### PR TITLE
Remove duplicated InsufficientFunds error member

### LINKED ISSUE #1440: InsufficientFunds is duplicated within coin_selection::Error and CreateTxError enums
**Describe the bug**  
Both `coin_selection::Error` and `CreateTxError` enums have an InsufficientFunds member. It is quite confusion prone

**Expected behavior**  
We shouldn't have duplicated enums

**Proposed solution**  
keep only `coin_selection::Error`'s member

### PR DESCRIPTION
**Pull request by e1a0a0ea**
closes #1440 

### Description

- Replace `CreateTxError::InsufficientFunds` use by `coin_selection::Error::InsufficientFunds`
- Remove `InsufficientFunds` member from `CreateTxError` enum
- Rename `coin_selection::Error` to `coin_selection::CoinSelectionError`

### Notes to the reviewers

- We could also keep both members but rename one of them to avoid confusion

#### All Submissions:

* [X] I've signed all my commits
* [X] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [X] I ran `cargo fmt` and `cargo clippy` before committing

### CODE REVIEW

**Comment by notmandatory** [comment]
Please also setup commit signing, see: https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Comment by matthiasdebernardini** [comment]
Maybe this belongs here better, basically, can this be disabled in anything but Network::Bitcoin?

https://github.com/bitcoindevkit/bdk/issues/1440#issuecomment-2108275322

**Review by oleonardolima — COMMENTED** [review]
Concept ACK, I do agree with Value's and Steve's comments above.

**Comment by oleonardolima** [comment]
> Maybe this belongs here better, basically, can this be disabled in anything but Network::Bitcoin?
> 
> [#1440 (comment)](https://github.com/bitcoindevkit/bdk/issues/1440#issuecomment-2108275322)

I personally don't think it's a good idea to "error-gate" based on the bitcoin::Network type, I would expect all behaviors that happen on mainnet (production per se) to happen on others, and even some nasty behaviors we may catch while testing on testnet/signet being prevented to land on mainnet code 😅.

**Comment by matthiasdebernardini** [comment]
That's a good point, @oleonardolima maybe the juice is not worth the squeeze on making this change.

**Review by oleonardolima — COMMENTED** [review]
Looking good! I left some comments, and I also think that it could be squashed into a single commit.

File: crates/bdk/tests/wallet.rs [hunk 1]
```diff
@@ -4,7 +4,7 @@ use assert_matches::assert_matches;
 use bdk::descriptor::{calc_checksum, IntoWalletDescriptor};
 use bdk::psbt::PsbtUtils;
 use bdk::signer::{SignOptions, SignerError};
-use bdk::wallet::coin_selection::{self, LargestFirstCoinSelection};
+use bdk::wallet::coin_selection::{self, CoinSelectionError, LargestFirstCoinSelection};
```
Comment (oleonardolima) [inline crates/bdk/tests/wallet.rs]: @e1a0a0ea Does this change still applies?

File: crates/bdk/src/wallet/mod.rs [hunk 2]
```diff
@@ -1662,10 +1664,12 @@ impl Wallet {
                     change_fee,
                 } = excess
                 {
-                    return Err(CreateTxError::InsufficientFunds {
-                        needed: *dust_threshold,
-                        available: remaining_amount.saturating_sub(*change_fee),
-                    });
+                    return Err(CreateTxError::CoinSelection(
+                        Error::InsufficientFunds {
```
Comment (oleonardolima) [inline crates/bdk/src/wallet/mod.rs]: @e1a0a0ea You could probably use a qualified version: `coin_selection::Error::InsufficientFunds` instead 🤔

**Review by oleonardolima — COMMENTED** [review]
Looking good! I left some comments, and I also think that it could be squashed into a single commit.

File: crates/bdk/src/wallet/mod.rs (hunk 2 above)
Comment (ValuedMammal) [reply crates/bdk/src/wallet/mod.rs]: Or just import the `InsufficientFunds` variant itself.

**Comment by notmandatory** [comment]
Please rebase again and fixup commits into one commit then this should be ready to merge.

File: crates/bdk/src/wallet/mod.rs (hunk 2 above)
Comment (evanlinjin) [reply crates/bdk/src/wallet/mod.rs]: I'm not a fan of importing the enum variant (can become confusing imo). I prefer the more verbose, but clearer option.

**Review by evanlinjin — APPROVED** [review]
ACK 29c8a00b435bdf2fa1d7c707ad09c1a47edc07b3

**Review by notmandatory — APPROVED** [review]
ACK 29c8a00b435bdf2fa1d7c707ad09c1a47edc07b3
