### PR TITLE
Revamp `KeychainTxOutIndex` API to be safer

### LINKED ISSUE #1268: Sync command grabs histories from lookahead spks.
**Describe the bug**  

There is a problem with the sync command in the esplora/electrum examples. Because of the 1000 lookahead default, we are trying to fetch txs for each spk (inc. lookahead).

We are fetching spks using `SpkTxOutIndex::all_spks()` and `SpkTxOutIndex::unused_spks()` to pass into `{Electrum|Esplora}::sync` (which includes lookahead spks).

**To Reproduce**  

Run `sync` command with esplora/electrum cli examples (not wallet).

**Expected behavior**  

We only fetch histories of revealed spks.

**Suggested implementation**

We probably need methods on `KeychainTxOutIndex` for non-lookahead versions for `all_spks` and `unused_spks`.

Maybe it is a bad idea to expose methods of `SpkTxOutIndex` from `KeychainTxOutIndex`?

### PR DESCRIPTION
**Pull request by evanlinjin**
Closes #1268

### Description

Previously `SpkTxOutIndex` methods can be called from `KeychainTxOutIndex` due to the `DeRef` implementation. However, the internal `SpkTxOut` will also contain lookahead spks resulting in an error-prone API.

`SpkTxOutIndex` methods are now not directly callable from `KeychainTxOutIndex`. Methods of `KeychainTxOutIndex` are renamed for clarity. I.e. methods that return an unbounded spk iter are prefixed with `unbounded`.

In addition to this, I also optimized the peek-address logic of `bdk::Wallet` using the optimized `<SpkIterator as Iterator>::nth` implementation.

### Notes to the reviewers

This is mostly refactoring, but can also be considered a bug-fix (as the API before was very problematic).

### Changelog notice

Changed
* Wallet's peek-address logic is optimized by making use of `<SpkIterator as Iterator>::nth`.
* `KeychainTxOutIndex` API is refactored to better differentiate between methods that return unbounded vs stored spks.
* `KeychainTxOutIndex` no longer directly exposes `SpkTxOutIndex` methods via `DeRef`. This was problematic because `SpkTxOutIndex` also contains lookahead spks which we want to hide.

Added
* `SpkIterator::descriptor` method which gets a reference to the internal descriptor. 

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### New Features:

~* [ ] I've added tests for the new feature~
* [x] I've added docs for the new feature

#### Bugfixes:

* [x] This pull request breaks the existing API
* [ ] I've added tests to reproduce the issue which are now passing
* [x] I'm linking the issue being fixed by this PR

### CODE REVIEW

File: crates/bdk/src/wallet/mod.rs [hunk 1]
```diff
@@ -792,36 +819,36 @@ impl<D> Wallet<D> {
     ///
     /// Note carefully that iterators go over **all** script pubkeys on the keychains (not what
     /// script pubkeys the wallet is storing internally).
-    pub fn spks_of_all_keychains(
+    pub fn all_unbounded_spk_iters(
```
Comment (danielabrozzoni) [inline crates/bdk/src/wallet/mod.rs:822]: The doc for this method is missing a \`, can you fix it please? Line 814, there's no ` at the start of the word "External"

File: example-crates/example_esplora/src/main.rs [hunk 2]
```diff
@@ -235,32 +235,32 @@ fn main() -> anyhow::Result<()> {
                 if *all_spks {
                     let all_spks = graph
                         .index
-                        .all_spks()
-                        .iter()
-                        .map(|(k, v)| (*k, v.clone()))
+                        .revealed_spks()
```
Comment (danielabrozzoni) [inline example-crates/example_esplora/src/main.rs:238]: Why is this iterating over revealed only? Was using `all_spks()` a bug?

File: crates/bdk/src/wallet/mod.rs [hunk 3]
```diff
@@ -792,36 +819,36 @@ impl<D> Wallet<D> {
...
 
     /// Gets an iterator over all the script pubkeys in a single keychain.
     ///
-    /// See [`spks_of_all_keychains`] for more documentation
+    /// See [`all_unbounded_spk_iters`] for more documentation
     ///
-    /// [`spks_of_all_keychains`]: Self::spks_of_all_keychains
-    pub fn spks_of_keychain(
+    /// [`all_unbounded_spk_iters`]: Self::all_unbounded_spk_iters
+    pub fn unbounded_spk_iter(
```
Comment (danielabrozzoni) [inline crates/bdk/src/wallet/mod.rs:833]: Is "unbounded" meant to be the contrary of "stored only"? 

To me, "unbounded_spk_iter" makes it sound like that there is a way to get a "bounded" spk iter, but then there's no method called like that. Maybe "all" would be a better word to communicate "it's all of the spks, not the stored only" - but then I wouldn't know how to call "all_unbounded_spk_iters" 😅 

This is definitely not a blocker, but I'm not convinced that "unbounded" is the right word here

File: crates/chain/src/keychain/txout_index.rs [hunk 4]
```diff
@@ -133,8 +125,11 @@ impl<K> KeychainTxOutIndex<K> {
     }
 }
 
+/// Methods that are *re-exposed* from the internal [`SpkTxOutIndex`].
 impl<K: Clone + Ord + Debug> KeychainTxOutIndex<K> {
     /// Return a reference to the internal [`SpkTxOutIndex`].
+    ///
+    /// **WARNING:** The internal index will contain lookahead spks.
```
Comment (danielabrozzoni) [inline crates/chain/src/keychain/txout_index.rs]: nit: maybe we should expand a little bit on stored vs revealed vs lookahead.

**Review by danielabrozzoni — COMMENTED** [review]
A few comments. I still haven't finished my review, but I wanted to post this in the meantime :)

File: example-crates/example_esplora/src/main.rs (hunk 2 above)
Comment (evanlinjin) [reply example-crates/example_esplora/src/main.rs:238]: Yes `all_spks` includes lookahead spks because it if `Deref`ed from `SpkTxOutIndex`. We want to hide all lookahead spks.

File: crates/bdk/src/wallet/mod.rs (hunk 3 above)
Comment (evanlinjin) [reply crates/bdk/src/wallet/mod.rs:833]: I don't think `all` is a better option. It can be interpreted as "all-revealed" or "all-stored". I'll be open for a better name, let me know if you have any further ideas.

File: crates/chain/src/keychain/txout_index.rs [hunk 5]
```diff
@@ -144,8 +139,103 @@ impl<K: Clone + Ord + Debug> KeychainTxOutIndex<K> {
...
+}
+
+impl<K: Clone + Ord + Debug> KeychainTxOutIndex<K> {
+    /// Iterate through all keychain identifiers.
+    pub fn keychains(&self) -> impl Iterator<Item = &K> + '_ {
+        self.keychains.keys()
+    }
+
+    /// Return a reference to the internal map of keychain to descriptors.
+    pub fn keychain_descriptors(&self) -> &BTreeMap<K, Descriptor<DescriptorPublicKey>> {
```
Comment (LLFourn) [inline crates/chain/src/keychain/txout_index.rs]: I don't think we need `keychains` and `keychain_descriptors`.

File: crates/chain/src/keychain/txout_index.rs (hunk 4 above)
Comment (LLFourn) [reply crates/chain/src/keychain/txout_index.rs]: I think we should do this on the main type. It already does this a bit but it could be clearer.

File: crates/bdk/src/wallet/mod.rs (hunk 3 above)
Comment (LLFourn) [reply crates/bdk/src/wallet/mod.rs:833]: I like unbounded better. Although there is no "bounded" version it implies the others are bounded (which they are). "unbounded" tells the caller that it's never going to stop so it would only make sense to use this in a "stop gap" context.

File: crates/chain/src/keychain/txout_index.rs (hunk 4 above)
Comment (evanlinjin) [reply crates/chain/src/keychain/txout_index.rs]: 83e7b7ec402bef27c3f83876f346ec2abd23eff1

**Review by LLFourn — APPROVED** [review]
ACK 83e7b7ec402bef27c3f83876f346ec2abd23eff1

File: crates/chain/src/keychain/txout_index.rs [hunk 6]
```diff
@@ -133,8 +165,12 @@ impl<K> KeychainTxOutIndex<K> {
     }
 }
 
+/// Methods that are *re-exposed* from the internal [`SpkTxOutIndex`].
 impl<K: Clone + Ord + Debug> KeychainTxOutIndex<K> {
     /// Return a reference to the internal [`SpkTxOutIndex`].
+    ///
+    /// **WARNING:** The internal index will contain lookahead spks. Refer to
+    /// [struct-level docs](KeychainTxOutIndex) for more about `lookahead`.
```
Comment (danielabrozzoni) [inline crates/chain/src/keychain/txout_index.rs:176]: Do you think we will eventually avoid exposing `inner`, or is it useful for some use cases, and so exposing it with a warning is good enough?

File: example-crates/example_esplora/src/main.rs (hunk 2 above)
Comment (danielabrozzoni) [reply example-crates/example_esplora/src/main.rs:238]: Should we clarify this change in the changelog?

**Review by danielabrozzoni — COMMENTED** [review]
From my understanding, this PR is making some `SpkTxOutIndex` methods slightly more difficult to call (you need to use `KeychainTxOutIndex::inner` instead of just using `Deref`).

These are SpkTxOutIndex methods that are not directly exposed from `KeychainTxOutIndex`:
- `all_spks`
- `insert_spk`
- `outputs_in_range`
- `txouts`
- `txouts_in_tx`

It makes sense to me that `insert_spk` and `all_spks` are not exposed: you should let the `KeychainTxOutIndex` insert the spks, and `all_spks` exposes the lookahead spks.

But I just can't figure out why `outputs_in_range`, `txouts`, and `txouts_in_tx` shouldn't be exposed as well - is there a particular reason?

File: crates/chain/src/keychain/txout_index.rs (hunk 6 above)
Comment (evanlinjin) [reply crates/chain/src/keychain/txout_index.rs:176]: I would assume in some cases getting lookahead spks will be handy.

I.e. we haven't finalized how a CBF chain-source will look like and how it will interact with `bdk_chain` structures. However, it might make sense to match lookahead spks against GCS (filters). Or maybe using an *unbounded* spk iterator makes more sense?

Maybe later on, we determine that it will make sense to use helper methods on `KeychainTxOutIndex` instead. However, for most usecases now, outputting lookahead spks is almost always non-intentional.

Comment (evanlinjin) [reply crates/chain/src/keychain/txout_index.rs:176]: In summary, I think we should keep `.inner` with a warning (for now).

**Comment by evanlinjin** [comment]
> But I just can't figure out why `outputs_in_range`, `txouts`, and `txouts_in_tx` shouldn't be exposed as well - is there a particular reason?

@danielabrozzoni I didn't include them because they weren't used in the examples. I guess it doesn't hurt to include?

**Review by danielabrozzoni — APPROVED** [review]
ACK 71fff1613d1c167d180636857063e181f6acedf1
