### PR TITLE
Remove redundant duplicated keys check

### LINKED ISSUE #760: BDK shouldn't complain if there are duplicated keys in TapLeaves
**Describe the bug**  
BDK returns an error if there are duplicated keys in different tap leaves

**To Reproduce**  
Trying to create a wallet using the descriptor 
```
tr(020202020202020202020202020202020202020202020202020202020202020202,{thresh(1,pk(tpubD6NzVbkrYhZ4WrjhC6iLoEYLhozBrsUjMU4poViXC57heJ8Q3EimPpoUrUKvajtkgfuPpf8Hku7X4sBazDFKqTAiSzGUaK2iCga42pcaFWe),s:pk(tpubD6NzVbkrYhZ4Y2eyqr1oFLQN1c9WUBVu9PyPxKQKnffx5wC1sumGAV9KK2zUj46oDyNCD3GHcfR9e23nFaioBfoBN9a2TtdLoSkKXw9bW1r)),and_v(v:thresh(1,pk(tpubD6NzVbkrYhZ4WrjhC6iLoEYLhozBrsUjMU4poViXC57heJ8Q3EimPpoUrUKvajtkgfuPpf8Hku7X4sBazDFKqTAiSzGUaK2iCga42pcaFWe),s:pk(tpubD6NzVbkrYhZ4Y2eyqr1oFLQN1c9WUBVu9PyPxKQKnffx5wC1sumGAV9KK2zUj46oDyNCD3GHcfR9e23nFaioBfoBN9a2TtdLoSkKXw9bW1r)),older(1))})#kgu06739
```

will give back `Error: Descriptor(DuplicatedKeys)`, even tho the duplicated keys are in different tap leaves, which should be fine

The descriptor has been created like this:
```
    let keys = [
        "tpubD6NzVbkrYhZ4WrjhC6iLoEYLhozBrsUjMU4poViXC57heJ8Q3EimPpoUrUKvajtkgfuPpf8Hku7X4sBazDFKqTAiSzGUaK2iCga42pcaFWe",
        "tpubD6NzVbkrYhZ4Y2eyqr1oFLQN1c9WUBVu9PyPxKQKnffx5wC1sumGAV9KK2zUj46oDyNCD3GHcfR9e23nFaioBfoBN9a2TtdLoSkKXw9bW1r",
    ];

    let keys_joined: String = keys.into_iter().map(|k| format!("pk({})", k)).collect::<Vec<_>>().join(",");

    let first_policy_str = format!("thresh({},{})", keys.len() - 1, keys_joined);
    let first_policy = Concrete::<String>::from_str(&first_policy_str)?.compile()?;
    let first_tap_leaf = TapTree::Leaf(Arc::new(first_policy));

    let second_policy_str = format!("and(older(1),thresh({},{}))",keys.len() / 2, keys_joined);
    let second_policy = Concrete::<String>::from_str(&second_policy_str)?.compile()?;
    let second_tap_leaf = TapTree::Leaf(Arc::new(second_policy));

    let dummy_internal = "020202020202020202020202020202020202020202020202020202020202020202".to_string();
    let tap_tree = TapTree::Tree(Arc::new(first_tap_leaf), Arc::new(second_tap_leaf));
    let descriptor = Descriptor::new_tr(dummy_internal, Some(tap_tree))?;
    println!("{}", descriptor);

```

**Expected behavior**  
The wallet is created normally

**Build environment**  
 - BDK tag/commit: v0.22

### PR DESCRIPTION
**Pull request by afilini**
### Description

This check is redundant since it's already performed by miniscript (see https://docs.rs/miniscript/7.0.0/miniscript/miniscript/analyzable/enum.AnalysisError.html#variant.RepeatedPubkeys) and it was incorrectly failing on tr descriptors that contain duplicated keys across different taproot leaves

Fixes #760

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### Bugfixes:

* [x] This pull request breaks the existing API
* [x] I've added tests to reproduce the issue which are now passing
* [x] I'm linking the issue being fixed by this PR

### CODE REVIEW

File: src/wallet/mod.rs [hunk 1]
```diff
@@ -2077,6 +2077,10 @@ pub(crate) mod test {
         "tr(cNJmN3fH9DDbDt131fQNkVakkpzawJBSeybCUNmP1BovpmGQ45xG,{pk(tprv8ZgxMBicQKsPdDArR4xSAECuVxeX1jwwSXR4ApKbkYgZiziDc4LdBy2WvJeGDfUSE4UT4hHhbgEwbdq8ajjUHiKDegkwrNU6V55CxcxonVN/*),pk(8aee2b8120a5f157f1223f72b5e62b825831a27a9fdf427db7cc697494d4a642)})"
     }
 
+    pub(crate) fn get_test_tr_dup_keys() -> &'static str {
```
Comment (notmandatory) [inline src/wallet/mod.rs:2080]: Could this string just be added to `test_taproot_load_descriptor_duplicated_keys` or do you anticipate using this descriptor in other tests?

**Review by danielabrozzoni — APPROVED** [review]
Code review ACK e2bf9734b16f5a0f419f1c1fc39c9773fd7e1128 - the code looks good to me, but I didn't test manually

File: src/wallet/mod.rs (hunk 1 above)
Comment (afilini) [reply src/wallet/mod.rs:2080]: I think it could be used in other tests, for example if we want to see how the policy module deals with duplicated keys
