### PR TITLE
fix(electrum): prevent `fetch_prev_txout` from querying coinbase transactions

### LINKED ISSUE #1698: bdk_electrum: don't query prevouts of coinbase tx
"fetch_prev_txout should not try to query the prevouts of coinbase transactions, this will query a 000...000 transaction to the Electrum server which will return an error and will make the overall sync() fail."

### PR DESCRIPTION
**Pull request by LagginTimes**
Fixes #1698.

### Description

`fetch_prev_txout` should not try to query the prevouts of coinbase transactions, as it may result in the Electrum server returning an error which would cause the overall `sync`/`full_scan` to fail. Without this critical bug fix,  `bdk_electrum` will crash when someone tracks an address being mined to.

### Changelog notice

* `fetch_prev_txout` no longer queries coinbase transactions.

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### Bugfixes:

* [ ] This pull request breaks the existing API
* [x] I've added tests to reproduce the issue which are now passing
* [x] I'm linking the issue being fixed by this PR

### CODE REVIEW

**Comment by notmandatory** [comment]
Needs a test then this looks good to go for 1.0.0.

File: crates/electrum/src/bdk_electrum_client.rs [hunk 1]
```diff
@@ -531,3 +531,52 @@ fn chain_update(
...
+
+        assert!(coinbase_tx.is_coinbase());
+
+        // Test that `fetch_prev_txout` does not process our coinbase transaction. If it attempts to
+        // fetch our previously inserted transaction with a txid of all zeros, this test will crash.
+        let mut tx_update = TxUpdate {
+            txs: vec![Arc::new(coinbase_tx)],
+            ..Default::default()
+        };
+        let _ = client.fetch_prev_txout(&mut tx_update);
```
Comment (evanlinjin) [inline crates/electrum/src/bdk_electrum_client.rs]: You didn't check the result here.

**Comment by ValuedMammal** [comment]
For the test can't we also build a `SyncRequest` with the same address that receives the block reward? which would cause electrum to throw an error without the fix in this PR.

File: crates/electrum/src/bdk_electrum_client.rs [hunk 2]
```diff
@@ -531,3 +531,52 @@ fn chain_update(
...
+        let client = BdkElectrumClient::new(electrum_client);
+
+        // Calling `fetch_prev_txout` on a coinbase transaction triggers a `fetch_tx` on a
+        // transaction with a txid of all zeros. However, since the error from Electrum's
+        // `transaction_get` is propagated upwards and may not interrupt the `sync`/`full_scan`
+        // process, we have to insert a transaction with a txid of all zeros into the `tx_cache` to
+        // ensure `fetch_prev_txout` will fail if it attempts to fetch this transaction.
+        let mut tx_cache = client.tx_cache.lock().unwrap();
+        tx_cache.insert(Txid::all_zeros(), new_tx(0).into());
+        drop(tx_cache);
```
Comment (evanlinjin) [inline crates/electrum/src/bdk_electrum_client.rs]: This is not needed now since we are checking the error returned by `client.fetch_prev_txout`.

**Comment by jirijakes** [comment]
tACK https://github.com/bitcoindevkit/bdk/commit/ccf13ec3624f55a387fad958fe342d643d356825. Test breaks when coinbase TX queried.

<details><summary>Failed test</summary>
<pre><code>
running 1 test
test bdk_electrum_client::test::test_fetch_prev_txout_with_coinbase ... FAILED

failures:

failures:
   bdk_electrum_client::test::test_fetch_prev_txout_with_coinbase

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.20s


--- STDERR:              bdk_electrum bdk_electrum_client::test::test_fetch_prev_txout_with_coinbase ---
thread 'bdk_electrum_client::test::test_fetch_prev_txout_with_coinbase' panicked at crates/electrum/src/bdk_electrum_client.rs:570:9:
assertion failed: client.fetch_prev_txout(&mut tx_update).is_ok()
</code></pre>
</details>

**Comment by LagginTimes** [comment]
> For the test can't we also build a `SyncRequest` with the same address that receives the block reward? which would cause electrum to throw an error without the fix in this PR.

Yes, something like this would work as well:

```
#[test]
fn test_sync_with_coinbase() -> anyhow::Result<()> {
    let env = TestEnv::new()?;
    let electrum_client = electrum_client::Client::new(env.electrsd.electrum_url.as_str())?;
    let client = BdkElectrumClient::new(electrum_client);

    // Setup address.
    let spk_to_track = ScriptBuf::new_p2wsh(&WScriptHash::all_zeros());
    let addr_to_track = Address::from_script(&spk_to_track, bdk_chain::bitcoin::Network::Regtest)?;

    // Setup receiver.
    let (mut recv_chain, _) = LocalChain::from_genesis_hash(env.bitcoind.client.get_block_hash(0)?);
    let mut recv_graph = IndexedTxGraph::<ConfirmationBlockTime, _>::new({
        let mut recv_index = SpkTxOutIndex::default();
        recv_index.insert_spk((), spk_to_track.clone());
        recv_index
    });

    // Mine some blocks.
    env.mine_blocks(101, Some(addr_to_track))?;
    env.wait_until_electrum_sees_block(Duration::from_secs(6))?;

    // Check to see if electrum syncs properly.
    assert!(sync_with_electrum(
        &client,
        [spk_to_track.clone()],
        &mut recv_chain,
        &mut recv_graph,
    )
    .is_ok());

    Ok(())
}
```

I believe the current implementation in the PR is more straightforward and easier to understand. However, I would appreciate hearing others' thoughts on this.

**Review by ValuedMammal — APPROVED** [review]
ACK ccf13ec3624f55a387fad958fe342d643d356825

**Comment by evanlinjin** [comment]
@LagginTimes let's include both tests. The `test_sync_with_coinbase` is excellent.

**Review by evanlinjin — APPROVED** [review]
ACK ccf13ec3624f55a387fad958fe342d643d356825

**Review by notmandatory — APPROVED** [review]
ACK ccf13ec3624f55a387fad958fe342d643d356825

**Comment by notmandatory** [comment]
Looks like this is ready to go once `test_sync_with_coinbase()` is added. I'm also happy to have it merged as is.

**Comment by LagginTimes** [comment]
`test_sync_with_coinbase()` has been added.

**Review by evanlinjin — APPROVED** [review]
ACK d4ef26611b83baefac65fffc0758c6ac55ade9cb
