### PR TITLE
[wallet] Add "needed" and "available" metadata to Error::Insufficient…

### LINKED ISSUE #164: InsufficientFunds should include more information
I think it should be `InsufficientFunds { needed, available }`.

### PR DESCRIPTION
**Pull request by justinmoon**
Closes #164

### CODE REVIEW

File: src/error.rs [hunk 1]
```diff
@@ -39,7 +39,7 @@ pub enum Error {
     NoRecipients,
     NoUtxosSelected,
     OutputBelowDustLimit(usize),
-    InsufficientFunds,
+    InsufficientFunds(u64, u64), // amount needed, amount available
```
Comment (justinmoon) [inline src/error.rs]: Would it be better to make a struct for this pair?

Also, would it be better to call the second one "amount selected" instead of "amount available"? Are there cases where the wallet may have enough but coin selection doesn't choose the right combination of utxos?

File: src/wallet/mod.rs [hunk 2]
```diff
@@ -739,7 +740,11 @@ where
             }
             Some(_) if change_val_after_add.is_dust() => {
                 // single_recipient but the only output would be below dust limit
-                return Err(Error::InsufficientFunds); // TODO: or OutputBelowDustLimit?
+                // TODO: or OutputBelowDustLimit?
+                return Err(Error::InsufficientFunds(
+                    DUST_LIMIT_SATOSHI,
+                    change_val_after_add,
+                ));
```
Comment (justinmoon) [inline src/wallet/mod.rs]: If I understand correctly, it seems like the real error here is that the user provided invalid recipients: the output amounts sum to less than the dust limit. Is that accurate?

So maybe an `InvalidRecipients` error type would be better???

Comment (murchandamus) [reply src/wallet/mod.rs]: Yeah, `InsufficientFunds` is definitely misleading.

File: src/error.rs (hunk 1 above)
Comment (afilini) [reply src/error.rs]: More than a struct you could just convert this to a named enum variant, like `InsufficientFunds { needed: u64, available: u64 }`

File: src/wallet/mod.rs (hunk 2 above)
Comment (afilini) [reply src/wallet/mod.rs]: I think specific branch is hit when `TxBuilder::set_single_recipient()` is enabled, which means that either `TxBuilder::drain_wallet()` is also enabled, or that the user specified manually which utxos to pick and then `TxBuilder::manually_selected_only()` has been set.

So this error happens basically when the user asks to make a tx without change (either by spending everything or only some specific utxos) but the amount selected is not enough to even make that single output.

I agree that the error is not the best, just wanted to provide more context to discuss what this could be changed to..

Comment (justinmoon) [reply src/wallet/mod.rs]: So `InsufficientFunds` is an accurate description in the `TxBuilder::drain_wallet()` case, but potentially not an accurate description in the `TxBuilder::manually_selected_only()` case?

Edit: maybe the first case would be better described as `BalanceBelowDustThreshold` or something ...

File: src/error.rs (hunk 1 above)
Comment (justinmoon) [reply src/error.rs]: Thanks! Updated accordingly.

File: src/wallet/mod.rs (hunk 2 above)
Comment (afilini) [reply src/wallet/mod.rs]: There's also one extra complication, and that is the fact that `drain_wallet()` also takes the "unspendable" utxos into account.. so there could be cases where you do have enough funds in your wallet, but you've marked some utxos as "unspendable" and without them your balance is too low.

Also it's not technically the balance "below dust", because the fees are also taken into account. So it's basically "at this fee rate, with the utxos i'm allowed to spend, i can't make a non-dust output".

The thing about the fees is true for the manual coin selection as well, but on the other end the manual coin selection has precedence over the "unspendable" utxos, so that's ignored in that case.

Comment (LLFourn) [reply src/wallet/mod.rs]: To me insufficient funds still makes sense if you've marked things as unspendable etc. It just means what was specified as spendable was insufficient so that the wallet's funds in total were insufficient. 

I don't get how it's possible to select an input, only have one output and not be able to produce a non-dust output (surely the input must also be below the dust limit then!). It does sound like `OutputBelowDustLimit` might be better for this awkward situtation.

Comment (afilini) [reply src/wallet/mod.rs]: It's a very weird corner-case but with very high fees it could happen: basically you could consume almost entirely the inputs in fees and what's left is not enough to build one output.

**Review by LLFourn — APPROVED** [review]

**Comment by afilini** [comment]
Needs a rebase and then I'll merge it

**Comment by justinmoon** [comment]
Rebased

**Comment by notmandatory** [comment]
utACK 7bc8c3c
