### PR TITLE
Fix the recovery of a descriptor given a PSBT

### LINKED ISSUE #108: OfflineWallet limitations/bugs
I found two limitations/bugs in `Wallet<OfflineBlockchain, _>` implementation:

- [ ] `is_mine` doesn't work properly as the DB isn't populated properly. Proposed fixes:
  * Either make the method unavailable
  * or implement script bruteforcing to find out if a script is ours
- [ ] `sign` doesn't work. The descriptor recovery is broken (is needed because the DB isn't populated with UTXOs) because it recovers the generic descriptor (drops last child number) while the finalizer in rust-miniscript expects a concrete descriptor with the full derivation paths.
  * I already have a working fix that could break other things, I opened #109 to discuss it

### PR DESCRIPTION
**Pull request by afilini**
This commit upgrades `rust-miniscript` with a fix to only return the prefix that
matches a `hd_keypath` instead of the full derivation path, and then adapts the
signer code accordingly.

This commit closes #108 and #109.

### CODE REVIEW

**Comment by afilini** [comment]
@sgeisler I tried running your `multisig.rs` example from #109 with this fix and it seemed to be working nicely. I'll give you some time to play around with this before merging, let me know if you have any problems/questions!

File: src/descriptor/mod.rs [hunk 1]
```diff
@@ -358,13 +358,12 @@ impl DescriptorMeta for Descriptor<DescriptorPublicKey> {
...
                     .get_key_value(&root_fingerprint)
                     .and_then(|(fingerprint, path)| xpub.matches(*fingerprint, path))
-                    .map(|prefix_path| prefix_path.into_iter().cloned().collect::<Vec<_>>())
                     .map(|prefix| {
                         index
                             .get(&xpub.root_fingerprint())
                             .unwrap()
                             .into_iter()
-                            .skip(prefix.len())
+                            .skip(prefix.into_iter().count())
```
Comment (sgeisler) [inline src/descriptor/mod.rs:366]: We really need to fix the ergonomics `DerivationPath` :grimacing:

**Review by sgeisler — APPROVED** [review]
Looks good!

File: src/descriptor/mod.rs (hunk 1 above)
Comment (afilini) [reply src/descriptor/mod.rs:366]: Yeah it's kinda weird at the moment because you keep mixing up `DerivationPath` with slices or vecs of `ChildNumber`

**Comment by afilini** [comment]
I had to make a couple more changes because the signer needs to use the full path and not just the suffix to derive the `xprv`. While I was at it, I also added a check to make sure that when we derive an `xprv` we get the expected public key as it is specified in the `hd_keypaths`.

Also added a simple signing test using a key with a longer path that would have failed before those last changes.

**Comment by afilini** [comment]
Rebased on #111 which I'm planning to merge first. I'm waiting for travis to start working again before I can merge, since `master` is protected and requires the CI to pass.
