### PR TITLE
[bug-fix] Set the db sync height

### LINKED ISSUE #719: [bug] get_funded_wallet() does not return balance
**Describe the bug**  
After recent changes in balance calculation, the get_funded_wallet test function will not show any balance because we are not setting the sync_time in the populate_test_db macro..

Our existing tests are not failing, because even if the balance is shown zero, it will still be able to produce transactions. But its causing test failure in downstream bdk-reserves crate where the balances are required to assert scenarios.

**To Reproduce**  
```
let (wallet, _, _) = get_funded_wallet(get_test_wpkh());
assert_eq!(wallet.get_balance().unwrap().confirmed, 0);
```
**Expected behavior**  
```
let (wallet, _, _) = get_funded_wallet(get_test_wpkh());
assert_eq!(wallet.get_balance().unwrap().confirmed, 50000);
```

### PR DESCRIPTION
**Pull request by rajarshimaitra**
### Description

Fixes #719 

Previously we weren't setting the db sync height in populate_test_db
macro even when current height is provided.. This creates a bug that
get_funded_wallet will return 0 balance.

This PR fixes the populate_test_db macro and updates tests which were
previously dependent on the unsynced wallet behavior.

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### Bugfixes:

* [x] I've added tests to reproduce the issue which are now passing
* [x] I'm linking the issue being fixed by this PR

### CODE REVIEW

File: src/wallet/mod.rs [hunk 1]
```diff
@@ -2862,7 +2898,21 @@ pub(crate) mod test {
...
+            Network::Regtest,
+            AnyDatabase::Memory(MemoryDatabase::new()),
+        )
+        .unwrap();
+
+        let tx_meta = testutils! {
+                @tx ( (@external descriptors, 0) => 50_000 ) (@confirmations 1)
+        };
+
+        // Add the transaction to our db, but do not sync the db.
```
Comment (danielabrozzoni) [inline src/wallet/mod.rs]: Same here, a comment would be really helpful!

File: src/wallet/mod.rs [hunk 2]
```diff
@@ -2364,7 +2385,22 @@ pub(crate) mod test {
...
```
Comment (danielabrozzoni) [inline src/wallet/mod.rs]: Can we add a comment here explaining why we don't want to sync the db?

Comment (rajarshimaitra) [reply src/wallet/mod.rs]: Done.. Yes would be helpful..

**Comment by rajarshimaitra** [comment]
Updated with review comments..

File: src/wallet/mod.rs [hunk 3]
```diff
@@ -2364,7 +2385,23 @@ pub(crate) mod test {
...
+            AnyDatabase::Memory(MemoryDatabase::new()),
+        )
+        .unwrap();
+
+        let tx_meta = testutils! {
+                @tx ( (@external descriptors, 0) => 50_000 ) (@confirmations 1)
+        };
+
+        // Add the transaction to our db, but do not sync the db. Unsynced db
+        // should trigger the default sequqence value for a new transaction as 0xFFFFFFFF
```
Comment (vladimirfomene) [inline src/wallet/mod.rs]: Nits: spelling error on `sequence`

File: src/wallet/mod.rs [hunk 4]
```diff
@@ -2862,7 +2899,22 @@ pub(crate) mod test {
...
```
Comment (vladimirfomene) [inline src/wallet/mod.rs]: Nits: spelling error on `sequence`

**Review by vladimirfomene — COMMENTED** [review]
utACK

File: src/wallet/mod.rs (hunk 3 above)
Comment (rajarshimaitra) [reply src/wallet/mod.rs]: Thanks.. Done..

**Comment by rajarshimaitra** [comment]
Thanks @vladimirfomene for the catches.. Updated..

**Review by danielabrozzoni — APPROVED** [review]
utACK b8ce842ce01752ce693759bbfa5007f5619c2424

File: src/database/memory.rs [hunk 5]
```diff
@@ -512,13 +513,29 @@ macro_rules! populate_test_db {
...
             .and_then(|v| if v == 0 { None } else { Some(v) })
             .map(|conf| $crate::BlockTime {
-                height: current_height.unwrap().checked_sub(conf as u32).unwrap() + 1,
+                height: height.checked_sub(conf as u32).unwrap() + 1,
                 timestamp: 0,
-            });
+            })
+        } else {
+            None
+        };
```
Comment (afilini) [inline src/database/memory.rs]: I don't think it's ok to silently drop the `min_confirmations` if the current height is not provided. I would rather keep what we had before with a better error message, by changing the `unwrap()` into an `expect()`.

File: src/database/memory.rs [hunk 6]
```diff
@@ -512,13 +513,29 @@ macro_rules! populate_test_db {
...
+
+        // Set the database sync height if current height is provided
+        if let Some(height) = current_height {
+            let sync_time = SyncTime {
+                block_time: BlockTime {
+                    height,
+                    timestamp: 0
+                }
+            };
+            db.set_sync_time(sync_time).unwrap();
```
Comment (afilini) [inline src/database/memory.rs:539]: I think here you should only keep the most recent sync time, so instead of just setting it you should first check if something is present and compare the two

File: src/database/memory.rs (hunk 5 above)
Comment (rajarshimaitra) [reply src/database/memory.rs]: Makes sense..

File: src/database/memory.rs (hunk 6 above)
Comment (rajarshimaitra) [reply src/database/memory.rs:539]: It should.. Done.,.

**Comment by rajarshimaitra** [comment]
Thanks @afilini  for the look.. Updated as suggested.. In the last dev call we talked about releasing this as a patch version for some downstream libs to update.. See https://github.com/bitcoindevkit/bdk-cli/pull/102#issuecomment-1226928903

**Comment by danielabrozzoni** [comment]
Sorry I didn't notice the two issues that Alekos has found, I should have inspected the code better.

re-utACK a72a97b663fa71cb66e91f1187dc257762dbb2a7

**Comment by notmandatory** [comment]
@rajarshimaitra  even though we talked about doing a fix release for this, since this is a test framework fix and code freeze for 0.22 is next Wed. (Aug 31), can we skip doing a fix release only for this PR and wait for 0.22 to put it out (Sept 7)?

**Comment by rajarshimaitra** [comment]
@notmandatory sounds good to me.. Only needed for the bdk-cli PR.. That can wait a bit..

File: src/database/memory.rs [hunk 7]
```diff
@@ -512,14 +513,32 @@ macro_rules! populate_test_db {
...
+                height: current_height.expect("Current height is needed for testing transaction with min-confirmation values").checked_sub(conf as u32).unwrap() + 1,
                 timestamp: 0,
             });
 
+        // Set the database sync_time.
+        // Check if the current_height is less than already known sync height, apply the max
+        // If any of them is None, the other will be applied instead.
+        // If both are None, this will not be set.
+        if let Some(height) = db.get_sync_time().unwrap()
+                                .and_then(|sync_time| Some(sync_time.block_time.height))
```
Comment (afilini) [inline src/database/memory.rs]: nit: You can replace `and_then` with `map` because you always return `Some()`

**Comment by rajarshimaitra** [comment]
Updated and rebased..

**Review by afilini — COMMENTED** [review]
ACK 08668ac46247d527cc53af5b6f359b1fa4e3b6aa
