### PR TITLE
fix(wallet): only mark change address used if `create_tx` succeeds

### LINKED ISSUE #1578: PSBT Creation: Change Address Index Skipped on InsufficientFunds
**Describe the bug**  

When I create a PSBT using TxBuilder, we typically add the recipients, amounts, and other necessary data, and everything works as expected. However, sometimes when we receive an InsufficientFunds exception, the change address index increases, causing it to be skipped in next call to create_psbt, which then selects a new unused one.

In the create_psbt function and noticed that the latest unused index in the KeychainKind::Internal is marked as used first, but when the InsufficientFunds exception occurs, it doesn’t reset back to unused.

please take a look thx

### PR DESCRIPTION
**Pull request by ValuedMammal**
If no drain script is specified in tx params then we get it from the change keychain by looking at the next unused address. Before this PR we marked the index used regardless of whether a change output is finally added. Then if creating a psbt failed, we never restored the unused status of the change address, so creating the next tx would have revealed an extra one.

We want to mark the change address used so that other callers won't attempt to use the same address between the time we create the tx and when it appears on chain. With this PR we only mark the change address used if we successfully create a psbt and the drain script is used in the change output.

fixes bitcoindevkit/bdk#1578 

### Notes to the reviewers

An early idea was to unmark the change address used if we fail to create a tx due to `InsufficientFunds`, but after looking into it I figure it doesn't totally make sense to mark the address used before we've determined that a change output is necessary. Further, `create_tx` can fail in other ways besides running coin selection, so I moved the `mark_used` logic to the end of the function.

### Changelog notice

Fixed an issue that caused an unused internal address to be skipped when creating transactions (#1578)

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### Bugfixes:

* [x] I've added tests to reproduce the issue which are now passing
* [x] I'm linking the issue being fixed by this PR

### CODE REVIEW

**Comment by ValuedMammal** [comment]
This might also be related to bitcoindevkit/bdk_wallet#74

File: crates/wallet/src/wallet/mod.rs [hunk 1]
```diff
@@ -1452,12 +1452,11 @@ impl Wallet {
             Some(ref drain_recipient) => drain_recipient.clone(),
             None => {
                 let change_keychain = self.map_keychain(KeychainKind::Internal);
-                let ((index, spk), index_changeset) = self
+                let ((_index, spk), index_changeset) = self
                     .indexed_graph
                     .index
                     .next_unused_spk(change_keychain)
```
Comment (evanlinjin) [inline crates/wallet/src/wallet/mod.rs]: I'm wondering whether it will make sense to introduce a `KeychainTxOutIndex::next_unused_spk_without_revealing`.

```rust
    pub fn next_unused_spk_without_revealing(&self, keychain: K) -> Option<Indexed<ScriptBuf>> {
        let next_unused = self
            .unused_keychain_spks(keychain.clone())
            .next()
            .map(|(i, spk)| (i, spk.to_owned()));
        let (next_index_to_reveal, _) = self.next_index(keychain.clone())?;
        next_unused.or_else(|| {
            self.unbounded_spk_iter(keychain)
                .expect("descriptor must exist")
                .nth(next_index_to_reveal as _)
        })
    }

```

This way, we can avoid potentially-revealing an spk here (which might not be used), and avoid recording the new revealed index in `self.stage`.

We can use a new variable `let mut drain_keychain_index = Option::<(KeychainKind, u32)>::None` to actually do a mutation later on (when we determine that we will have a change output in our tx).

File: crates/wallet/src/wallet/mod.rs [hunk 2]
```diff
@@ -1557,6 +1556,19 @@ impl Wallet {
         params.ordering.sort_tx_with_aux_rand(&mut tx, rng);
 
         let psbt = self.complete_transaction(tx, coin_selection.selected, params)?;
+
+        if psbt
+            .unsigned_tx
+            .output
+            .iter()
+            .any(|txout| txout.script_pubkey == drain_script)
+        {
```
Comment (evanlinjin) [inline crates/wallet/src/wallet/mod.rs]: It will be more *correct* to check the `excess` variable. The caller may set the recipient address as the drain address that we obtained from the index. In this case, it might be unexpected for the caller to have this spk marked as used.

```rust
        if matches!(excess, &coin_selection::Excess::Change { .. }) { }
```

**Review by evanlinjin — COMMENTED** [review]
Thanks for taking this forward. Let me know what you think about the `next_unused_spk_without_revealing` idea.

File: crates/wallet/src/wallet/mod.rs (hunk 2 above)
Comment (ValuedMammal) [reply crates/wallet/src/wallet/mod.rs]: Yes that will be better, I think it's resolved by 6afde0b7761113775bdca11ee720777cd178acf7

File: crates/wallet/src/wallet/mod.rs (hunk 1 above)
Comment (ValuedMammal) [reply crates/wallet/src/wallet/mod.rs]: Thinking through this what I think you're advocating is something like "next unused or else peek next index". Would you then reveal the next index in the event that the change address is used in the tx?

Also if we don't reveal it here are we relying on `index_of_spk` returning a value in order to mark it used? (which should be the case as long as the lookahead > 0)

Comment (ValuedMammal) [reply crates/wallet/src/wallet/mod.rs]: > are we relying on index_of_spk returning a value in order to mark it used?

I think no because we'll just use `drain_keychain_index` instead of `index_of_spk`

Comment (ValuedMammal) [reply crates/wallet/src/wallet/mod.rs]: I pushed 9bd6c4703fecedf4237dff3091e515d3d000951a to show what that would look like, but I'm not certain this is truly better than revealing one if needed. If we reveal an address but don't use it, then future calls to `create_tx` shouldn't cause a runaway of revealed addresses

Comment (ValuedMammal) [reply crates/wallet/src/wallet/mod.rs]: alternatively I'm considering the approach in 9341041cfdadc329f7850cf028059db84d4eb658

File: crates/wallet/src/wallet/mod.rs [hunk 3]
```diff
@@ -1457,8 +1458,8 @@ impl Wallet {
                     .index
                     .next_unused_spk(change_keychain)
```
Comment (evanlinjin) [inline crates/wallet/src/wallet/mod.rs]: It's a bug to reveal something when we error out. Calling `.next_unused_spk` may reveal an spk here. I think it makes sense to fix this in the same PR.

File: crates/wallet/src/wallet/mod.rs [hunk 4]
```diff
@@ -1557,6 +1568,20 @@ impl Wallet {
...
+                let (_, index_changeset) = self
+                    .indexed_graph
+                    .index
+                    .reveal_to_target(keychain, index)
+                    .expect("must not be None");
+                self.stage.merge(index_changeset.into());
+                self.mark_used(keychain, index);
+            }
+        }
+
```
Comment (evanlinjin) [inline crates/wallet/src/wallet/mod.rs]: Nit

```suggestion
        if let (Excess::Change { .. }, Some((keychain, index))) = (excess, drain_index) {
            let (_, index_changeset) = self
                .indexed_graph
                .index
                .reveal_to_target(keychain, index)
                .expect("must not be None");
            self.stage.merge(index_changeset.into());
            self.mark_used(keychain, index);
        }

```

File: crates/wallet/tests/wallet.rs [hunk 5]
```diff
@@ -1392,6 +1392,55 @@ fn test_create_tx_global_xpubs_with_origin() {
...
+    let err = builder.finish().unwrap_err();
+    assert!(matches!(
+        err,
+        CreateTxError::CoinSelection(Error::InsufficientFunds { .. }),
+    ));
+    assert_eq!(
+        wallet.next_unused_address(KeychainKind::Internal),
+        internal_addr0,
+        "create tx fail should not mark change address used",
+    );
```
Comment (evanlinjin) [inline crates/wallet/tests/wallet.rs]: Nit: Can also check that the `last_derivation_index` is not incremented. An easy way to do this is to check whether `Wallet::stage` is empty.

**Review by evanlinjin — APPROVED** [review]
ACK 18ecd0641438c455e8ca9a666d0306b31c2a0d8f

File: crates/wallet/tests/wallet.rs (hunk 5 above)
Comment (ValuedMammal) [reply crates/wallet/tests/wallet.rs]: Added checks for derivation index in 004b0caf30c08b4177a92076fdc448191ce9cf89

File: crates/wallet/tests/wallet.rs [hunk 6]
```diff
@@ -1392,6 +1392,60 @@ fn test_create_tx_global_xpubs_with_origin() {
...
+    assert!(
+        !wallet.mark_used(KeychainKind::Internal, 0),
+        "creating tx should mark change address used",
+    );
+    assert!(wallet
+        .list_unused_addresses(KeychainKind::Internal)
+        .next()
+        .is_none());
+    assert_eq!(wallet.reveal_next_address(KeychainKind::Internal).index, 1);
+}
```
Comment (oleonardolima) [inline crates/wallet/tests/wallet.rs]: nit: you could also check the `derivation_index` as above.

File: crates/wallet/tests/wallet.rs [hunk 7]
```diff
@@ -1392,6 +1392,60 @@ fn test_create_tx_global_xpubs_with_origin() {
     assert_eq!(psbt.xpub.get(&key), Some(&(fingerprint, path)));
 }
 
+#[test]
+fn test_create_tx_increment_change_index() {
+    use coin_selection::Error;
+    let (desc, change_desc) = get_test_tr_single_sig_xprv_with_change_desc();
```
Comment (oleonardolima) [inline crates/wallet/tests/wallet.rs:1416]: I guess you could have a test that tests for a single descriptor wallet, without the change descriptor. WDYT ?

**Review by oleonardolima — COMMENTED** [review]
utACK 004b0caf30c08b4177a92076fdc448191ce9cf89

It looks good! Thanks for addressing this issue.
I left some suggestions and nit below.

File: crates/wallet/tests/wallet.rs (hunk 7 above)
Comment (ValuedMammal) [reply crates/wallet/tests/wallet.rs:1416]: Let me know if you like the test better in 849e13691031cb811567775c54325ae51e67a901

**Review by oleonardolima — APPROVED** [review]
ACK 849e13691031cb811567775c54325ae51e67a901

File: crates/wallet/tests/wallet.rs (hunk 7 above)
Comment (oleonardolima) [reply crates/wallet/tests/wallet.rs:1416]: It looks good, thanks!

**Comment by ValuedMammal** [comment]
Made last minute [changes](https://github.com/bitcoindevkit/bdk/compare/849e13691031cb811567775c54325ae51e67a901..606fa0874db0f10cd1c64de0f1f097b12db3a16d) @notmandatory

**Review by notmandatory — APPROVED** [review]
ACK 606fa0874db0f10cd1c64de0f1f097b12db3a16d
