### PR TITLE
test for excluded bounds in outputs_in_range

### LINKED ISSUE #58: Test excluded bounds in `SpkTxOutIndex::outputs_in_range`
"For SpkTxOutIndex::outputs_in_range() the excluded bounds aren't tested, you can just change them to whatever and no test would fail."

### PR DESCRIPTION
**Pull request by aagbotemi**
### Description
This PR covers a wide range on tests for excluded bounds and the `SpkTxOutIndex::outputs_in_range`. This PR fixes bitcoindevkit/bdk_wallet#58 

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### New Features:

* [ ] I've added tests for the new feature
* [ ] I've added docs for the new feature

#### Bugfixes:

* [ ] This pull request breaks the existing API
* [ ] I've added tests to reproduce the issue which are now passing
* [x] I'm linking the issue being fixed by this PR

### CODE REVIEW

**Comment by GideonBature** [comment]
tACK #1897 

Tested and working as it should.

File: crates/chain/tests/test_spk_txout_index.rs [hunk 1]
```diff
@@ -122,3 +122,172 @@ fn unmark_used_does_not_result_in_invalid_representation() {
...
+    let outputs_one_to_four_excl: Vec<_> = spk_index.outputs_in_range(1..4).collect();
+    assert_eq!(outputs_one_to_four_excl.len(), 3);
+    assert!(outputs_one_to_four_excl.iter().any(|(i, _)| **i == 1));
+    assert!(outputs_one_to_four_excl
+        .iter()
+        .any(|(i, op)| **i == 3 && *op == tx3_op));
+    assert!(!outputs_one_to_four_excl.iter().any(|(i, _)| **i == 4));
+
+    // Excluded start, Included end
+    let outputs_one_excl_to_four: Vec<_> = spk_index.outputs_in_range(2..=4).collect();
```
Comment (ValuedMammal) [inline crates/chain/tests/test_spk_txout_index.rs]: I would also suggest specifying the range as a tuple of `core::ops::Bound`, as it might better express the intent behind the excluded start.

```rs
let outputs_one_excl_to_four: Vec<_> = spk_index.outputs_in_range((Bound::Excluded(1), Bound::Included(4))).collect();

```

**Review by ValuedMammal — COMMENTED** [review]
ACK

@aagbotemi If you plan to rebase I left a comment that I think would make the test better.

File: crates/chain/tests/test_spk_txout_index.rs (hunk 1 above)
Comment (aagbotemi) [reply crates/chain/tests/test_spk_txout_index.rs]: Great suggestion. I have switched to using `Bound`. Thank you.

**Comment by aagbotemi** [comment]
> @aagbotemi If you plan to rebase I left a comment that I think would make the test better.

@ValuedMammal I have rebased and attended to the comment. Thank you.

**Comment by ValuedMammal** [comment]
ACK 8a86594ef5f33502329ba94ff6dcbbd6d040a9b5 pending a passing CI run.

**Review by ValuedMammal — APPROVED** [review]

**Comment by aagbotemi** [comment]
> ACK [8a86594](https://github.com/bitcoindevkit/bdk/commit/8a86594ef5f33502329ba94ff6dcbbd6d040a9b5) pending a passing CI run.

@ValuedMammal I have rebased with PR #1972, that will fix the CI as discussed

File: crates/chain/tests/test_spk_txout_index.rs [hunk 2]
```diff
@@ -122,3 +123,194 @@ fn unmark_used_does_not_result_in_invalid_representation() {
...
+        .collect();
+    assert_eq!(outputs_to_three.len(), 3,);
+    assert!(outputs_to_three.iter().any(|(i, _)| **i == 3));
+    assert!(outputs_to_three.iter().any(|(i, _)| **i == 5),);
+    assert!(!outputs_to_three.iter().any(|(i, _)| **i == 2),);
+
+    // Excluded start, Unbounded end
+    let outputs_to_three_excl: Vec<_> = spk_index
+        .outputs_in_range((Bound::Included(4u32), Bound::Unbounded::<u32>))
+        .collect();
```
Comment (ValuedMammal) [inline crates/chain/tests/test_spk_txout_index.rs]: You might have meant to do `Bound::Excluded(3)` here.

**Review by ValuedMammal — APPROVED** [review]
ACK d8819c3836f435f19e5a9b475da0c0d540d544b0

File: crates/chain/tests/test_spk_txout_index.rs (hunk 2 above)
Comment (aagbotemi) [reply crates/chain/tests/test_spk_txout_index.rs]: Yes, thank you for pointing it out. Using `Bound::Excluded(3)` provides clarity.

**Review by notmandatory — APPROVED** [review]
ACK c39ba0a65be1e0b91ee7f4406bdfc7f109f67d1c

Just needs a rebase to pick up a CI change and then it looks ready to merge.

**Comment by aagbotemi** [comment]
> Just needs a rebase to pick up a CI change and then it looks ready to merge.

Thank you for the feedback. I have rebased

**Review by oleonardolima — APPROVED** [review]
utACK ad792670c487e62183d901338b2655ec7b81c688

**Comment by ValuedMammal** [comment]
ACK ad792670c487e62183d901338b2655ec7b81c688
