### PR TITLE
Fix/ci update 1.56

### LINKED ISSUE #439: Update CI pipelines to latest Rust stable `1.55.0`
The current stable Rust version is now [`1.55.0`](https://blog.rust-lang.org/2021/09/09/Rust-1.55.0.html). We should update our CI pipelines to this version and fix any resulting issues in the code, most likely due to new clippy checks.

### PR DESCRIPTION
**Pull request by afilini**
### Description

Update our CI to use `1.56`, pin some dependencies to maintain our MSRV.

Closes #439.

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### Bugfixes:

* [x] I'm linking the issue being fixed by this PR

### CODE REVIEW

**Review by rajarshimaitra — COMMENTED** [review]
tACK 

Are those refs changes required for the previous version update changes? Its working ok too without the refs changes.

File: src/blockchain/compact_filters/store.rs [hunk 1]
```diff
@@ -801,7 +801,7 @@ impl CfStore {
             .zip(headers.into_iter())
             .scan(checkpoint, |prev_header, ((_, filter_content), header)| {
                 let filter = BlockFilter::new(&filter_content);
-                if header != filter.filter_header(&prev_header) {
+                if header != filter.filter_header(prev_header) {
```
Comment (rajarshimaitra) [inline src/blockchain/compact_filters/store.rs:804]: Are moving objects instead of passing refs more efficient for these cases for some reason?

Comment (afilini) [reply src/blockchain/compact_filters/store.rs:804]: This was actually a clippy error, I'm not sure why the explicit `&` is not needed, but clearly the compiler can infer that it's a reference.

If you tried running clippy locally maybe you forgot to enable the `compact_filters` feature? This would explain why you didn't get anything

**Review by notmandatory — APPROVED** [review]
ACK d75d221540a0d47b7538b456211f92cdb4d4da8c
