### PR TITLE
fix(wallet): improve safety on finaize psbt

### LINKED ISSUE #1711: Improve safety of finalize_psbt
"In finalize_psbt, the code at lines 1910-1911 assumes a PSBT input corresponds to the inner transaction input. This only holds because it was checked 50 lines before (L1862). It'd be more careful to use get(n).ok_or(...)? to access the input around line 1910 too, in case the check 50 lines earlier was removed or updated. This is the kind of bug that could slip through review as it'd affect code outside the diff, and could realistically cause an issue as a PSBT is often externally provided: it can be reasonably anticipated to be turned into a remote crasher for some applications."

### PR DESCRIPTION
**Pull request by f3r10**
fix #1711 
### Description

This PR replaces how currently potentially bug-prone PSBT's input access is done using a more carefully approach. 

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

### CODE REVIEW

File: crates/wallet/src/wallet/mod.rs [hunk 1]
```diff
@@ -1879,8 +1879,11 @@ impl Wallet {
                         Ok(_) => {
                             // Set the UTXO fields, final script_sig and witness
                             // and clear everything else.
-                            let original = mem::take(&mut psbt.inputs[n]);
-                            let psbt_input = &mut psbt.inputs[n];
```
Comment (rustaceanrob) [inline crates/wallet/src/wallet/mod.rs:1883]: Interesting here that `psbt_input` is assigned to the `n`th value after `take` has already been called. The result should be `psbt_input` is assigned to `Input::default`, which seems like a bug to me in the old code. Curious what you think @ValuedMammal ?

**Comment by rustaceanrob** [comment]
ACK e8a96389bac78961220cbc095c820a551ce4dacf

File: crates/wallet/src/wallet/mod.rs (hunk 1 above)
Comment (ValuedMammal) [reply crates/wallet/src/wallet/mod.rs:1883]: I think it's right before and after.

Comment (evanlinjin) [reply crates/wallet/src/wallet/mod.rs:1883]: @rustaceanrob it's not a bug. `mem::take` replaces the original with a default value (in this case, it'll be an empty `psbt::Input`). In essence, this block of code will clear the `psbt::Input` and fill it in with only things that we need.

**Review by evanlinjin — APPROVED** [review]
ACK e8a96389bac78961220cbc095c820a551ce4dacf
