### PR TITLE
fix: no `Debug` on `Display` implementations

### LINKED ISSUE #1933: Display implementations should not expose `Debug` output
Currently, the `Display` implementation for `LoadError` displays`Debug` output for `LoadError::MissingDescriptor` and `LoadError::Mismatch`:

```rust
impl fmt::Display for LoadError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            LoadError::Descriptor(e) => e.fmt(f),
            LoadError::MissingNetwork => write!(f, "loaded data is missing network type"),
            LoadError::MissingGenesis => write!(f, "loaded data is missing genesis hash"),
            LoadError::MissingDescriptor(k) => {
                write!(f, "loaded data is missing descriptor for keychain {k:?}")
            }
            LoadError::Mismatch(mismatch) => write!(f, "data mismatch: {mismatch:?}"),
        }
    }
}
```

I think this is generally not a good practice. `Debug` output is automatically generated, and is not as nice to read as a hand-written `Display` implementation's output.

I noticed this in a test we were loading a wallet with the incorrect network, and instead of getting a nice error message, we got `data mismatch: Network { loaded: Network::Testnet, expected: Network::Bitcoin }`. Our project never exposes `Debug` output to the user, and we'd like to avoid doing this if we use BDK, but still be able to expose BDK errors to the user via `Display`.

### PR DESCRIPTION
**Pull request by Dmenec**
### Description

Fixes https://github.com/bitcoindevkit/bdk/issues/1933, remove the usage of `Debug` on `Display` implemetations mentioned in https://github.com/bitcoindevkit/bdk/pull/1881#issuecomment-2718412512

### Changelog notice

- Replaced  `Debug` usage with `Display` messages for `InsertDescriptorError`, `CalculateFeeError` and `StoreError`.
- `InvalidMagicBytes` now displays expected and actual bytes in hexadecimal instead of using `Debug`.
- Added a new `short_descriptor` function to shorten descriptors for concise error output.
- Added detailed `SyncRequest` `Display` for Esplora and Electrum examples.

#### All Submissions:
* [x] I have signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `just check`, `just fmt` and `just test` before committing

### CODE REVIEW

**Comment by qatkk** [comment]
Concept ACK — this approach looks good, thanks for the changes. I ran the tests locally and they all passed.

While trying to recreate the initial issue’s scenario (https://github.com/bitcoindevkit/bdk/issues/1933), I found that `bdk_wallet` `master` still references the older API names (`list_canonical_txs`, `filter_chain_unspents`, `filter_chain_txouts`, `from_genesis_hash`), whereas this PR’s `bdk_chain` exposes the newer canonicalization API (`canonical_iter`) and `LocalChain::from_genesis`. As a result, building `bdk_wallet` against this PR failed. Is there any branch in `bdk_wallet` that already adopts the new APIs, so I can test against them?

I have a few small suggestions below. Most of these are nits, but since this PR is already addressing the area, I thought it’d be reasonable to mention them here:

- It might be nice to add a CI to prevent using `Debug` for `Display` in future changes.

- In the `short_descriptor` function, it could be useful to show the last 8 characters of the descriptor so the full checksum is visible.

- A small note on `InvalidMagicBytes`: it might be helpful to also show any difference between the length of expected and received byte.

File: crates/chain/src/indexer/keychain_txout.rs [hunk 1]
```diff
@@ -973,33 +973,47 @@ pub enum InsertDescriptorError<K> {
...
             InsertDescriptorError::DescriptorAlreadyAssigned {
-                existing_assignment: existing,
+                existing_assignment,
                 descriptor,
             } => {
+                let short_desc = short_descriptor(descriptor, 4);
                 write!(
                     f,
-                    "attempt to re-assign descriptor {descriptor:?} already assigned to {existing:?}"
+                    "Descriptor '{}' is already in use by keychain '{}'. Please use a different descriptor.",
```
Comment (evanlinjin) [inline crates/chain/src/indexer/keychain_txout.rs]: Nit

```suggestion
                    "descriptor '{}' is already in use by another keychain '{}'",
```

File: crates/chain/src/indexer/keychain_txout.rs [hunk 2]
```diff
@@ -973,33 +973,47 @@ pub enum InsertDescriptorError<K> {
...
             InsertDescriptorError::KeychainAlreadyAssigned {
-                existing_assignment: existing,
+                existing_assignment,
                 keychain,
             } => {
+                let short_desc = short_descriptor(existing_assignment, 4);
                 write!(
                     f,
-                    "attempt to re-assign keychain {keychain:?} already assigned to {existing:?}"
+                    "Keychain '{}' is already associated with descriptor '{}'. Please choose a different keychain.",
```
Comment (evanlinjin) [inline crates/chain/src/indexer/keychain_txout.rs]: Nit

```suggestion
                    "keychain '{}' is already associated with another descriptor '{}'",
```

File: crates/chain/src/indexer/keychain_txout.rs [hunk 3]
```diff
@@ -973,33 +973,47 @@ pub enum InsertDescriptorError<K> {
...
+                    keychain, short_desc
                 )
             }
         }
     }
 }
 
 #[cfg(feature = "std")]
-impl<K: core::fmt::Debug> std::error::Error for InsertDescriptorError<K> {}
+impl<K: core::fmt::Display + core::fmt::Debug> std::error::Error for InsertDescriptorError<K> {}
```
Comment (evanlinjin) [inline crates/chain/src/indexer/keychain_txout.rs:1004]: Technically this is a breaking change, so it should be reflected in the commit message (`!`).

**Review by evanlinjin — CHANGES_REQUESTED** [review]
Quality work.

Just a couple requested changes:

* Commit messages should contain a scope (as mentioned in the conventional commits spec). The scope should be the name of the package affected: `core`, `chain`, `example`, etc.
* Commits that break the API should be marked with `!`.

And a nit:

* Error messages should be somewhat consistent. I personally don't think we should suggest actions in the message, just state what the error is.

**Comment by evanlinjin** [comment]
@Dmenec are you able to make progress on this?

**Comment by Dmenec** [comment]
@evanlinjin Pushed the updates. Let me know if everything checks out :)

File: crates/chain/src/indexer/keychain_txout.rs [hunk 4]
```diff
@@ -973,33 +973,47 @@ pub enum InsertDescriptorError<K> {
     },
 }
 
-impl<K: core::fmt::Debug> core::fmt::Display for InsertDescriptorError<K> {
+/// Returns a shortened string representation of a descriptor.
+/// Shows the first and last `edge_len` characters, separated by `...`.
+fn short_descriptor(desc: &Descriptor<DescriptorPublicKey>, edge_len: usize) -> String {
+    let s = ToString::to_string(desc);
+    if s.len() <= edge_len * 2 {
```
Comment (evanlinjin) [inline crates/chain/src/indexer/keychain_txout.rs]: Nit: `edge_len * 2 + 3`.

No point returning the shortened version if it's longer than the original (due to `...`).

Have a code comment for the rationale of `+3`.

**Review by evanlinjin — APPROVED** [review]
utACK 532e2ecf039f7f3ab1b17e76620137cb955c2704

I'm happy with how this is looking. Unable to test until I have access to a computer again.

**Comment by Dmenec** [comment]
Having some trouble with the no_std CI check for the esplora crate... Does it actually support no_std, or should be treated as std‑only?

**Comment by oleonardolima** [comment]
> Having some trouble with the no_std CI check for the esplora crate... Does it actually support no_std, or should be treated as std‑only?

@Dmenec It's now fixed on master, a rebase should fix it.

File: crates/chain/src/tx_graph.rs [hunk 5]
```diff
@@ -256,10 +256,28 @@ pub enum CalculateFeeError {
...
+                    write!(f, ": ")?;
+                    for (i, op) in shown.enumerate() {
+                        if i > 0 {
+                            write!(f, ", ")?;
+                        }
+                        write!(f, "{}", op)?;
+                    }
+                    if remaining > 0 {
+                        write!(f, " (+{} more)", remaining)?;
+                    }
```
Comment (nymius) [inline crates/chain/src/tx_graph.rs:274]: Nit:

```diff
diff --git a/crates/chain/src/tx_graph.rs b/crates/chain/src/tx_graph.rs
index 457a478a..d170eccf 100644
--- a/crates/chain/src/tx_graph.rs
+++ b/crates/chain/src/tx_graph.rs
@@ -258,19 +258,16 @@ impl fmt::Display for CalculateFeeError {
         match self {
             CalculateFeeError::MissingTxOut(outpoints) => {
                 let max_show = 3;
-                let shown = outpoints.iter().take(max_show);
+                let shown: Vec<_> = outpoints.iter().take(max_show).collect();
                 let remaining = outpoints.len().saturating_sub(max_show);
 
                 write!(f, "missing `TxOut` for input(s)")?;
                 if outpoints.is_empty() {
                     write!(f, ": <none>")
                 } else {
-                    write!(f, ": ")?;
-                    for (i, op) in shown.enumerate() {
-                        if i > 0 {
-                            write!(f, ", ")?;
-                        }
-                        write!(f, "{}", op)?;
+                    write!(f, ": {}", shown[0])?;
+                    for op in &shown[1..] {
+                        write!(f, ", {}", op)?;
                     }
                     if remaining > 0 {
                         write!(f, " (+{} more)", remaining)?;
```

File: crates/file_store/src/lib.rs [hunk 6]
```diff
@@ -26,11 +26,18 @@ pub enum StoreError {
...
     fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
         match self {
-            Self::Io(e) => write!(f, "io error trying to read file: {e}"),
-            Self::InvalidMagicBytes { got, expected } => write!(
-                f,
-                "file has invalid magic bytes: expected={expected:?} got={got:?}",
-            ),
+            Self::Io(e) => write!(f, "io error trying to read file: {}", e),
+            Self::InvalidMagicBytes { got, expected } => {
+                write!(f, "file has invalid magic bytes: expected=0x")?;
```
Comment (nymius) [inline crates/file_store/src/lib.rs]:
```bash
Error: could not open file store

Caused by:
    file has invalid magic bytes: expected=0x62646b5f6578616d706c655f656c65637472756d got=0x62646b5f6578616d706c5f656c65637472756d01
```
Given the format of the error output I would use `invalid magic bytes` without the `file has`.

This is a good opportunity to rewrite the others in the same spirit.

Also, stacking `expected` and `got` improves the feedback to the reader:
```bash
Error: could not open file store

Caused by:
    invalid magic bytes
expected: 0x62646b5f6578616d706c655f656c65637472756d
got:      0x62646b5f6578616d706c5f656c65637472756d01
```

File: examples/example_esplora/src/main.rs [hunk 7]
```diff
@@ -215,8 +215,20 @@ fn main() -> anyhow::Result<()> {
                     .chain_tip(local_tip.clone())
                     .inspect(|item, progress| {
                         let pc = (100 * progress.consumed()) as f32 / progress.total() as f32;
-                        eprintln!("[ SCANNING {pc:03.0}% ] {item}");
-                        // Flush early to ensure we print at every iteration.
+                        match item {
+                            bdk_chain::spk_client::SyncItem::Spk((keychain, index), spk) => {
+                                eprintln!(
+                                    "[ SCANNING {pc:03.0}% ] script {} {} {}",
```
Comment (nymius) [inline examples/example_esplora/src/main.rs]: nit: `"[ SCANNING {pc:3.0}% ] script {} {} {}"`, instead of `"[ SCANNING {pc:03.0}% ] script {} {} {}",`

I prefer
```
[ SCANNING   6% ] outpoint 623cf110e23b15074e807a551a751856eb0a95f23a4a60f125d943d1d6e7cb6a:0
```
to
```
[ SCANNING 006% ] outpoint 623cf110e23b15074e807a551a751856eb0a95f23a4a60f125d943d1d6e7cb6a:0
```

File: crates/chain/src/indexer/keychain_txout.rs [hunk 8]
```diff
@@ -973,33 +973,50 @@ pub enum InsertDescriptorError<K> {
     },
 }
 
-impl<K: core::fmt::Debug> core::fmt::Display for InsertDescriptorError<K> {
+/// Returns a shortened string representation of a descriptor.
+/// Shows the first and last `edge_len` characters, separated by `...`.
+fn short_descriptor(desc: &Descriptor<DescriptorPublicKey>, edge_len: usize) -> String {
```
Comment (nymius) [inline crates/chain/src/indexer/keychain_txout.rs]: I've tried this with the following `bin`:
```rust
use bdk_chain::bitcoin::key::Secp256k1;
use bdk_chain::indexer::keychain_txout::KeychainTxOutIndex;
use bdk_chain::miniscript::Descriptor;

const DESC: &str = "...";

fn main() {
    let lookahead = 10;
    let use_cache = true;
    let mut index = KeychainTxOutIndex::new(lookahead, use_cache);
    let secp = Secp256k1::new();
    let (desc, _) = Descriptor::parse_descriptor(&secp, DESC).unwrap();
    index.insert_descriptor("some", desc.clone()).unwrap();
    if let Err(e) = index.insert_descriptor("other", desc) {
        eprintln!("{}", e);
    }
}
```

I think the output is not very clear:

```bash
descriptor 'tr([...d45f9rlk' is already in use by another keychain 'some'.
```

I would keep only a fixed size prefix in the output, including the descriptor type and trying to capture the origin keypath if possible.
@qatkk proposed to increase the suffix to capture the checksum, but without any clear accessors to those components it is a "best guess" effort.
Maybe we should propose the implementation of them at the `miniscript` level, and add methods to get strings from `DescriptorType` for example.

File: crates/chain/src/tx_graph.rs (hunk 5 above)
Comment (Dmenec) [reply crates/chain/src/tx_graph.rs:274]: Maybe shortening the displayed txid could be an option as well? e.g. abcd1234…ef901234

File: crates/file_store/src/lib.rs (hunk 6 above)
Comment (Dmenec) [reply crates/file_store/src/lib.rs]: Sure! I'll update the ones that are in scope for this PR and push the proposed changes shortly.

File: crates/chain/src/indexer/keychain_txout.rs (hunk 8 above)
Comment (Dmenec) [reply crates/chain/src/indexer/keychain_txout.rs]: cACK — I’ll open a follow‑up PR with the proposal and then apply it here. Thanks for the suggestion!

File: crates/chain/src/tx_graph.rs (hunk 5 above)
Comment (evanlinjin) [reply crates/chain/src/tx_graph.rs:274]: Nack on shortening txid 😅 personally I prefer seeing the whole thing

File: crates/chain/src/indexer/keychain_txout.rs (hunk 8 above)
Comment (evanlinjin) [reply crates/chain/src/indexer/keychain_txout.rs]: @nymius that is a good point. For practicality, can we remove the `short_descriptor` concept in this PR and just print the full descriptor for now?

Let's add it back once it is more readable (including the descriptor type, key path, checksum, etc.)

Comment (nymius) [reply crates/chain/src/indexer/keychain_txout.rs]: I agree, let's use full descriptors for now.

File: crates/chain/src/tx_graph.rs [hunk 9]
```diff
@@ -256,15 +256,29 @@ pub enum CalculateFeeError {
...
+                let remaining = outpoints.len().saturating_sub(max_show);
+
+                writeln!(f, "   missing `TxOut` for input(s)")?;
+                if outpoints.is_empty() {
+                    write!(f, "<none>")
+                } else {
+                    writeln!(f, "{}", shown[0])?;
+                    for op in &shown[1..] {
+                        writeln!(f, "{}", op)?;
+                    }
```
Comment (nymius) [inline crates/chain/src/tx_graph.rs]: I haven't executed this yet, but my guess is it will print the outpoint vertically, as you are using `writeln!` instead of `write!`.

File: crates/chain/src/tx_graph.rs (hunk 5 above)
Comment (Dmenec) [reply crates/chain/src/tx_graph.rs:274]: Resolved in 737cff8db54031db379c583f8869b61170b268ec

File: examples/example_esplora/src/main.rs (hunk 7 above)
Comment (Dmenec) [reply examples/example_esplora/src/main.rs]: Resolved in e46b1c9640ec8ebbb0200e16084c3e31d1824fb0

File: crates/file_store/src/lib.rs [hunk 10]
```diff
@@ -25,13 +25,26 @@ pub enum StoreError {
...
-            ),
-            Self::Bincode(e) => write!(f, "bincode error while reading entry {e}"),
+            Self::Io(e) => write!(f, "io error while reading store file: {e}"),
+            Self::Bincode(e) => write!(f, "bincode error while decoding entry {e}"),
+            Self::InvalidMagicBytes { got, expected } => {
+                writeln!(f, "invalid magic bytes")?;
+                write!(f, "  expected: 0x")?;
+                fmt_hex_bytes(f, expected)?;
+                writeln!(f)?;                
+                write!(f, "  got:      0x")?;
```
Comment (nymius) [inline crates/file_store/src/lib.rs]: Maybe the best for this is to reserve the same number of spaces for the word in the `fmt` placeholder, i.e., `writeln!("{:10}", "expected:")`. Seems a bit clunky, but is much more future proof than guessing the number of spaces. I have tried it with the following code:
```rust
fn main() {
    let hex = "0x913414332";
    let other_hex = "0x3941247913414332";
    println!("{:10}{hex}", "expected:");
    println!("{:10}{other_hex}", "got:");
}
```

File: examples/example_electrum/src/main.rs [hunk 11]
```diff
@@ -210,9 +210,22 @@ fn main() -> anyhow::Result<()> {
...
+                                eprintln!(
+                                    "[ SCANNING {pc:03.0}% ] script {} {} {}",
+                                    keychain, index, spk
+                                );
+                            }
+                            bdk_chain::spk_client::SyncItem::Txid(txid) => {
+                                eprintln!("[ SCANNING {pc:03.0}% ] txid {}", txid);
+                            }
+                            bdk_chain::spk_client::SyncItem::OutPoint(op) => {
+                                eprintln!("[ SCANNING {pc:03.0}% ] outpoint {}", op);
```
Comment (nymius) [inline examples/example_electrum/src/main.rs]: I would apply the same criteria for `esplora` here.

File: crates/chain/src/tx_graph.rs (hunk 9 above)
Comment (Dmenec) [reply crates/chain/src/tx_graph.rs]: Yes, thought maybe it would be a bit more readable:

```
   missing `TxOut` for input(s)
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa:0
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb:1
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc:2
```

File: crates/file_store/src/lib.rs (hunk 6 above)
Comment (Dmenec) [reply crates/file_store/src/lib.rs]: Resolved in ae17df23280728923c6f062aa8fda3aa462766eb

File: examples/example_electrum/src/main.rs (hunk 11 above)
Comment (Dmenec) [reply examples/example_electrum/src/main.rs]: Resolved in adb5b9954267de623c111cbd103523d7e6b07487

File: crates/chain/src/tx_graph.rs (hunk 9 above)
Comment (evanlinjin) [reply crates/chain/src/tx_graph.rs]: I'd suggest keeping `Display` single-line to follow Rust conventions. Callers typically don't expect `{}` to emit multiple lines, and it composes better with logging/error chains.

If we really want a pretty-printed multi-line version later, we can use the alternate flag (`{:#}`) for that. I don't think it's necessary for this PR (but feel free to include it).

```rust
fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
       if f.alternate() {
           // multi-line version
           todo!()
       } else {
           // single-line version
           todo!()
       }
   }
```

File: crates/chain/src/indexer/keychain_txout.rs [hunk 12]
```diff
@@ -973,33 +973,35 @@ pub enum InsertDescriptorError<K> {
...
             }
             InsertDescriptorError::KeychainAlreadyAssigned {
-                existing_assignment: existing,
+                existing_assignment,
                 keychain,
             } => {
                 write!(
                     f,
-                    "attempt to re-assign keychain {keychain:?} already assigned to {existing:?}"
+                    "keychain '{}' is already associated with another descriptor '{}'.",
```
Comment (evanlinjin) [inline crates/chain/src/indexer/keychain_txout.rs]: As per [Rust API Guidelines](https://rust-lang.github.io/api-guidelines/interoperability.html#error-types-are-meaningful-and-well-behaved-c-good-err):

> The error message given by the Display representation of an error type should be lowercase without trailing punctuation, and typically concise.

Please remove the trailing punctuation thanks!

File: crates/file_store/src/lib.rs [hunk 13]
```diff
@@ -25,13 +25,26 @@ pub enum StoreError {
...
-            Self::Io(e) => write!(f, "io error trying to read file: {e}"),
-            Self::InvalidMagicBytes { got, expected } => write!(
-                f,
-                "file has invalid magic bytes: expected={expected:?} got={got:?}",
-            ),
-            Self::Bincode(e) => write!(f, "bincode error while reading entry {e}"),
+            Self::Io(e) => write!(f, "io error while reading store file: {e}"),
+            Self::Bincode(e) => write!(f, "bincode error while decoding entry {e}"),
+            Self::InvalidMagicBytes { got, expected } => {
+                writeln!(f, "invalid magic bytes")?;
```
Comment (evanlinjin) [inline crates/file_store/src/lib.rs]: Also here, please make this single line thanks!

**Review by evanlinjin — CHANGES_REQUESTED** [review]
Sorry for the bike-shedding. We're very close.

File: crates/file_store/src/lib.rs (hunk 13 above)
Comment (Dmenec) [reply crates/file_store/src/lib.rs]: Just to clarify the final intended format:

`invalid magic bytes: expected 0x01020304, got 0x10203040`

and the one mentioned in https://github.com/bitcoindevkit/bdk/pull/2083#discussion_r2734811270

```
missing `TxOut` for input(s): aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa:0, ...
```

Does this look okay? Thank you!

File: crates/file_store/src/lib.rs (hunk 10 above)
Comment (Dmenec) [reply crates/file_store/src/lib.rs]: Discussing **[here](https://github.com/bitcoindevkit/bdk/pull/2083#discussion_r2734829962)**

File: crates/file_store/src/lib.rs (hunk 6 above)
Comment (evanlinjin) [reply crates/file_store/src/lib.rs]: > ```shell
> Error: could not open file store
> 
> Caused by:
>     file has invalid magic bytes: expected=0x62646b5f6578616d706c655f656c65637472756d got=0x62646b5f6578616d706c5f656c65637472756d01
> ```
> 
> Given the format of the error output I would use `invalid magic bytes` without the `file has`.
> 
> This is a good opportunity to rewrite the others in the same spirit.
> 
> Also, stacking `expected` and `got` improves the feedback to the reader:
> 
> ```shell
> Error: could not open file store
> 
> Caused by:
>     invalid magic bytes
> expected: 0x62646b5f6578616d706c655f656c65637472756d
> got:      0x62646b5f6578616d706c5f656c65637472756d01
> ```

Sorry for the back-and-forth, but my [comment](https://github.com/bitcoindevkit/bdk/pull/2083#discussion_r2734811270) invalidates this. Error messages should be single line as per convention! Can use the `#` for "pretty print".

File: crates/file_store/src/lib.rs (hunk 13 above)
Comment (evanlinjin) [reply crates/file_store/src/lib.rs]: @Dmenec looks good thanks.

**Nit:** Message for the second one can be simplified to `cannot calculate fee, missing output(s):`. 😅 Messages for `CalculateFeeError` should mention that it's a calculate fee error?

Comment (Dmenec) [reply crates/file_store/src/lib.rs]: > **Nit:** Message for the second one can be simplified to `cannot calculate fee, missing output(s):`. 😅 Messages for `CalculateFeeError` should mention that it's a calculate fee error?

What do you think about `cannot calculate fee, missing previous output(s)`? Since we're referring to the outpoints of the inputs, I think it's clearer. Also agree on mentioning that it's a calculate fee error :)

File: crates/chain/src/tx_graph.rs (hunk 9 above)
Comment (oleonardolima) [reply crates/chain/src/tx_graph.rs]: I don't think we need the multi-line now, can add in the future if needed. Also, what's the rationale for the leading whitespace ?

**Review by oleonardolima — COMMENTED** [review]
Overall it looks good, it just need to address Evan's comments.

File: crates/file_store/src/lib.rs (hunk 6 above)
Comment (Dmenec) [reply crates/file_store/src/lib.rs]: Resolved in 744a3de1bc2f9fc77203e1e89a5e95de5034948a

File: crates/chain/src/indexer/keychain_txout.rs (hunk 8 above)
Comment (Dmenec) [reply crates/chain/src/indexer/keychain_txout.rs]: Resolved in 5d715c2e4c8076be058e342efe279a3fc3481312

File: crates/chain/src/tx_graph.rs (hunk 9 above)
Comment (Dmenec) [reply crates/chain/src/tx_graph.rs]: > I don't think we need the multi-line now, can add in the future if needed. Also, what's the rationale for the leading whitespace ?

Was a minor style thing, wasn't really sure about it, already removed it :)

Comment (Dmenec) [reply crates/chain/src/tx_graph.rs]: Resolved in ad96bd9244fd58d34b3bb901285751e2c92a9edd

File: crates/chain/src/indexer/keychain_txout.rs (hunk 12 above)
Comment (Dmenec) [reply crates/chain/src/indexer/keychain_txout.rs]: Resolved in 5d715c2e4c8076be058e342efe279a3fc3481312

File: crates/file_store/src/lib.rs (hunk 13 above)
Comment (Dmenec) [reply crates/file_store/src/lib.rs]: > Also here, please make this single line thanks!

Resolved in 823e4e980af03672cc6342d0e4850febcbd14c9d

> > **Nit:** Message for the second one can be simplified to `cannot calculate fee, missing output(s):`. 😅 Messages for `CalculateFeeError` should mention that it's a calculate fee error?
> 
> What do you think about `cannot calculate fee, missing previous output(s)`? Since we're referring to the outpoints of the inputs, I think it's clearer. Also agree on mentioning that it's a calculate fee error :)

Resolved in 5a85f6e25a9e14204cb66fec3f7381a59133f0be

File: crates/chain/src/tx_graph.rs [hunk 14]
```diff
@@ -256,15 +256,33 @@ pub enum CalculateFeeError {
...
-                f,
-                "missing `TxOut` for one or more of the inputs of the tx: {outpoints:?}",
-            ),
-            CalculateFeeError::NegativeFee(fee) => write!(
-                f,
-                "transaction is invalid according to the graph and has negative fee: {}",
-                fee.display_dynamic()
-            ),
+            CalculateFeeError::MissingTxOut(outpoints) => {
+                let max_show = 3;
```
Comment (evanlinjin) [inline crates/chain/src/tx_graph.rs:260]: If I were to nit-pick, I would say get rid of this and just show all prev outputs.

**Review by evanlinjin — APPROVED** [review]
ACK 823e4e980af03672cc6342d0e4850febcbd14c9d

I'm going to merge this as is. My nit-pick can be addressed in follow ups.

File: crates/chain/src/tx_graph.rs [hunk 15]
```diff
@@ -256,15 +256,33 @@ pub enum CalculateFeeError {
...
+                let shown: Vec<_> = outpoints.iter().take(max_show).collect();
+                let remaining = outpoints.len().saturating_sub(max_show);
+
+                write!(f, "cannot calculate fee, missing previous output(s): ")?;
+                if outpoints.is_empty() {
+                    write!(f, "<none>")
```
Comment (evanlinjin) [inline crates/chain/src/tx_graph.rs:266]: If this ever happens, it's a bug in the library - let's `debug_assert!` it?
