### PR TITLE
test(electrum): Test sync in reorg and no-reorg situations

### LINKED ISSUE #1125: Calling `example_electrum sync` on an unconfirmed tx may result in the tx being stuck as unconfirmed eternally (according to the cli))
**Describe the bug**  
Calling `example_electrum sync` on an unconfirmed tx may result in the tx being stuck as unconfirmed eternally (according to the cli)).

**To Reproduce**  
1. Send a transaction: `example_electrum send 123456 <insert-address-here>`.
2. Perform `example_electrum sync` until the transaction is confirmed (according to the block explorer).
3. Do `example_electrum balance` -> You'll see that the transaction is not confirmed (according to our cli).
4. Do `example_electrum scan && example_electrum balance` -> The transaction is still NOT confirmed!

The transaction is forever stuck as unconfirmed according to our cli.

**Expected behavior**  

That the tx is viewed as confirmed by our cli.

### PR DESCRIPTION
**Pull request by LagginTimes**
Closes #1125.

### Description

Add new test for `bdk_electrum` to make sure previously unconfirmed transactions get confirmed again in both reorg and no-reorg situations.

### Changelog notice

* Added `wait_until_electrum_sees_txid` method to `TestEnv`.
* `wait_until_electrum_sees_block` now has a `Duration` input for timeout.
* Removed exponential polling delay in `wait_until_electrum_sees_block`.
* Added `test_sync` to `bdk_electrum` to make sure previously unconfirmed transactions get confirmed in both reorg and no-org situations.

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

### CODE REVIEW

File: crates/electrum/tests/test_electrum.rs [hunk 1]
```diff
@@ -22,10 +23,34 @@ fn get_balance(
     Ok(balance)
 }
 
+fn electrum_sync<I>(
```
Comment (evanlinjin) [inline crates/electrum/tests/test_electrum.rs]: **Nit:** according to [standard naming conventions in Rust](https://rust-lang.github.io/api-guidelines/naming.html#names-use-a-consistent-word-order-c-word-order), let's start with the verb for this function (since this is how we name things in BDK, let me know if you find an exception though). I.e. `sync_with_electrum`.

File: crates/electrum/tests/test_electrum.rs [hunk 2]
```diff
@@ -22,10 +23,34 @@ fn get_balance(
...
+    let _ = graph.apply_update(update.graph_update.clone());
+
+    Ok(update)
+}
+
 #[test]
 pub fn test_update_tx_graph_without_keychain() -> anyhow::Result<()> {
     let env = TestEnv::new()?;
-    let electrum_client = electrum_client::Client::new(env.electrsd.electrum_url.as_str())?;
+    let electrum_client = Client::new(env.electrsd.electrum_url.as_str())?;
```
Comment (evanlinjin) [inline crates/electrum/tests/test_electrum.rs]: **Nit:** Ideally, we don't change lines of code that we don't need to touch. Same as line `151`. In this file, could we use the full module path to refer to `Client`?

However, if you see a problem with using the full path, I think it makes sense to include this change in a separate commit.

File: crates/electrum/tests/test_electrum.rs [hunk 3]
```diff
@@ -238,18 +263,13 @@ pub fn test_update_tx_graph_stop_gap() -> anyhow::Result<()> {
     Ok(())
 }
 
-/// Ensure that [`ElectrumExt`] can sync properly.
-///
-/// 1. Mine 101 blocks.
-/// 2. Send a tx.
-/// 3. Mine extra block to confirm sent tx.
-/// 4. Check [`Balance`] to ensure tx is confirmed.
+/// Ensure that [`BdkElectrumClient`] can sync properly in both reorg and no-reorg situations.
```
Comment (evanlinjin) [inline crates/electrum/tests/test_electrum.rs]: This doc comment is a little ambiguous. We may need to expand on "sync properly" here and describe the scenario in more detail. I think you did a better job describing the test in the PR description than in this doc comment.

File: crates/electrum/tests/test_electrum.rs [hunk 4]
```diff
@@ -22,10 +23,34 @@ fn get_balance(
     Ok(balance)
 }
 
+fn electrum_sync<I>(
+    client: &BdkElectrumClient<Client>,
+    spks: &[ScriptBuf],
```
Comment (evanlinjin) [inline crates/electrum/tests/test_electrum.rs]: **Nit:** there is no point having a reference here, since we are cloning this later on (with `.to_owned()`).

File: crates/electrum/tests/test_electrum.rs [hunk 5]
```diff
@@ -22,10 +23,34 @@ fn get_balance(
...
+    batch_size: usize,
+    chain: &mut LocalChain,
+    graph: &mut IndexedTxGraph<ConfirmationBlockTime, I>,
+) -> anyhow::Result<SyncResult>
+where
+    I: Indexer,
+    I::ChangeSet: Default + Merge,
```
Comment (evanlinjin) [inline crates/electrum/tests/test_electrum.rs]: **Nit:** This removes the unnecessary reference and allows more flexibility for what we can input in `spks`.

```suggestion
fn electrum_sync<I, Spks>(
    client: &BdkElectrumClient<Client>,
    spks: Spks,
    batch_size: usize,
    chain: &mut LocalChain,
    graph: &mut IndexedTxGraph<ConfirmationBlockTime, I>,
) -> anyhow::Result<SyncResult>
where
    I: Indexer,
    I::ChangeSet: Default + Merge,
    Spks: IntoIterator<Item = ScriptBuf>,
    Spks::IntoIter: ExactSizeIterator + Send + 'static,

```

File: crates/electrum/tests/test_electrum.rs [hunk 6]
```diff
@@ -22,10 +23,34 @@ fn get_balance(
     Ok(balance)
 }
 
+fn electrum_sync<I>(
+    client: &BdkElectrumClient<Client>,
+    spks: &[ScriptBuf],
+    batch_size: usize,
```
Comment (evanlinjin) [inline crates/electrum/tests/test_electrum.rs]: I think it's okay to hard-code the batch size and have it as a constant at the top of the file (instead of having it as an input to this function). The value is not relevant for what we are testing and not having it slightly increases readability for the tests.

File: crates/electrum/tests/test_electrum.rs [hunk 7]
```diff
@@ -272,32 +292,91 @@ fn scan_detects_confirmed_tx() -> anyhow::Result<()> {
     // Mine some blocks.
     env.mine_blocks(101, Some(addr_to_mine))?;
 
-    // Create transaction that is tracked by our receiver.
+    // Broadcast transaction to mempool.
     env.send(&addr_to_track, SEND_AMOUNT)?;
+    env.wait_until_electrum_sees_block()?;
```
Comment (evanlinjin) [inline crates/electrum/tests/test_electrum.rs]: We are sending tx to mempool, but we are waiting to see a block? Is there a method that waits for electrum to see a certain tx in mempool? If not, we should add it.

File: crates/electrum/tests/test_electrum.rs [hunk 8]
```diff
@@ -272,32 +292,91 @@ fn scan_detects_confirmed_tx() -> anyhow::Result<()> {
...
+
+    // Check if balance is zero when transaction exists only in mempool.
+    assert_eq!(
+        get_balance(&recv_chain, &recv_graph)?,
+        Balance {
+            confirmed: Amount::from_sat(0),
+            ..Balance::default()
+        },
+        "initial balance must be correct",
+    );
```
Comment (evanlinjin) [inline crates/electrum/tests/test_electrum.rs]: Since we have a tx in mempool, shouldn't we have an unconfirmed balance?

If the intention is to sync BEFORE seeing the tx in mempool, it should be made more obvious in code.

File: crates/electrum/tests/test_electrum.rs [hunk 9]
```diff
@@ -272,32 +292,91 @@ fn scan_detects_confirmed_tx() -> anyhow::Result<()> {
...
-        .map_err(|err| anyhow::anyhow!("LocalChain update error: {:?}", err))?;
-    let _ = recv_graph.apply_update(update.graph_update);
+    // Check if balance is correct when transaction returns to mempool.
+    assert_eq!(
+        get_balance(&recv_chain, &recv_graph)?,
+        Balance {
+            confirmed: Amount::from_sat(0),
+            ..Balance::default()
+        },
+    );
```
Comment (evanlinjin) [inline crates/electrum/tests/test_electrum.rs]: This result is assuming that the receiving structures have not seen the tx in mempool yet.

If the receiving structures are aware of the tx being in mempool, there should be an unconfirmed balance here.

File: crates/electrum/tests/test_electrum.rs [hunk 10]
```diff
@@ -272,32 +292,91 @@ fn scan_detects_confirmed_tx() -> anyhow::Result<()> {
...
     assert_eq!(
         get_balance(&recv_chain, &recv_graph)?,
         Balance {
             confirmed: SEND_AMOUNT,
             ..Balance::default()
         },
+        "initial balance must be correct",
     );
 
     for tx in recv_graph.graph().full_txs() {
```
Comment (evanlinjin) [inline crates/electrum/tests/test_electrum.rs:390]: We need a comment before the for loop to explain what is being tested in the for loop.

**Review by evanlinjin — CHANGES_REQUESTED** [review]
Good work with this. Moving forward, I recommend improving the docs and adding more clarity to the testing logic. I also included a bunch of nits for you to consider including.

File: crates/electrum/tests/test_electrum.rs (hunk 1 above)
Comment (evanlinjin) [reply crates/electrum/tests/test_electrum.rs]: @LagginTimes I think you attempted to change this, but you ended up changing the wrong thing 😅

Comment (LagginTimes) [reply crates/electrum/tests/test_electrum.rs]: Oops.

**Comment by evanlinjin** [comment]
The commit also adds a method to the `TestEnv` (which is not documented). Please either have this change as a separate commit, or mention the change in the commit.

File: crates/testenv/src/lib.rs [hunk 11]
```diff
@@ -186,6 +186,22 @@ impl TestEnv {
         }
     }
 
+    /// This method waits for Electrum to see a transaction with given `txid`.
```
Comment (evanlinjin) [inline crates/testenv/src/lib.rs]:
```suggestion
    /// This method waits for Electrsd to see a transaction with given `txid`.
```

File: crates/testenv/src/lib.rs [hunk 12]
```diff
@@ -186,6 +186,22 @@ impl TestEnv {
...
+    pub fn wait_until_electrum_sees_txid(&self, txid: Txid) -> anyhow::Result<()> {
+        let mut delay = Duration::from_millis(64);
+
+        loop {
+            if self.electrsd.client.transaction_get(&txid).is_ok() {
+                return Ok(());
+            }
```
Comment (evanlinjin) [inline crates/testenv/src/lib.rs]: This will create a situation where we may loop forever.

Are we able to figure out if the error is a not-exist error? Ideally, the `rust_esplora` crate has something to figure this out easily. If not, we should upstream some changes later.

Also, would be good to add a timeout as an input. Just in case the test fails (the txid never shows up). We at least want to exit the test!

**Review by evanlinjin — CHANGES_REQUESTED** [review]

File: crates/testenv/src/lib.rs (hunk 12 above)
Comment (evanlinjin) [reply crates/testenv/src/lib.rs]: The timeout thing can be added in a separate PR. Can also add timeouts to the other wait methods.

Comment (LagginTimes) [reply crates/testenv/src/lib.rs]: The error returned is: `Err(Protocol(String("missing transaction")))`

File: crates/testenv/src/lib.rs [hunk 13]
```diff
@@ -168,22 +168,36 @@ impl TestEnv {
     }
 
     /// This method waits for the Electrum notification indicating that a new block has been mined.
-    pub fn wait_until_electrum_sees_block(&self) -> anyhow::Result<()> {
+    /// `timeout` is the maximum amount of seconds we want to wait for a response from Electrsd.
+    pub fn wait_until_electrum_sees_block(&self, timeout: u32) -> anyhow::Result<()> {
```
Comment (evanlinjin) [inline crates/testenv/src/lib.rs]: Can we please make `timeout` a `Duration`?

You can instantiate an `Instant` before the loop and check `Instant::elapsed` against `timeout` within the loop to determine if we need to break.

https://doc.rust-lang.org/std/time/struct.Instant.html#method.elapsed

File: crates/testenv/src/lib.rs [hunk 14]
```diff
@@ -168,22 +168,42 @@ impl TestEnv {
...
             }
+            std::thread::sleep(delay);
+        }
+        Err(anyhow::Error::msg(
+            "Timed out waiting for Electrsd to get block header",
+        ))
+    }
 
-            if delay.as_millis() < 512 {
-                delay = delay.mul_f32(2.0);
```
Comment (evanlinjin) [inline crates/testenv/src/lib.rs:183]: Is there a reason why we got rid of the exponential backoff strategy?

Comment (evanlinjin) [reply crates/testenv/src/lib.rs:183]: As mentioned in DMs, I'm okay with removing this, but can we please document this removal in the commit description? Thanks!

File: crates/electrum/tests/test_electrum.rs [hunk 15]
```diff
@@ -271,35 +303,88 @@ fn scan_detects_confirmed_tx() -> anyhow::Result<()> {
...
 
-    // Mine a block to confirm sent tx.
+    sync_with_electrum(
+        &client,
+        [spk_to_track.clone()],
+        &mut recv_chain,
+        &mut recv_graph,
+    )?;
+
+    // Check if balance is zero when transaction exists only in mempool.
```
Comment (evanlinjin) [inline crates/electrum/tests/test_electrum.rs]: Might need to update this comment now, since we have a pending balance.

File: crates/electrum/tests/test_electrum.rs [hunk 16]
```diff
@@ -271,35 +303,88 @@ fn scan_detects_confirmed_tx() -> anyhow::Result<()> {
...
         get_balance(&recv_chain, &recv_graph)?,
         Balance {
             confirmed: SEND_AMOUNT,
             ..Balance::default()
         },
+        "balance must be correct",
     );
 
+    // Check to see if we have the floating txouts available from our transactions' previous outputs
+    // in order to calculate transaction fees.
```
Comment (evanlinjin) [inline crates/electrum/tests/test_electrum.rs:389]: Since we are testing this, might make sense to mention this in the test's doc comments.

**Review by evanlinjin — CHANGES_REQUESTED** [review]
LGTM. Once these are addressed and changelog is added to PR description, I am happy to merge.

**Review by evanlinjin — APPROVED** [review]
ACK 2c0bc45ecf0241abc8bf9d72c8bbeded53d32a45

File: crates/electrum/tests/test_electrum.rs [hunk 17]
```diff
@@ -407,24 +490,21 @@ fn tx_can_become_unconfirmed_after_reorg() -> anyhow::Result<()> {
...
-            .map_err(|err| anyhow::anyhow!("LocalChain update error: {:?}", err))?;
-
         // Check that no new anchors are added during current reorg.
         assert!(initial_anchors.is_superset(update.graph_update.all_anchors()));
-        let _ = recv_graph.apply_update(update.graph_update);
 
         assert_eq!(
             get_balance(&recv_chain, &recv_graph)?,
             Balance {
+                trusted_pending: SEND_AMOUNT * depth as u64,
```
Comment (ValuedMammal) [inline crates/electrum/tests/test_electrum.rs:507]: I agree this line should be here. It made me wonder why after #1416 the assertion failed, but I think the difference here is that we're updating last-seen during `sync_with_electrum` as we should.

see related #1550
