### PR TITLE
fix: full_scan covers revealed range before applying stop_gap

### LINKED ISSUE #2057: Unintuitive and undocumented `full_scan` behavior
[Book of BDK](https://bookofbdk.com/cookbook/syncing/full-scan-vs-sync/?h=sync) has a overview of the expected sync behavior 

Image

However `full_scan` seems to completely ignore the revealed addresses and goes by the gap only.  This means that if there is a large gap it will not discover any transactions even though the addresses are already revealed.  A `sync` will discover those transactions, such that for a "full scan" one has to do  `full_scan` _and_ `sync` .

Thanks to  @design-rrr for finding this behavior.

- Reproducible in bdkpython 2.0.0

#### Why not do `sync`  most of the time?
- onchain wallets can have multiple instances running, that reveal and use scripts.  That means that the wallet always has to sync at least the gap limit ahead to discover txs that other instances used. 

#### What to do about it?
- Was this behavior intended? 
  - But then to do a full scan, one has to hit the server twice...  --> inefficient

@thunderbiscuit  @ValuedMammal

### PR DESCRIPTION
**Pull request by noahjoeris**
Fixes #2057. `full_scan` now always covers the revealed range before applying the stop_gap

### Notes to the reviewers

Replaces #2181. That PR unified full_scan and sync into one path; per @evanlinjin's feedback we're keeping them separate and doing the minimal fix here instead

### Changelog notice

Fixed: full_scan now always scans the full revealed range before applying stop_gap past last_revealed.

#### All Submissions:

* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)

#### New Features:

* [x] I've added tests for the new feature
* [x] I've added docs for the new feature

#### Bugfixes:

* [ ] This pull request breaks the existing API
* [x] I've added tests to reproduce the issue which are now passing
* [x] I'm linking the issue being fixed by this PR

### CODE REVIEW

File: crates/electrum/src/bdk_electrum_client.rs [hunk 1]
```diff
@@ -267,12 +270,14 @@ impl<E: ElectrumApi> BdkElectrumClient<E> {
...
     /// requested spk will be added to `tx_update`. Anchors of the aforementioned transactions are
     /// also included.
+    #[allow(clippy::too_many_arguments)]
     fn populate_with_spks(
         &self,
         start_time: u64,
         tx_update: &mut TxUpdate<ConfirmationBlockTime>,
         mut spks_with_expected_txids: impl Iterator<Item = (u32, SpkWithExpectedTxids)>,
         stop_gap: usize,
+        last_revealed: Option<u32>,
```
Comment (noahjoeris) [inline crates/electrum/src/bdk_electrum_client.rs:280]: Should we combine some parameters to avoid suppressing clippy::too_many_arguments? e.g.
```
struct StopGapExt {
  stop_gap: usize
  last_revealed Option<u32>
}
```

File: crates/core/src/spk_client.rs
Comment (evanlinjin) [inline crates/core/src/spk_client.rs:493]: We now need to mention that fetching stops after stop-gap number of scripts ABOVE the last-revealed-index. Feel free to improve my wording here.

```suggestion
/// A client full scan iterates through all the scripts for the given keychains, fetching relevant
/// data until some stop gap number of scripts is found (above the last-revealed index) that have no
/// data. This operation is generally only used when importing or restoring previously used
/// keychains in which the list of used scripts is not known. The full scan process also updates the
/// chain from the given [`chain_tip`](FullScanRequestBuilder::chain_tip) (if provided).
```

File: crates/electrum/tests/test_electrum.rs [hunk 2]
```diff
@@ -490,6 +492,47 @@ pub fn test_update_tx_graph_stop_gap() -> anyhow::Result<()> {
     Ok(())
 }
 
+/// Test that `full_scan` always scans the revealed range before applying `stop_gap`.
+#[test]
+pub fn test_stop_gap_past_last_revealed() -> anyhow::Result<()> {
```
Comment (evanlinjin) [inline crates/electrum/tests/test_electrum.rs:502]: Can we expand on this test (or write a new test) to ensure that the stop gap is enforced above last-revealed?

I.e. last_revealed = 10, stop_gap = 5, tx at index = 16 (should not be discovered).

File: crates/electrum/tests/test_electrum.rs [hunk 3]
```diff
@@ -490,6 +492,47 @@ pub fn test_update_tx_graph_stop_gap() -> anyhow::Result<()> {
     Ok(())
 }
 
+/// Test that `full_scan` always scans the revealed range before applying `stop_gap`.
```
Comment (evanlinjin) [inline crates/electrum/tests/test_electrum.rs]:
```suggestion
/// Test that `full_scan` always scans the revealed range before applying `stop_gap`.
///
///
/// Given a single keychain with a tx at index 9, we scan with `stop_gap=3` and `last_revealed=9`.
/// We expect that the tx at index 9 to be returned by the `full_scan`.
```

File: crates/esplora/tests/common/mod.rs [hunk 4]
```diff
@@ -1,14 +1,32 @@
...
-use bdk_core::bitcoin::ScriptBuf;
+use bdk_core::bitcoin::{Address, ScriptBuf};
+use std::str::FromStr;
 
 const PK_BYTES: &[u8] = &[
     12, 244, 72, 4, 163, 4, 211, 81, 159, 82, 153, 123, 125, 74, 142, 40, 55, 237, 191, 231, 31,
     114, 89, 165, 83, 141, 8, 203, 93, 240, 53, 101,
 ];
 
-#[allow(dead_code)]
```
Comment (evanlinjin) [inline crates/esplora/tests/common/mod.rs:9]: Can we have this change in a new commit?

The idiomatic way would be to have `#![allow(dead_code)]` on the top of the file instead of per-item - let's do that in that new commit. This is slightly out of scope, but would be good to get it sorted here imo.

File: crates/electrum/tests/test_electrum.rs (hunk 3 above)
Comment (evanlinjin) [reply crates/electrum/tests/test_electrum.rs]: Can we also have this in the esplora tests?

File: crates/electrum/tests/test_electrum.rs (hunk 2 above)
Comment (evanlinjin) [reply crates/electrum/tests/test_electrum.rs:502]: Also have this in the esplora tests, thanks.

**Review by evanlinjin — CHANGES_REQUESTED** [review]
Thanks for this work. The approach is correct and minimal. Just some small things about docs and tests before ACK and merge.

**Comment by noahjoeris** [comment]
Thanks for the review! Addressed all comments. Docs updated, tests expanded and the `#![allow(dead_code)]` refactor is in its own commit

**Review by evanlinjin — APPROVED** [review]
ACK 187b00747ab978a3bba21df5d14835ec31ed9fa3

**Comment by thunderbiscuit** [comment]
@noahjoeris @evanlinjin I'm wondering if there is a way to backport this into chain 0.23.X so users of the 3.0 wallet could benefit from this. As is, this fix will only come in the 4.0 version of `Wallet`, probably a long way out.

**Comment by evanlinjin** [comment]
@thunderbiscuit definitely possible. This is a non-breaking change. Need to create a minor release for `bdk_core` and subsequent minor releases for the chain sources.

**Comment by thunderbiscuit** [comment]
Awesome. Also by the way, I wasn't asking for someone else to do the work for me haha, I just wanted to check if this was an easy lift or if it needed more thinking through.

I'm happy to do the PR.
