### PR TITLE
fix: remove deprecated max_satisfaction_weight

### LINKED ISSUE #1036: Use `max_weight_to_satisfy` instead of `max_satisfaction_weight`
Needs #1023

`max_satisfaction_weight` is deprecated, we should switch to using `max_weight_to_satisfy` instead.

Note that the switch is not an easy search and replace, the two methods have slightly different definitions

### PR DESCRIPTION
**Pull request by storopoli**
### Description
Continuation of #1115.
Closes #1036.

* Change deprecated `max_satisfaction_weight` to `max_weight_to_satisfy`
* Remove `#[allow(deprecated)]` flags

### Notes to the reviewers

I've changed all `max_satisfaction_weight()` to `max_weight_to_satisfy()` in `Wallet.get_available_utxo()` and `Wallet.build_fee_bump()`. Checking the docs on the `miniscript` crate for `max_weight_to_satisfy` has the following note:

We are testing if the underlying descriptor `is.segwit()` or `.is_taproot`,
then adding 4WU if true or leaving as it is otherwise.

Another thing, we are not testing in BDK tests for legacy (pre-segwit) descriptors.
Should I also add them to this PR?

### Fixed
Replace the deprecated `max_satisfaction_weight` from `rust-miniscript` to `max_weight_to_satisfy`.

#### All Submissions:
* [x]  I've signed all my commits
* [x]  I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x]  I ran `cargo fmt` and `cargo clippy` before committing

#### Bugfixes:
* [ ]  This pull request breaks the existing API
* [ ]  I've added tests to reproduce the issue which are now passing
* [x]  I'm linking the issue being fixed by this PR

### CODE REVIEW

**Review by kaiwolfram — COMMENTED** [review]
‼️‼️ 3️⃣✖️🇸 🇦 🇲 🇪 🎌 🇨 🇴 🇩 🇪 ‼️‼️
🫴4️⃣🤔

File: crates/bdk/src/wallet/mod.rs [hunk 1]
```diff
@@ -2045,13 +2050,18 @@ impl<D> Wallet<D> {
...
-                #[allow(deprecated)]
-                (
-                    utxo,
+                (utxo, {
+                    let is_segwit = self.get_descriptor_for_keychain(keychain).is_witness()
+                        || self.get_descriptor_for_keychain(keychain).is_taproot();
+                    let segwit_add = match is_segwit {
+                        true => 4,
+                        false => 0,
+                    };
```
Comment (evanlinjin) [inline crates/bdk/src/wallet/mod.rs]: Is the intention here to include the `scriptSigLen` weight? If so, please name the variable appropriately.

However, non-segwit inputs also have this field. Wouldn't it be correct to always have this addition?

**Review by evanlinjin — CHANGES_REQUESTED** [review]
Thank you for having a go at this, however the approach here is incorrect.

First off, it's incorrect to add 4WU to only segwit inputs.

Looking at the docs of [`max_weight_to_satisfy`](https://docs.rs/miniscript/latest/miniscript/descriptor/enum.Descriptor.html#method.max_weight_to_satisfy), we need to change the definition of our `TX_IN_BASE_WEIGHT` to be `TxIn::default().segwit_weight()`.

After that, to make the tests pass, we need to change `P2WPKH_SATISFACTION_SIZE` to take in to account the `scriptSigLen` and `witnessLen`.

I think it's okay to assume all transactions are segwit transactions for now? Unless if someone can figure out how to take away the witness len elegantly (for non-segwit txs).

File: crates/bdk/src/wallet/mod.rs (hunk 1 above)
Comment (evanlinjin) [reply crates/bdk/src/wallet/mod.rs]: Ignore the comment above. Just remove this and add the extra weights to `TX_IN_BASE_WEIGHT`.

File: crates/bdk/src/wallet/coin_selection.rs [hunk 2]
```diff
@@ -120,8 +120,9 @@ use rand::seq::SliceRandom;
 pub type DefaultCoinSelectionAlgorithm = BranchAndBoundCoinSelection;
 
 // Base weight of a Txin, not counting the weight needed for satisfying it.
-// prev_txid (32 bytes) + prev_vout (4 bytes) + sequence (4 bytes)
-pub(crate) const TXIN_BASE_WEIGHT: usize = (32 + 4 + 4) * 4;
+// prev_txid (32 bytes) + prev_vout (4 bytes) + sequence (4 bytes) + script_len
+// (1 byte).
+pub(crate) const TXIN_BASE_WEIGHT: usize = (32 + 4 + 4 + 1) * 4;
```
Comment (storopoli) [inline crates/bdk/src/wallet/coin_selection.rs]: @evanlinjin You mean something like this?

Comment (evanlinjin) [reply crates/bdk/src/wallet/coin_selection.rs]: You're missing the witness length

**Comment by evanlinjin** [comment]
Can I please have some input on my statement here? Thanks!

> I think it's okay to assume all transactions are segwit transactions for now? Unless if someone can figure out how to take away the witness len elegantly (for non-segwit txs).

File: crates/bdk/src/wallet/mod.rs (hunk 1 above)
Comment (storopoli) [reply crates/bdk/src/wallet/mod.rs]: Great, sorry for the missundestanding.
I think I've fixed this in 52d6283ecaa343980dc8ef2da2ee3b0b28aaa45e

**Comment by storopoli** [comment]
> I think it's okay to assume all transactions are segwit transactions for now? Unless if someone can figure out how to take away the witness len elegantly (for non-segwit txs).

I agree. We currently don't test any non-segwit tx anyways...

**Comment by evanlinjin** [comment]
> I think it's okay to assume all transactions are segwit transactions for now? Unless if someone can figure out how to take away the witness len elegantly (for non-segwit txs).

Because we already assume this:

https://github.com/bitcoindevkit/bdk/blob/master/crates%2Fbdk%2Fsrc%2Fwallet%2Fmod.rs#L1505-L1513

So I think it is okay.

**Comment by evanlinjin** [comment]
@storopoli can we please rebase the two commits into one and I'll ACK it.

**Comment by storopoli** [comment]
> @storopoli can we please rebase the two commits into one and I'll ACK it.

Done, thanks mate!

File: crates/bdk/src/wallet/tx_builder.rs [hunk 3]
```diff
@@ -318,8 +319,19 @@ impl<'a, D, Cs, Ctx> TxBuilder<'a, D, Cs, Ctx> {
...
+                        .is_witness()
+                        || wallet
+                            .get_descriptor_for_keychain(utxo.keychain)
+                            .is_taproot();
+                    let segwit_add = match is_segwit {
+                        true => 4,
+                        false => 0,
+                    };
+                    descriptor.max_weight_to_satisfy().unwrap() + segwit_add
+                };
```
Comment (evanlinjin) [inline crates/bdk/src/wallet/tx_builder.rs]: This is still wrong.

**Review by evanlinjin — CHANGES_REQUESTED** [review]

File: crates/bdk/src/wallet/tx_builder.rs (hunk 3 above)
Comment (storopoli) [reply crates/bdk/src/wallet/tx_builder.rs]: Sorry about that. Should be good now.

File: crates/bdk/src/wallet/coin_selection.rs [hunk 4]
```diff
@@ -749,9 +747,9 @@ mod test {
     use rand::seq::SliceRandom;
     use rand::{Rng, RngCore, SeedableRng};
 
-    // n. of items on witness (1WU) + signature len (1WU) + signature and sighash (72WU)
-    // + pubkey len (1WU) + pubkey (33WU) + script sig len (1 byte, 4WU)
-    const P2WPKH_SATISFACTION_SIZE: usize = 1 + 1 + 72 + 1 + 33 + 4;
+    // n. of items on witness (1WU) signature and sighash (72WU)
+    // + pubkey len (1WU) + pubkey (33WU)
+    const P2WPKH_SATISFACTION_SIZE: usize = 1 + 72 + 1 + 33;
```
Comment (ValuedMammal) [inline crates/bdk/src/wallet/coin_selection.rs]: I think our accounting is right but just for clarity I would keep signature len in the above comment and drop witness length varint - which should already be included in [segwit_weight](https://docs.rs/bitcoin/0.30.2/bitcoin/blockdata/transaction/struct.TxIn.html#method.segwit_weight).

```suggestion
    // signature len (1WU) + signature and sighash (72WU)
    // + pubkey len (1WU) + pubkey (33WU)
    const P2WPKH_SATISFACTION_SIZE: usize = 1 + 72 + 1 + 33;
```

File: crates/bdk/src/wallet/mod.rs [hunk 5]
```diff
@@ -54,7 +54,6 @@ pub(crate) mod utils;
 pub mod error;
 pub use utils::IsDust;
 
-#[allow(deprecated)]
```
Comment (ValuedMammal) [inline crates/bdk/src/wallet/mod.rs:57]: ❓ I'm actually not sure why this was here before

**Review by ValuedMammal — COMMENTED** [review]
Approach ACK.

For simplicity I think it's fair to assume segwit weight everywhere. Unless someone is doing legacy transactions with hundreds of inputs (which is certainly possible), I don't think you'd notice a difference. We could consider carving out a special case for legacy-only transactions in a future iteration of tx building.

To the note on testing legacy descriptors I don't have an immediate comment on it.

File: crates/bdk/src/wallet/mod.rs (hunk 5 above)
Comment (storopoli) [reply crates/bdk/src/wallet/mod.rs:57]: Me neither, but always glad to nuke it out of the codebase.
More strict lints checks are always welcomed...

File: crates/bdk/src/wallet/coin_selection.rs (hunk 4 above)
Comment (storopoli) [reply crates/bdk/src/wallet/coin_selection.rs]: I like this. I will add the commit and then squash it later

File: crates/bdk/src/wallet/mod.rs (hunk 5 above)
Comment (storopoli) [reply crates/bdk/src/wallet/mod.rs:57]: OOOOOO sorry. Yes, this was here because we were using the deprecated `rust-miniscript`'s `max_satisfaction_weight`.

That's the whole point of the PR 😂

**Comment by evanlinjin** [comment]
@storopoli sorry can you do a rebase on master? thanks

**Comment by storopoli** [comment]
> @storopoli sorry can you do a rebase on master? thanks

Don't worry man. Sure, rebased to master :)

**Review by evanlinjin — APPROVED** [review]
ACK 798ed8ced25156049126645435127a22245e916f
