### PR TITLE
Fix: Hang when `ElectrumBlockchainConfig::stop_gap == 0`

### LINKED ISSUE #651: Setting electrum client's stop_gap as 0 results in hang
**Describe the bug**  

Setting `ElectrumBlockchainConfig::stop_gap` as `0` results in infinite loop during wallet setup/sync.
https://github.com/bitcoindevkit/bdk/blob/063d51fd7587815c733f24365a4de02fed072903/src/blockchain/electrum.rs#L302

**To Reproduce**  
* Create wallet with `ElectrumBlockchainConfig::stop_gap` set as `0`
* Call `Wallet::sync`

**Expected behavior**  
* Electrum blockchain should still be functional with `stop_gap == 0`

**Build environment**  
 - BDK tag/commit: `v0.19.0` 063d51fd7587815c733f24365a4de02fed072903
 - OS+version: Fedora Linux 5.18.5-200.fc36.x86_64
 - Rust/Cargo version: cargo 1.62.0 (a748cf5a3 2022-06-08)
 - Rust/Cargo target: x86_64-unknown-linux-gnu

**Additional context**

Example code:
```rust
let mut test_client = TestClient::default();

let factory = Arc::new(
    ElectrumBlockchain::from_config(&ElectrumBlockchainConfig {
        url: test_client.electrsd.electrum_url.clone(),
        socks5: None,
        retry: 0,
        timeout: None,
        stop_gap: 0, // STOP_GAP IS ZERO
    })
    .unwrap(),
);

let wallet = Wallet::new(
    "wpkh(L5EZftvrYaSudiozVRzTqLcHLNDoVn7H5HSfM9BAN6tMJX8oTWz6)",
    None,
    bitcoin::Network::Regtest,
    MemoryDatabase::new(),
)
.unwrap();

// HANGS HERE INDEFINITELY!!!
factory
    .sync_wallet(&wallet, None, Default::default())
    .unwrap();
```

### PR DESCRIPTION
**Pull request by evanlinjin**
* Ensure `chunk_size` is > 0 during wallet sync.

* Slight refactoring for better readability.

* Add test: `test_electrum_blockchain_factory_sync_with_stop_gaps`

### Description

`Wallet::sync` hangs indefinitely when syncing with Electrum with `stop_gap` set as 0.

The culprit is having `chunk_size` set as `stop_gap`. A zero value results in syncing not being able to progress.

Fixes #651

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### Bugfixes:

~* [ ] This pull request breaks the existing API~
* [x] I've added tests to reproduce the issue which are now passing
* [x] I'm linking the issue being fixed by this PR

### CODE REVIEW

**Comment by evanlinjin** [comment]
I realized for the test, I'm using a single key descriptor, when I really should be using an extended key, since we are testing the stop gap.

So this is still WIP.

File: src/blockchain/electrum.rs [hunk 1]
```diff
@@ -385,4 +386,116 @@ mod test {
 
         assert_eq!(wallet.get_balance().unwrap(), 50_000);
     }
+
+    #[test]
+    fn test_electrum_blockchain_factory_sync_with_stop_gaps() {
```
Comment (LLFourn) [inline src/blockchain/electrum.rs]: can we put this in `blockchain_tests` so it covers all blockchains?

Comment (evanlinjin) [reply src/blockchain/electrum.rs]: That's a good idea, I'll do so in a bit.

**Comment by LLFourn** [comment]
Interesting bug. I'm not sure about the semantics of `stop_gap = 0`? Maybe the correct thing is to do nothing. If I am going to stop after I find a gap of 0 then I should just stop right away no? (you start off with a gap of 0).

**Comment by evanlinjin** [comment]
> Interesting bug. I'm not sure about the semantics of `stop_gap = 0`? Maybe the correct thing is to do nothing. If I am going to stop after I find a gap of 0 then I should just stop right away no? (you start off with a gap of 0).

From my understanding, the gap between 0 and 1 is zero, as there is no gap. These are integers, so there are no numbers between 0 and 1.

File: src/blockchain/electrum.rs [hunk 2]
```diff
@@ -108,7 +108,10 @@ impl WalletSync for ElectrumBlockchain {
         let mut block_times = HashMap::<u32, u32>::new();
         let mut txid_to_height = HashMap::<Txid, u32>::new();
         let mut tx_cache = TxCache::new(database, &self.client);
-        let chunk_size = self.stop_gap;
+
+        // Ensure chunk_size > 0, otherwise we will result in an infinite loop
```
Comment (LLFourn) [inline src/blockchain/electrum.rs]: I understand better what is going on now. We must find a gap greater than `stop_gap` in order to stop.
So I think this comment should be: 

> set the chunk_size to the smallest value that we can find a gap greater than stop gap.

It is also a performance issue to set it to `stop_gap` since you will do two requests when you should only do one on any empty wallet (for example).

**Comment by LLFourn** [comment]
ACK. See https://github.com/bitcoindevkit/bdk/pull/652#discussion_r912656091 

`chunk_size` was set wrongly before. Thanks!

File: src/blockchain/electrum.rs (hunk 2 above)
Comment (evanlinjin) [reply src/blockchain/electrum.rs]: Changed in 475b005eb9151284885600896e8f0f50a45cd1b2.

File: src/blockchain/electrum.rs (hunk 1 above)
Comment (evanlinjin) [reply src/blockchain/electrum.rs]: > can we put this in `blockchain_tests` so it covers all blockchains?

I feel like this is too much work for this PR. Should we get this merged and I can create a second ticket?

Each test case requires creating a new `Blockchain` with a specified `stop_gap`.

I am also not very familiar with macros in Rust, so this may take a while.

Comment (LLFourn) [reply src/blockchain/electrum.rs]: Hmmmm. Ok I see and agree with this point. Not all blockchains have "stop gaps" anyways.

Comment (evanlinjin) [reply src/blockchain/electrum.rs]: We can definitely do something universal I think. Can create a custom test trait with a method such as `generate_blockchain_with_stop_gap` and have that trait as an input.

File: src/blockchain/electrum.rs [hunk 3]
```diff
@@ -145,18 +148,16 @@ impl WalletSync for ElectrumBlockchain {
                 Request::Conftime(conftime_req) => {
                     // collect up to chunk_size heights to fetch from electrum
                     let needs_block_height = {
-                        let mut needs_block_height_iter = conftime_req
+                        let mut needs_block_height = HashSet::with_capacity(chunk_size);
```
Comment (afilini) [inline src/blockchain/electrum.rs]: I think here you can just construct the `HashSet` from the iterator, using the `FromIterator` trait:

```rust
let needs_block_height = conftime_req./*<long chain>*/.collect();
```

File: src/blockchain/electrum.rs [hunk 4]
```diff
@@ -385,4 +386,116 @@ mod test {
...
+        // Amount (in satoshis) provided to a single address (which expects to have a balance)
+        const AMOUNT_PER_TX: u64 = 1000;
+
+        // [stop_gap, actual_gap, addrs_before, addrs_after]
+        //
+        // [0]     stop_gap: Passed to [`ElectrumBlockchainConfig`]
+        // [1]   actual_gap: Range size of address indexes without a balance
+        // [2] addrs_before: Range size of address indexes (before gap) which contains a balance
+        // [3]  addrs_after: Range size of address indexes (after gap) which contains a balance
+        let test_vectors: Vec<[u64; 4]> = vec![
```
Comment (afilini) [inline src/blockchain/electrum.rs]: Wouldn't it be better to use `usize` here? I see that you have to cast these values in a few places

**Review by afilini — COMMENTED** [review]
Concept ACK, a couple of things:

- did you check if this happens with esplora as well? The two blockchains are very similar in terms of architecture and code
- once you are done fixing the various comments, could you squash the commits into the first one?

**Comment by evanlinjin** [comment]
> Concept ACK, a couple of things:
> 
> - did you check if this happens with esplora as well? The two blockchains are very similar in terms of architecture and code
> - once you are done fixing the various comments, could you squash the commits into the first one?

Thank you for the review! I'll test all Blockchains with a stop_gap and do some rebasing after ☺️

**Comment by evanlinjin** [comment]
> did you check if this happens with esplora as well? The two blockchains are very similar in terms of architecture and code

@afilini I've made a trait that can be reused for testing both esplora and electrum. I've also made it expandable, so in the future we can implement more tests in it. Let me know whether these changes make sense!

File: src/blockchain/electrum.rs (hunk 1 above)
Comment (evanlinjin) [reply src/blockchain/electrum.rs]: I've done something relatively universal, we can continue this conversation here: https://github.com/bitcoindevkit/bdk/pull/652#issuecomment-1173789385

File: src/blockchain/electrum.rs (hunk 4 above)
Comment (evanlinjin) [reply src/blockchain/electrum.rs]: It seems that if we do this, other variables will need casting... Should we leave it as is?

**Comment by evanlinjin** [comment]
> once you are done fixing the various comments, could you squash the commits into the first one?

@afilini I feel like it's better to keep it to two commits. One if for the actual fix, the other is introducing a new testing trait that can be shared between different blockchain implementations.

What do you think?

**Comment by evanlinjin** [comment]
@afilini Should this fix also be part of [Release 0.20.0 Feature Freeze](https://github.com/bitcoindevkit/bdk/milestone/16)?

Ensuring that the `Blockchain` implementations respect the `stop_gap` parameter can potentially be important for avoiding address reuse.

The test I have included checks for this.

https://github.com/bitcoindevkit/bdk/blob/612da165f8cfbc2b0aee0a37b2cdc44d6da017c8/src/testutils/configurable_blockchain_tests.rs#L131-L135

File: src/blockchain/electrum.rs (hunk 4 above)
Comment (afilini) [reply src/blockchain/electrum.rs]: Yeah at a quick glance I thought using usize would be fine, but if you need to cast anyway there's no reason to change it

**Comment by afilini** [comment]
> @afilini I feel like it's better to keep it to two commits. One if for the actual fix, the other is introducing a new testing trait that can be shared between different blockchain implementations.

Yeah two commits works for me, as long as they are self-contained (they should both compile and run `cargo test` with no errors) and they have a good commit message

> @afilini Should this fix also be part of [Release 0.20.0 Feature Freeze](https://github.com/bitcoindevkit/bdk/milestone/16)?

I don't think this is as critical as that other one, but if this is ready in time yes, this is also important

**Review by afilini — APPROVED** [review]
ACK 612da165f8cfbc2b0aee0a37b2cdc44d6da017c8
