### PR TITLE
fix(chain): filter coinbase tx not in best chain

### LINKED ISSUE #1144: Coinbase transaction that is not anchored in the best chain should always be filtered out
**Describe the bug**  

Coinbase transactions cannot exist in the mempool and be unconfirmed. `TxGraph::try_get_chain_position` should always return `None` for coinbase transactions which are not anchored in the best chain.

**To Reproduce**  

A proper test has not been written for this scenario. The test would mine blocks which has the coinbase send to a tracked/owned spk. A reorg should not result in an unconfirmed balance.

**Expected behavior**  

Coinbase transactions cannot be "unconfirmed".

### PR DESCRIPTION
**Pull request by LagginTimes**
### Description

Fixes #1144.
Coinbase transactions cannot exist in the mempool and be unconfirmed. `TxGraph::try_get_chain_position` should always return `None` for coinbase transactions not anchored in best chain.

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### Bugfixes:

* [ ] This pull request breaks the existing API
* [x] I've added tests to reproduce the issue which are now passing
* [x] I'm linking the issue being fixed by this PR

### CODE REVIEW

File: crates/chain/tests/test_tx_graph_conflicts.rs [hunk 1]
```diff
@@ -45,6 +45,46 @@ fn test_tx_conflict_handling() {
         .unwrap_or_default();
 
     let scenarios = [
+        Scenario {
+            name: "coinbase tx cannot be in mempool and be unconfirmed",
+            tx_templates: &[
+                TxTemplate {
+                    tx_name: "coinbase",
```
Comment (danielabrozzoni) [inline crates/chain/tests/test_tx_graph_conflicts.rs]: nit: I would call this "unconfirmed_coinbase"

**Review by danielabrozzoni — COMMENTED** [review]
The code looks good to me.

In #1144, @evanlinjin says:

> A proper test has not been written for this scenario. The test would mine blocks which has the coinbase send to a tracked/owned spk. A reorg should not result in an unconfirmed balance.

Are we ok with the test that this PR includes, or better to also add the one evan is suggesting?

**Review by notmandatory — APPROVED** [review]
ACK 991cb77b6fbeedbf52d1bd9aa6b3d680f8269969

I verified new test fails without this fix. If an additional test is needed and not easy to do with current framework can we make a new issue and put in the beta milestone?

**Review by danielabrozzoni — APPROVED** [review]
ACK 991cb77b6fbeedbf52d1bd9aa6b3d680f8269969
