### PR TITLE
Include the descriptor in `keychain::Changeset`

### LINKED ISSUE #1101: Reintroduce descriptor data to `bdk::Wallet` persistence
**Describe the enhancement**

The current stable version of BDK stores the descriptor checksum in the database. This ensures the caller does not use the wrong descriptor with the database. We should reintroduce this.

**Implementation proposal**

Add `verify_checksum` method to the `Persist` trait.

### PR DESCRIPTION
**Pull request by danielabrozzoni**
Fixes bitcoindevkit/bdk#1101

- Moves keychain::ChangeSet inside `keychain/txout_index.rs` as now the `ChangeSet` depends on miniscript
- Slightly cleans up tests by introducing some constant descriptors
- The KeychainTxOutIndex's internal SpkIterator now uses DescriptorId
instead of K. The DescriptorId -> K translation is made at the
KeychainTxOutIndex level.
- The keychain::Changeset is now a struct, which includes a map for last
revealed indexes, and one for newly added keychains and their
descriptor.

### Changelog notice

API changes in bdk:
- Wallet::keychains returns a `impl Iterator` instead of `BTreeMap`
- Wallet::load doesn't take descriptors anymore, since they're stored in the db
- Wallet::new_or_load checks if the loaded descriptor from db is the same as the provided one
  
API changes in bdk_chain:
- `ChangeSet` is now a struct, which includes a map for last revealed
      indexes, and one for keychains and descriptors.
- `KeychainTxOutIndex::inner` returns a `SpkIterator<(DescriptorId, u32)>`
- `KeychainTxOutIndex::outpoints` returns a `BTreeSet` instead of `&BTreeSet`
- `KeychainTxOutIndex::keychains` returns a `impl Iterator` instead of
      `&BTreeMap`
- `KeychainTxOutIndex::txouts` doesn't return a ExactSizeIterator anymore
- `KeychainTxOutIndex::last_revealed_indices` returns a `BTreeMap`
      instead of `&BTreeMap`
- `KeychainTxOutIndex::add_keychain` has been renamed to `KeychainTxOutIndex::insert_descriptor`, and now it returns a ChangeSet
- `KeychainTxOutIndex::reveal_next_spk` returns Option
- `KeychainTxOutIndex::next_unused_spk` returns Option
- `KeychainTxOutIndex::unbounded_spk_iter` returns Option
- `KeychainTxOutIndex::next_index` returns Option
- `KeychainTxOutIndex::reveal_to_target` returns Option
- `KeychainTxOutIndex::revealed_keychain_spks` returns Option
- `KeychainTxOutIndex::unused_keychain_spks` returns Option
- `KeychainTxOutIndex::last_revealed_index` returns Option
- `KeychainTxOutIndex::keychain_outpoints` returns Option
- `KeychainTxOutIndex::keychain_outpoints_in_range` returns Option
- `KeychainTxOutIndex::last_used_index` returns None if the keychain has never been used, or if it doesn't exist

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### New Features:

* [x] I've added tests for the new feature
* [x] I've added docs for the new feature

### CODE REVIEW

File: crates/chain/src/keychain/txout_index.rs [hunk 1]
```diff
@@ -11,6 +11,75 @@ use core::{fmt::Debug, ops::Deref};
...
+    serde(
+        crate = "serde_crate",
+        bound(
+            deserialize = "K: Ord + serde::Deserialize<'de>",
+            serialize = "K: Ord + serde::Serialize"
+        )
+    )
+)]
+#[must_use]
+pub struct ChangeSet<K>(pub BTreeMap<K, (Descriptor<DescriptorPublicKey>, u32)>);
```
Comment (evanlinjin) [inline crates/chain/src/keychain/txout_index.rs]: The problem with this design, is that every time we need to increase the last derivation index, we need to include the descriptor in the changeset. This is rather expensive.

What do you think about having two fields? One for descriptors, one for last derivation indices?

File: crates/chain/src/keychain/txout_index.rs [hunk 2]
```diff
@@ -11,6 +11,75 @@ use core::{fmt::Debug, ops::Deref};
...
+}
+
+impl<K: Ord> Append for ChangeSet<K> {
+    /// Append another [`ChangeSet`] into self.
+    ///
+    /// For each keychain in the given [`ChangeSet`]:
+    /// - If the keychain already exists in the old [`ChangeSet`], and the two descriptors are the
+    /// same, we increase the index when new index > old index.
+    /// - If the keychain already exists, but with a different descriptor, we overwrite the
+    /// original descriptor with the changeset one.
```
Comment (evanlinjin) [inline crates/chain/src/keychain/txout_index.rs]: I'm wondering whether it is a good idea to allow changing the descriptor for a keychain... It may result in some potentially confusing behavior? The other option is to ignore it, and add a `debug_assert!` statement when a changeset attempts to change the descriptor.

File: crates/chain/src/keychain/txout_index.rs [hunk 3]
```diff
@@ -11,6 +11,75 @@ use core::{fmt::Debug, ops::Deref};
 
 use crate::Append;
 
+/// Represents updates to the derivation index of a [`KeychainTxOutIndex`].
+/// It maps each keychain `K` to a descriptor and its last revealed index.
+///
+/// It can be applied to [`KeychainTxOutIndex`] with [`apply_changeset`]. [`ChangeSet] are
```
Comment (evanlinjin) [inline crates/chain/src/keychain/txout_index.rs:19]:
```suggestion
/// It can be applied to [`KeychainTxOutIndex`] with [`apply_changeset`]. [`ChangeSet`]s are
```

**Review by evanlinjin — CHANGES_REQUESTED** [review]
Thanks for taking this forward. This is my initial round of comments!

**Comment by evanlinjin** [comment]
Oh and it seems like you need to rebase.

File: crates/chain/src/keychain/txout_index.rs (hunk 2 above)
Comment (LLFourn) [reply crates/chain/src/keychain/txout_index.rs]: Let's make this monotone. Just take the highest `(descriptor, index)` pair as a tiebreak (`Descriptor` implements `Ord`). Don't allow changing the descriptor for a given in the API so hopefully this can't happen in practice but we at least make the changesets monotone in case it does.

[EDIT] this concrete proposal makes less sense given what I suggest above but we should try and make the changesets monotone.

File: crates/chain/src/keychain/txout_index.rs (hunk 1 above)
Comment (LLFourn) [reply crates/chain/src/keychain/txout_index.rs]: Could it be like this:

```
ChangeSet<K> {
    /// Descriptors indexed by keychain. Note that in the case a changeset is applied to an [`KeychainTxOutIndex`] that already has a descriptor under that keychain then it will choose the greatest `Descriptor` according to `Ord`. 
    pub descriptors: BTreeMap<K, Descriptor>,
    /// Index of the script pubkey that was last revealed
    pub last_revealed: BTreeMap<Descriptor, u32>,
}
```
This links descriptors to last derivation indices rather than keychain. We could do this inside the `KeychainTxOutIndex` as well.

A more broad question is can we take moment to redesign this without `K` at all? We could use the `(Descriptor, u32)` as the key in the underlying `Spk` tracker. This would be wasteful from a memory perspective so we could compress this down to `32` bytes with sha256 -- but it's still a bit wasteful. Other option is to come up with a internal index for each descriptor as they are added.

I think I'm against this idea but thought I should bring it up. Offloading the problem of labeling Descriptors to the user keeps things efficient internally and I think you almost always want to label descriptors with some semantic meaning inside your application.

Comment (evanlinjin) [reply crates/chain/src/keychain/txout_index.rs]: > This links descriptors to last derivation indices rather than keychain.

@LLFourn Is this so that we can avoid setting the last revealed index to a keychain with no descriptor?

Comment (LLFourn) [reply crates/chain/src/keychain/txout_index.rs]: It's to avoid a changeset changing the descriptor of a keychain but inheriting the last seen of the old descriptor. Thinking further doing literally what I suggested above is a terrible idea because descriptors can be arbitrarily large (you already pointed this out). Not sure if necessary -- I'd very happy if you and/or @danielabrozzoni to make the call about the design here. I think my preference has changed to what you suggested in the OP.

**Comment by danielabrozzoni** [comment]
Hey @evanlinjin and @LLFourn, thanks a lot for your reviews. I've given some thoughts about them:

1. I agree that having a BTreeMap with everything inside is not optimal, and a structure with both last_revealed and descriptor would be better. That being said, we need to make sure that users don't pass in a (keychain, index) without the correspondent descriptor.
2. The more I think about it, the more I convince myself that we shouldn't let the user modify the descriptor - otherwise, what's the point of having a db checksum? I think that changing it silently (as my code is doing right now), or making the changeset monotone as lloyd suggested, might be potential footguns. (I might not have fully comprehended lloyd's proposal though!)

It seems to me that it would be optimal to have `append` return a Result, and error in the two cases; but the Append trait doesn't specify any return value for `append`. How should I go about this?

File: crates/chain/src/keychain/txout_index.rs (hunk 1 above)
Comment (danielabrozzoni) [reply crates/chain/src/keychain/txout_index.rs]: > I think I'm against this idea but thought I should bring it up. Offloading the problem of labeling Descriptors to the user keeps things efficient internally and I think you almost always want to label descriptors with some semantic meaning inside your application.

I agree, I think it's useful from the user perspective to have a way to label descriptor, and so I'd prefer not to remove it.

**Comment by evanlinjin** [comment]
Just quoting @LLFourn's response to adding an error to `Append` trait methods:

> Because we should design things so that there should be no possible error

> The errors would have to be programmer errors which should be handled via panic or just carry on with best effort.

> I think there would most of the time be ways to re-architect the changeset to avoid errors completely. That's the trade off. Either design it so there can't be errors (may mean bigger more monotone changesets) or just accept the error.

**Comment by evanlinjin** [comment]
What do we think about using `debug_assert!` in the `Append` implementation for now? This will check if we are mutating the descriptor of an already-existing keychain. In release mode, the consecutive changes to a keychain's descriptor should just be ignored.

The `add_keychain` method should error if a user is trying to modify an already-existing keychain. The changesets are returned by `KeychainTxOutIndex` methods. The `KeychainTxOutIndex` should never create consecutive changesets that modify the same keychain's descriptor. So I think my suggestion is fair.

File: crates/chain/src/keychain/txout_index.rs [hunk 4]
```diff
@@ -11,6 +11,75 @@ use core::{fmt::Debug, ops::Deref};
...
+    /// Append another [`ChangeSet`] into self.
+    ///
+    /// For each keychain in the given [`ChangeSet`]:
+    /// - If the keychain already exists in the old [`ChangeSet`], and the two descriptors are the
+    /// same, we increase the index when new index > old index.
+    /// - If the keychain already exists, but with a different descriptor, we overwrite the
+    /// original descriptor with the changeset one.
+    /// - If the keychain did not exist, append the new keychain.
+    fn append(&mut self, mut other: Self) {
+        for (key, (descriptor, index)) in &mut self.0 {
```
Comment (notmandatory) [inline crates/chain/src/keychain/txout_index.rs:54]: nit: can we call `key` here `keychain` to improve readability

Comment (notmandatory) [inline crates/chain/src/keychain/txout_index.rs]: nit, for readability can we call `key` here `keychain` ?

File: crates/chain/tests/test_keychain_txout_index.rs [hunk 5]
```diff
@@ -42,24 +42,95 @@ fn spk_at_index(descriptor: &Descriptor<DescriptorPublicKey>, index: u32) -> Scr
...
+    let mut lhs = ChangeSet(lhs_di);
+    let rhs = ChangeSet(rhs_di);
+    lhs.append(rhs);
+
+    // Descriptor gets updated
+    assert_eq!(
+        lhs.0.get(&Keychain::Zero),
+        (Some(&(descriptors[1].clone(), 13)))
+    );
+    // Exiting index doesn't update if the new index in `other` is lower than `self`.
```
Comment (notmandatory) [inline crates/chain/tests/test_keychain_txout_index.rs]:
```suggestion
    // Existing index doesn't update if the new index in `other` is lower than `self`.
```

**Review by notmandatory — COMMENTED** [review]
I've been trying to think of how to keep `ChangeSet<K>` monotone and I think we should not change the keychain::ChangeSet and instead enforce that  descriptors don't change at the bdk::wallet::ChangeSet level.  This puts responsibility on the devs who who don't use bdk::wallet to keep their data consistent. They can either follow how we do it in `Wallet` or go their own way if they know what they're doing. I created #1234 to demonstrate this approach, would love some feed back.

**Comment by LLFourn** [comment]
> I've been trying to think of how to keep `ChangeSet<K>` monotone and I think we should not change the keychain::ChangeSet and instead enforce that descriptors don't change at the bdk::wallet::ChangeSet level. This puts responsibility on the devs who who don't use bdk::wallet to keep their data consistent. They can either follow how we do it in `Wallet` or go their own way if they know what they're doing. I created bitcoindevkit/bdk#1234 to demonstrate this approach, would love some feed back.

This is actually becoming my intuition too but have an idea a bit different bitcoindevkit/bdk#1234. I think the descriptor has to be in the keychain changeset because that's where it's stored in memory and it has to be there to produce new addresses. Having it elsewhere adds friction and removing that is the point of this effort.

We can keep `KeychainTxOutIndex` simple and keep changesets montone by removing the type parameter `K` from it. There is a perfectly coherent bit of functionality with its own persistence mechanism that cannot conflict with anything else that we can carve out here and leave labeling to later. For now we can let `Wallet` handle its own labeling with the `KeychainKind` enum in its own addition to its changeset.

So here's my suggestion:

1. Use descriptor hash to identify descriptor (as @notmandatory does in his approach). Let's call it `DescriptorId` and make it `type DescriptorId = sha256::Hash` for now.
2. Rename `KeychainTxOutIndex` to `DescriptorTxOutIndex`
3. Define it as follows:

```rust
#[derive(Clone, Debug)]
pub struct DescriptorTxOutIndex {
    inner: SpkTxOutIndex<(DescriptorId, u32)>,
    // descriptors of each keychain
    descriptors: BTreeMap<DescriptorId, Descriptor<DescriptorPublicKey>>,
    // last revealed indexes
    last_revealed: BTreeMap<DescriptorId, u32>,
    // lookahead settings for each descriptor
    lookahead: BTreeMap<DescriptorId, u32>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize, serde::Serialize)]
pub struct ChangeSet {
    revealed: BTreeMap<DescriptorId, u32>
    added: BTreeSet<Descriptor<DescriptorPublicKey>
}
```

Methods in `DescriptorTxOutIndex` should take a `DescriptorId`. 

This changeset is monotone and error free and gives us most of the useful things that `KeychainTxOutIndex` did. We could of course keep `KeychainTxOutIndex` and implement with a `DescriptorTxOutIndex` internally but I think we should just do `Wallet` first and add that later if we want it. I guess the examples won't be too hard to change (it might even simplify them a bit!).

So here's what `Wallet` changeset would become:

```rust
/// The changes made to a wallet by applying an [`Update`].
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, Default)]
pub struct ChangeSet {
    /// Changes to the [`LocalChain`].
    ///
    /// [`LocalChain`]: local_chain::LocalChain
    pub chain: local_chain::ChangeSet,

    /// Changes to [`IndexedTxGraph`].
    ///
    /// [`IndexedTxGraph`]: bdk_chain::indexed_tx_graph::IndexedTxGraph
    pub indexed_tx_graph: indexed_tx_graph::ChangeSet<
        ConfirmationTimeHeightAnchor,
        descriptor::ChangeSet,
    >,

    /// Stores they keychains of the wallet and their descriptors.
    /// This should only be non-empty in the first changeset of the wallet.
    keychains: BTreeMap<KeychainKind, DescriptorId>.

    /// Stores the network type of the wallet.
    pub network: Option<Network>,   
}
```

Of course this is non-monotone but it's better to have these hacks up here than down in `bdk_chain`. Since our API doesn't allow you to mutate descriptors it could also be fixed by bitcoindevkit/bdk_wallet#125 i.e. setting `keychains` and `network` in the header. There is a question about whether keychains should have a `DescriptorId` or a `Descriptor` in it. If you use `DescriptorId` you always have to make sure the `Descriptor` is in the index and have an error case where a `DescriptorId` gets added to `keychains` but not `indexed_tx_graph`. Using the `Descriptor` in `keychains` redundantly stores the descriptors but remove the error case. I think I lean to just have `DescriptorId` since I don't see it causing too much trouble.

We'll probably want to add a `descriptor_id()` to `DescriptorExt` in `bdk_chain`.

Thoughts?

**Comment by LLFourn** [comment]
> Thoughts?

So after sleeping on it I have changed my view a little bit. The design above is the most in line with the overall design philosophy and removes all possible invalid representations at the `bdk_chain` level. But it *is* a very nice feature to label descriptors and we use it in examples and almost every user will want to attach some kind of application semantics to the descriptor. So I want to modify the above proposal to keep `KeychainTxOutIndex` *but* have it internally function mostly like what was suggested above so that we remove most of the surface area for footguns.

```rust
#[derive(Clone, Debug)]
pub struct KeychainTxOutIndex<K> {
    inner: SpkTxOutIndex<(DescriptorId, u32)>,
    // descriptors of each keychain
    descriptors: BTreeMap<DescriptorId, Descriptor<DescriptorPublicKey>>,
    // last revealed indexes
    last_revealed: BTreeMap<DescriptorId, u32>,
    // lookahead settings for each descriptor
    lookahead: BTreeMap<DescriptorId, u32>,

    keychains: BTreeMap<K, DescriptorId> 
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize, serde::Serialize)]
pub struct ChangeSet<K> {
    revealed: BTreeMap<DescriptorId, u32>,
    keychains_added: BTreeMap<K, Descriptor<DescriptorPublicKey>
}
```

This means the non-montonicity is restricted to `keychains_added` field where we can implement `keychains_added` by just replacing descriptors with the most recent one (i.e. just use `BTreeMap::append`). Replacing a keychain will not be a permanent break of anything -- You could just re-replace it with the correct one and all the other values like `last_revealed` would return to their correct values. In fact this even makes it possible to replace a keychain with another descriptor **while not losing the old coins**. Since the last revealed is associated with the descriptor rather than keychain it will also always load all the old spks. So this turns a bug into a feature in a relatively safe way -- it's probably not a feature that you should ever use though!

**Comment by ValuedMammal** [comment]
@LLFourn Thanks for the detailed explanation. It helped clarify for me why persisting descriptor data at the wallet level is perhaps not enough. I think this direction is well aligned with the related effort of separating out a "header" changeset.

**Comment by notmandatory** [comment]
~~I'll take a crack at implementing your new `KeychainTxOutIndex<K>` design, but if @danielabrozzoni gets to it first in this PR that's fine too. At least I'll be a better reviewer if I play with it a bit.~~ @danielabrozzoni has this one, I'll still help review.

**Comment by notmandatory** [comment]
Please rebase now that bitcoindevkit/bdk#1183 has been merged.

**Comment by evanlinjin** [comment]
@LLFourn very nice!

**Comment by notmandatory** [comment]
I fixed some new CI issues with bitcoindevkit/bdk#1247, it just needs to be ACKd and merged and then this PR rebased.

**Comment by danielabrozzoni** [comment]
@LLFourn @evanlinjin do you think it's ok if `KeychainTxOutIndex::keychains` returns a `BTreeMap<&K, &Descriptor<DescriptorPublicKey>>` instead of `&BTreeMap<K, Descriptor<DescriptorPublicKey>>`?

The thing is, after refactoring the `KeychainTxOutIndex`, I don't have a `keychain -> desc` map that I can return a reference to. Returning a `BTreeMap<&..., &...>` is the best idea that come to my mind, other possibilities are returning a `BTreeMap<K, Desc>` (seems wasteful) or keeping in the keychain index the `BTreeMap<K, Desc>` (unclean, but maybe it's the same case as `TxGraph::empty_outspends`?)

**Comment by evanlinjin** [comment]
@danielabrozzoni personally I would prefer returning an `impl Iterator<Item = (K, &Desc)>`. What do you think?

**Comment by danielabrozzoni** [comment]
@evanlinjin I see how Iter<...> is better than BTreeMap<...> since you don't need to collect, but why returning `K` instead of `&K`?

**Comment by LLFourn** [comment]
`&K` is fine to me

**Comment by danielabrozzoni** [comment]
Pushed an update. It still needs a rebase, but while I work on it, can you let me know what you think?

File: crates/chain/src/keychain/txout_index.rs [hunk 6]
```diff
@@ -5,11 +5,85 @@ use crate::{
...
     SpkIterator, SpkTxOutIndex,
 };
+use alloc::string::{String, ToString};
 use bitcoin::{OutPoint, Script, TxOut};
 use core::{fmt::Debug, ops::Deref};
+use miniscript::descriptor::checksum::desc_checksum;
 
 use crate::Append;
 
+type DescriptorId = String;
```
Comment (evanlinjin) [inline crates/chain/src/keychain/txout_index.rs]: String is not nice as it is variable-length.

Additionally, we can use a byte array (instead of a char array as returned by `checksum_chars`). If you look at the implementation of `checksum_chars`, they take bytes from a byte array and needlessly transform them to chars.

If rust-bitcoin people start returning non UTF-8 chars as part of their checksum, this will be something to complain about. No one needs emojis in their checksum.

```suggestion
type DescriptorId = [u8; 8];

fn descriptor_id(desc: &Descriptor<DescriptorPublicKey>) -> DescriptorId {
    let mut eng = miniscript::descriptor::checksum::Engine::new();
    eng.input(&desc.to_string()).expect("must!");
    let mut id = DescriptorId::default();
    for (i, c) in eng.checksum_chars().into_iter().enumerate() {
        id[i] = c as u8;
    }
    id
}
```

File: crates/chain/src/keychain/txout_index.rs [hunk 7]
```diff
@@ -61,10 +135,14 @@ const DEFAULT_LOOKAHEAD: u32 = 1_000;
 #[derive(Clone, Debug)]
 pub struct KeychainTxOutIndex<K> {
     inner: SpkTxOutIndex<(K, u32)>,
-    // descriptors of each keychain
-    keychains: BTreeMap<K, Descriptor<DescriptorPublicKey>>,
+    // descriptor id -> descriptor map
+    descriptors: BTreeMap<DescriptorId, Descriptor<DescriptorPublicKey>>,
+    // keychain -> descriptor id map
+    keychains_to_descriptor_ids: BTreeMap<K, DescriptorId>,
```
Comment (evanlinjin) [inline crates/chain/src/keychain/txout_index.rs]:
```suggestion
    // keychain -> (descriptor_id, descriptor) map
    descriptors: BTreeMap<K, (DescriptorId, Descriptor<DescriptorPublicKey>>),
```

File: crates/chain/src/keychain/txout_index.rs [hunk 8]
```diff
@@ -126,14 +210,31 @@ impl<K> KeychainTxOutIndex<K> {
...
+        let descriptor_id = self
+            .keychains_to_descriptor_ids
+            .get(keychain)
+            .expect("keychain must exist");
+        let descriptor = self
+            .descriptors
+            .get(descriptor_id)
+            .expect("descriptor must exist");
+        (descriptor_id, descriptor)
+    }
```
Comment (evanlinjin) [inline crates/chain/src/keychain/txout_index.rs]: We need to be careful about calling this. Ideally, we avoid panics. If that is not possible, we need to document panics.

**Review by evanlinjin — CHANGES_REQUESTED** [review]
Thank you for taking this forward! Here is an incomplete review (will complete later).

File: crates/chain/src/keychain/txout_index.rs [hunk 9]
```diff
@@ -158,13 +261,30 @@ impl<K: Clone + Ord + Debug> KeychainTxOutIndex<K> {
     ///
     /// This will panic if a different `descriptor` is introduced to the same `keychain`.
     pub fn add_keychain(&mut self, keychain: K, descriptor: Descriptor<DescriptorPublicKey>) {
```
Comment (evanlinjin) [inline crates/chain/src/keychain/txout_index.rs]: This should return a changeset.

Also, the new behavior should not panic when we replace a descriptor.

File: crates/chain/src/keychain/txout_index.rs [hunk 10]
```diff
@@ -61,10 +135,14 @@ const DEFAULT_LOOKAHEAD: u32 = 1_000;
 #[derive(Clone, Debug)]
 pub struct KeychainTxOutIndex<K> {
     inner: SpkTxOutIndex<(K, u32)>,
```
Comment (evanlinjin) [inline crates/chain/src/keychain/txout_index.rs]:
```suggestion
    inner: SpkTxOutIndex<(DescriptorId, u32)>,
```

Because it is possible to change the descriptor of a keychain, this is a more accurate representation.

Comment (evanlinjin) [reply crates/chain/src/keychain/txout_index.rs]: Because of this, we may need two versions of some methods.

I.e. `reveal_to_target` will have a non-pub version: `reveal_to_target_with_id` that takes in a `DescriptorId` instead of `K`.

File: crates/chain/src/keychain/txout_index.rs (hunk 8 above)
Comment (danielabrozzoni) [reply crates/chain/src/keychain/txout_index.rs]: Good catch. I changed descriptor_of_keychain to return an Option, and I explicitly expected where needed.

I am thinking of also panicking in `revealed_spks_of_keychain` and `unused_spks_of_keychain` - previously, they would just return empty iterators if you passed in a non-existent keychain, but panicking seems more appropriate. What do you think?

Comment (evanlinjin) [reply crates/chain/src/keychain/txout_index.rs]: I prefer returning empty iterators instead of panicing. I'm thinking if there was no descriptor under a keychain, nothing should be returned when we query about the keychain.

**Comment by evanlinjin** [comment]
> @evanlinjin I see how Iter<...> is better than BTreeMap<...> since you don't need to collect, but why returning `K` instead of `&K`?

I would assume for the majority of cases, `K` is small (as an identifier) so cloning/copying would be cheaper than working with references. Therefore I prefer not having references on `K.

File: crates/chain/src/keychain/txout_index.rs [hunk 11]
```diff
@@ -158,13 +261,30 @@ impl<K: Clone + Ord + Debug> KeychainTxOutIndex<K> {
     ///
     /// This will panic if a different `descriptor` is introduced to the same `keychain`.
     pub fn add_keychain(&mut self, keychain: K, descriptor: Descriptor<DescriptorPublicKey>) {
-        let old_descriptor = &*self
-            .keychains
+        let descriptor_id = desc_checksum(&descriptor.to_string()).expect("Checksum can't fail");
```
Comment (LLFourn) [inline crates/chain/src/keychain/txout_index.rs]: I don't think we can assess the implications of having a non-collision-resistant descriptor id. I can imagine applications where this could be a disaster e.g. different descriptor per collaborative custody user where the user can influence the descriptor by choosing their key and grind for a collision with another user. I think we should use a sha256 hash of the string representation of the descriptor without checksum (I don't think there's a binary encoding for descriptors?).

Comment (ValuedMammal) [reply crates/chain/src/keychain/txout_index.rs]: +1

Comment (evanlinjin) [reply crates/chain/src/keychain/txout_index.rs]: What do you think about using RIPEMD-160? It's a smaller hash length (which is desirable here) and is already used for bitcoin addresses (so part of rust-bitcoin which is already a dependency).

File: crates/chain/src/keychain/txout_index.rs (hunk 8 above)
Comment (danielabrozzoni) [reply crates/chain/src/keychain/txout_index.rs]: Are there any real use cases for passing in a non-existent keychain? I can't think of any, and if that's the case, then passing in a non-existent keychain is a mistake, and mistakes should be reported explicitly to the user. I agree that panicking is a bit dramatic, it does make the API a bit cleaner compared than returning Result or Option (which I would be ok with, but it seems to me that we don't want to do that? I'm not sure why.)

In any case, we should be consistent across methods of the keychaintxout index, as currently the methods that return iterators return an empty one if you pass in a non-existent descriptor, while the others panic.

Comment (evanlinjin) [reply crates/chain/src/keychain/txout_index.rs]: I think it will make sense to return an `Option` if there is no descriptor under the keychain,.

File: crates/chain/src/keychain/txout_index.rs (hunk 11 above)
Comment (LLFourn) [reply crates/chain/src/keychain/txout_index.rs]: A shorter length is not desirable since that reduces the collision resistance. We either want collision resistance or we don't. If we do we should use the 128-bit security level (SHA256). Note collision resistance is not required for Bitcoin addresses in general -- at least not single user addresses.

File: crates/chain/src/keychain/txout_index.rs (hunk 7 above)
Comment (danielabrozzoni) [reply crates/chain/src/keychain/txout_index.rs]: As discussed in private, I'm changing this to:
```
keychains_to_descriptors: (keychain -> (desc, desc_id))
descriptor_ids_to_keychains: (desc_id -> keychain)
```

File: crates/chain/src/keychain/txout_index.rs (hunk 8 above)
Comment (danielabrozzoni) [reply crates/chain/src/keychain/txout_index.rs]: I realized it's better to leave it as is in this PR, and open an issue and discuss possible solutions there.

**Comment by danielabrozzoni** [comment]
In my last push:
- Rebase on master
- Fix (almost all the) review comments - I'm still missing a couple, will take a look soon
- `revealed_keychain_spks`, `unused_keychain_spks` `keychain_outpoints_in_range` and `keychain_outpoints` return an iterator, and would previously return an empty iterator if the keychain passed in didn't exist. The code is updated to instead panic if the keychain passed in doesn't exist. I was hoping to keep the same functionality in this PR, and maybe change the behavior in a new PR if we think it's the right choice (more here: bitcoindevkit/bdk#1340), but I can't really find a way to do so. Any suggestions? Should we take a decision on bitcoindevkit/bdk#1340 first, and then implement it here, or is it ok to merge and fix in a follow-up PR (hopefully before the release)?
- The new `KeychainTxOutIndex::add_keychain` always adds keychains, overwriting old descriptor/keychains when needed. This causes the (rather strange) behavior shown in `test_insert_different_desc_same_keychain`:
    - The index contains (K1, D1) and (K2, D2)
    - (K1, D2) is insterted
    - The index now contains (K1, D2) and (K2, D2)
I'm not sure if this is the behavior we want, or if instead, the index should only contain (K1, D2). From my understanding, since APIs never take in a DescriptorId, but always a Keychain, it shouldn't be a problem in any way.

File: crates/chain/src/keychain/txout_index.rs (hunk 9 above)
Comment (danielabrozzoni) [reply crates/chain/src/keychain/txout_index.rs]: > This should return a changeset.

Agreed. Can I open an issue for this? I think it should be easy to tackle for new contributors, is it ok if this is not fixed in this PR?

> Also, the new behavior should not panic when we replace a descriptor.

Yup, implemented, thanks

**Comment by ValuedMammal** [comment]
Maybe `KeychainTxOutIndex` should have its own Error enum, to catch mistakes early instead of returning results that don't make sense

File: crates/chain/tests/test_keychain_txout_index.rs [hunk 12]
```diff
@@ -44,29 +52,116 @@ fn spk_at_index(descriptor: &Descriptor<DescriptorPublicKey>, index: u32) -> Scr
...
+#[test]
+fn append_keychain_derivation_indices() {
+    let mut lhs_di = BTreeMap::<[u8; 8], u32>::default();
+    let mut rhs_di = BTreeMap::<[u8; 8], u32>::default();
+    lhs_di.insert(descriptor_ids(0), 7);
+    lhs_di.insert(descriptor_ids(1), 0);
+    rhs_di.insert(descriptor_ids(1), 3);
+    rhs_di.insert(descriptor_ids(1), 5);
+    lhs_di.insert(descriptor_ids(2), 3);
+    rhs_di.insert(descriptor_ids(3), 4);
```
Comment (notmandatory) [inline crates/chain/tests/test_keychain_txout_index.rs]: To match the below comments on the expected results this should be as below, also can removed the unneeded insert 3 for rhs_di for descriptor 1.
```suggestion
    lhs_di.insert(descriptor_ids(0), 7);
    lhs_di.insert(descriptor_ids(1), 0);
    lhs_di.insert(descriptor_ids(2), 3);
    
    rhs_di.insert(descriptor_ids(0), 3); // value less than lhs 0
    rhs_di.insert(descriptor_ids(1), 5); // value more than lhs 1
    rhs_di.insert(descriptor_ids(3), 4); // key doesn't exist in lhs
```

**Comment by danielabrozzoni** [comment]
@ValuedMammal I agree, but it seems to me that there aren't many methods in bdk_chain that return `Result`, and this seems a deliberate design choice? Also, "having an error-free API" was explicitly stated in the docs (which I had to remove in bitcoindevkit/bdk#1188, when I realized that some methods did return Results)

@LLFourn can you shed some light on this?

**Comment by ValuedMammal** [comment]
While returning `Option` is effectively the same as calling `next` on an empty iter, it would do a better job of informing the caller that the keychain doesn't exist - without introducing errors. You could use an if-let in places where `descriptor_of_keychain` is called and simply return `None` if the keychain isn't there.

File: crates/chain/src/keychain/txout_index.rs (hunk 11 above)
Comment (danielabrozzoni) [reply crates/chain/src/keychain/txout_index.rs]: Yup, makes sense, thanks for pointing this out. 

I'm having troubles hashing a `Descriptor<DescriptorPublicKey>`, has anyone ever tried doing so? It seems to me that `core::hash::Hash` is impl for a descriptor, but not `bitcoin::hashes::Hash` (https://docs.rs/miniscript/latest/miniscript/descriptor/enum.Descriptor.html#impl-Hash-for-Descriptor%3CPk%3E). Am I missing something?

Comment (ValuedMammal) [reply crates/chain/src/keychain/txout_index.rs]: use `to_string` and hash the descriptor string as bytes
```rust
    let data = <Vec<u8>>::from(descriptor.to_string().as_bytes());
    let descriptor_id = sha256::Hash::hash(&data);
```

File: crates/chain/src/keychain/txout_index.rs (hunk 9 above)
Comment (notmandatory) [reply crates/chain/src/keychain/txout_index.rs]: I took a try at returning a Result with an Err if trying to add a duplicate keychain or descriptor, otherwise returning an Ok ChangeSet. It shouldn't be that hard to do but I agree it's complicated enough to get it's own PR and there will be some decisions that will need to be discussed.

EDIT:

I created #1348 to take a stab at returning a `Result<ChangeSet<K>, AddKeychainError>`.

EDIT 2: 

I'm closing #1348 after reading @LLFourn 's latest comments. If there's no harm in replacing an existing keychain -> descriptor mapping then no need for the AddKeychainError.  Anyway I expect most wallets will only be adding new descriptors as they do key rotation, upgrade script types, etc.

File: crates/chain/src/keychain/txout_index.rs [hunk 13]
```diff
@@ -367,60 +525,70 @@ impl<K: Clone + Ord + Debug> KeychainTxOutIndex<K> {
...
-        self.keychains.keys().flat_map(|keychain| {
+        self.keychains_to_descriptors.keys().flat_map(|keychain| {
             self.revealed_keychain_spks(keychain)
                 .map(|(i, spk)| (keychain.clone(), i, spk))
         })
     }
 
     /// Iterate over revealed spks of the given `keychain`.
+    ///
+    /// # Panics
```
Comment (notmandatory) [inline crates/chain/src/keychain/txout_index.rs]: Is there really any way for this (and below functions) to panic? If the logic of `add_keychain()` is correct (which I think it is) there shouldn't be a way. The `.expect("Must exist")` lines should only fail during development and testing if someone breaks the logic.

**Review by notmandatory — DISMISSED** [review]
Looks good, I just have a couple questions/suggestions.

File: crates/chain/src/keychain/txout_index.rs [hunk 14]
```diff
@@ -170,26 +257,60 @@ impl<K> KeychainTxOutIndex<K> {
...
-        self.inner.outpoints()
+    pub fn outpoints(&self) -> BTreeSet<((K, u32), OutPoint)> {
+        self.inner
+            .outpoints()
+            .iter()
+            .map(|((desc_id, index), op)| {
+                (
+                    (
+                        self.keychain_of_descriptor_id(desc_id)
+                            .expect("Must be here")
```
Comment (evanlinjin) [inline crates/chain/src/keychain/txout_index.rs]: If the caller is no longer tracking the keychain `K`, the outpoint should not be returned.

File: crates/chain/src/keychain/txout_index.rs [hunk 15]
```diff
@@ -170,26 +257,60 @@ impl<K> KeychainTxOutIndex<K> {
...
     /// [struct-level docs](KeychainTxOutIndex) for more about `lookahead`.
-    pub fn inner(&self) -> &SpkTxOutIndex<(K, u32)> {
+    pub fn inner(&self) -> &SpkTxOutIndex<(DescriptorId, u32)> {
         &self.inner
     }
 
     /// Get a reference to the set of indexed outpoints.
-    pub fn outpoints(&self) -> &BTreeSet<((K, u32), OutPoint)> {
-        self.inner.outpoints()
+    pub fn outpoints(&self) -> BTreeSet<((K, u32), OutPoint)> {
```
Comment (evanlinjin) [inline crates/chain/src/keychain/txout_index.rs]: Maybe it's better we return an `impl Iterator` since we are already iterating anyway. This will give the caller more flexibility to collect into a collection of choice.

File: crates/chain/src/keychain/txout_index.rs [hunk 16]
```diff
@@ -170,26 +257,60 @@ impl<K> KeychainTxOutIndex<K> {
...
     pub fn txouts(
         &self,
     ) -> impl DoubleEndedIterator<Item = (K, u32, OutPoint, &TxOut)> + ExactSizeIterator {
-        self.inner
-            .txouts()
-            .map(|((k, i), op, txo)| (k.clone(), *i, op, txo))
+        self.inner.txouts().map(|((desc_id, i), op, txo)| {
+            (
+                self.keychain_of_descriptor_id(desc_id)
+                    .expect("Must be here")
```
Comment (evanlinjin) [inline crates/chain/src/keychain/txout_index.rs]: Same here, if the caller is not tracking the keychain, the txout should not be returned.

File: crates/chain/src/keychain/txout_index.rs [hunk 17]
```diff
@@ -199,7 +320,16 @@ impl<K: Clone + Ord + Debug> KeychainTxOutIndex<K> {
     ) -> impl DoubleEndedIterator<Item = (K, u32, OutPoint, &TxOut)> {
         self.inner
             .txouts_in_tx(txid)
-            .map(|((k, i), op, txo)| (k.clone(), *i, op, txo))
+            .map(|((desc_id, i), op, txo)| {
+                (
+                    self.keychain_of_descriptor_id(desc_id)
+                        .expect("Must be here")
```
Comment (evanlinjin) [inline crates/chain/src/keychain/txout_index.rs]: Here again.

File: crates/chain/src/keychain/txout_index.rs [hunk 18]
```diff
@@ -208,23 +338,34 @@ impl<K: Clone + Ord + Debug> KeychainTxOutIndex<K> {
...
     /// This calls [`SpkTxOutIndex::index_of_spk`] internally.
     pub fn index_of_spk(&self, script: &Script) -> Option<(K, u32)> {
-        self.inner.index_of_spk(script).cloned()
+        self.inner
+            .index_of_spk(script)
+            .cloned()
+            .map(|(desc_id, last_index)| {
+                (
+                    self.keychain_of_descriptor_id(&desc_id)
+                        .expect("must be here")
```
Comment (evanlinjin) [inline crates/chain/src/keychain/txout_index.rs]: Just return `None` because we may not have a corresponding keychain.

File: crates/chain/src/keychain/txout_index.rs (hunk 9 above)
Comment (evanlinjin) [reply crates/chain/src/keychain/txout_index.rs]: > Agreed. Can I open an issue for this? I think it should be easy to tackle for new contributors, is it ok if this is not fixed in this PR?

I'm against this because the main purpose of this PR is to be able to persist descriptors (albeit, with structures that aren't error-prone) and so descriptors SHOULD go in the changesets whenever added.

In terms of accidental replacing, I think we should have two methods; `add_keychain` and `add_or_replace_keychain`. `add_keychain` does not allow for replacing keychains and returns `Error<ChangeSet, {already-existing-keychain}>`.

File: crates/chain/src/keychain/txout_index.rs [hunk 19]
```diff
@@ -463,16 +632,39 @@ impl<K: Clone + Ord + Debug> KeychainTxOutIndex<K> {
...
     /// Keychains with no revealed indices will not be included in the returned [`BTreeMap`].
-    pub fn last_revealed_indices(&self) -> &BTreeMap<K, u32> {
-        &self.last_revealed
+    pub fn last_revealed_indices(&self) -> BTreeMap<K, u32> {
+        self.last_revealed
+            .iter()
+            .map(|(descriptor_id, index)| {
+                (
+                    self.keychain_of_descriptor_id(descriptor_id)
+                        .expect("Must be here")
```
Comment (evanlinjin) [inline crates/chain/src/keychain/txout_index.rs]: IF there is no corresponding keychain, just don't return it.

File: crates/chain/src/keychain/txout_index.rs [hunk 20]
```diff
@@ -367,60 +525,70 @@ impl<K: Clone + Ord + Debug> KeychainTxOutIndex<K> {
...
             self.unused_keychain_spks(keychain)
                 .map(|(i, spk)| (keychain.clone(), i, spk))
         })
     }
 
     /// Iterate over revealed, but unused, spks of the given `keychain`.
+    ///
+    /// # Panics
+    ///
+    /// This will panic if the given `keychain`'s descriptor does not exist.
```
Comment (evanlinjin) [inline crates/chain/src/keychain/txout_index.rs]: Thanks for adding this comment! Could you add a similar comment to `lookahead_to_target` as well?

I'm also thinking whether panicing when the keychain does not exist is the best move. @LLFourn what are your thoughts? I think in anycase, this can be tackled in a separate PR because this was already the old behavior.

**Review by evanlinjin — CHANGES_REQUESTED** [review]
Great work so far!

I think I may have confused you with some previous suggestions of mine. This is my fault, sorry for the confusion!

In general, we should not panic if `DescriptorId` does not have a corresponding `Keychain`. The lack of a corresponding `Keychain` means the caller does not want anything returned for the `Keychain` (for the time being). However, we should still continue to track that descriptor just in case the caller want's to re-introduce a `Keychain` for it!

For this reason, we need a separate `BTreeMap<DescriptorId, Descriptor>` field (as it were before I requested it be changed) which we should never delete from.

**Comment by notmandatory** [comment]
FYI I'm not including this PR in bitcoindevkit/bdk#1343, but looks like it will be ready for the next alpha release.

File: crates/chain/src/keychain/txout_index.rs [hunk 21]
```diff
@@ -170,26 +257,60 @@ impl<K> KeychainTxOutIndex<K> {
 
 /// Methods that are *re-exposed* from the internal [`SpkTxOutIndex`].
 impl<K: Clone + Ord + Debug> KeychainTxOutIndex<K> {
+    /// Returns the corresponding (descriptor_id, descriptor) given a keychain, if exists
+    fn descriptor_of_keychain(
+        &self,
+        keychain: &K,
+    ) -> Option<&(DescriptorId, Descriptor<DescriptorPublicKey>)> {
+        self.keychains_to_descriptors.get(keychain)
```
Comment (LLFourn) [inline crates/chain/src/keychain/txout_index.rs]: :pick: This method doesn't do anything. We can just call `keychains_to_descriptors.get(keychain)` wherever it's used and it will be clear what it does.

File: crates/chain/src/keychain/txout_index.rs [hunk 22]
```diff
@@ -170,26 +257,60 @@ impl<K> KeychainTxOutIndex<K> {
...
+    fn keychain_of_descriptor_id(&self, descriptor_id: &[u8; 8]) -> Option<&K> {
+        self.descriptor_ids_to_keychain.get(descriptor_id)
+    }
+
     /// Return a reference to the internal [`SpkTxOutIndex`].
     ///
     /// **WARNING:** The internal index will contain lookahead spks. Refer to
     /// [struct-level docs](KeychainTxOutIndex) for more about `lookahead`.
-    pub fn inner(&self) -> &SpkTxOutIndex<(K, u32)> {
+    pub fn inner(&self) -> &SpkTxOutIndex<(DescriptorId, u32)> {
```
Comment (LLFourn) [inline crates/chain/src/keychain/txout_index.rs:313]: :pushpin: It would be good if this method has an explanation as to why it is helpful rather than just to provide a footgun. I think the reason is maybe with compact block filters you might want to use *all* all the lookahead'd spks for the filters. But if that's the only reason then we could just provide a method to do just that and hide the `SpkTxOutIndex`.

I just did a wallet implementation with electrum and I didn't need this method once.

File: crates/chain/src/keychain/txout_index.rs (hunk 14 above)
Comment (LLFourn) [reply crates/chain/src/keychain/txout_index.rs]: Yes in the case that they have changed the descriptor for a keychain this should be ignored with a `filter_map`. Good catch.

File: crates/chain/src/keychain/txout_index.rs (hunk 9 above)
Comment (LLFourn) [reply crates/chain/src/keychain/txout_index.rs]: :wrench: +1 this must return a changeset otherwise this PR has little value.

I think we should keep it simple and just have one method with no error. I'd call it `insert_descriptor` and add a method `get_descriptor` (this seems to be missing). I don't see much risk in accidental replacement. With this PR you insert the descriptor once when you initialize the wallet and never again (you might add new descriptors under a new keychain variant). I'm not strongly against what @evanlinjin suggested but I feel like it's turning descriptor replacement into an explicit feature rather than just a artifact of the design. We may not want to support this feature going forward and have to think about "what about if you have replaced a descriptor" for every API or internal change.

File: crates/chain/src/keychain/txout_index.rs (hunk 20 above)
Comment (LLFourn) [reply crates/chain/src/keychain/txout_index.rs]: In this case we can avoid panicking because returning an empty iterator is fine. So we can just put a null `desc_id` in the range here and get an empty iterator.

**Comment by LLFourn** [comment]
> I would assume for the majority of cases, `K` is small (as an identifier) so cloning/copying would be cheaper than working with references. Therefore I prefer not having references on `K.

I think the rust-centric policy is if we don't want to enforce `K: Copy` then it should be `&K` must of the time. Unfortunately, I don't think we do want `K: Copy` so you can use `String` etc as keychains.

File: crates/chain/src/keychain/txout_index.rs [hunk 23]
```diff
@@ -666,7 +874,40 @@ impl<K: Clone + Ord + Debug> KeychainTxOutIndex<K> {
...
+                        .clone(),
+                    index,
+                )
+            })
+            .collect();
+        let _ = self.reveal_to_target_multi(&last_revealed);
+    }
+}
+
+fn calc_descriptor_id(desc: &Descriptor<DescriptorPublicKey>) -> DescriptorId {
```
Comment (LLFourn) [inline crates/chain/src/keychain/txout_index.rs]: :wrench: I think we should put this on `DescriptorExt` in `descriptor_ext.rs` as `descriptor_id()`. Since it's part of the public api you should be able to create one yourself.

File: crates/chain/src/keychain/txout_index.rs [hunk 24]
```diff
@@ -121,7 +196,12 @@ impl<K: Clone + Ord + Debug> Indexer for KeychainTxOutIndex<K> {
 
     fn index_txout(&mut self, outpoint: OutPoint, txout: &TxOut) -> Self::ChangeSet {
         match self.inner.scan_txout(outpoint, txout).cloned() {
-            Some((keychain, index)) => self.reveal_to_target(&keychain, index).1,
+            Some((keychain, index)) => {
+                let descriptor_id = self
```
Comment (LLFourn) [inline crates/chain/src/keychain/txout_index.rs]: :wrench: these variable names look backwards.

File: crates/chain/src/keychain/txout_index.rs [hunk 25]
```diff
@@ -121,7 +196,12 @@ impl<K: Clone + Ord + Debug> Indexer for KeychainTxOutIndex<K> {
...
+                    .keychain_of_descriptor_id(&keychain)
+                    .expect("Must be here");
```
Comment (LLFourn) [inline crates/chain/src/keychain/txout_index.rs]: :wrench: ignoring this is better than panicking. The user has said they don't care about this descriptor any more by replacing it.

**Review by LLFourn — COMMENTED** [review]
Thanks @danielabrozzoni! I've recently been using `KeychainTxOutIndex` directly in our project and I messed it up in most possible ways. I inserted a keychain after data was inserted and so found nothing. I also tried to query a keychain before I inserted it from persistence and so got a panic. Looking forward to having this PR fix this for me.

> @ValuedMammal I agree, but it seems to me that there aren't many methods in bdk_chain that return `Result`, and this seems a deliberate design choice? Also, "having an error-free API" was explicitly stated in the docs (which I had to remove in #1188, when I realized that some methods did return Results)
> 
> @LLFourn can you shed some light on this?

My experience above is an example of why -- it's better to panic when the programmer has made a mistake rather than returning some `Error` that gets pushed up to who knows where and often loses the backtrace. It's better not to have a panic or error at all if you can design the API to make invalid actions impossible.

We hadn't done a great job of making invalid actions on `KeychainTxOutIndex` impossible up until now. This was mostly because we had to rely on the user to re-insert the keychains at application start and they were very likely to forget that and so a panic was the way to tell them that. Now we are restoring the keychains automatically via `apply_changeset` I think we should try and fix all these panics.

The approach here is great. The remaining tasks I see are:

1. Remove panics. Although not all of them were introduced with this PR, we can solve most of them now.
2. Flesh out `DescriptorId` type. I think it should be `DescriptorId([u8;32])`. It should encode/decode to hex in `Display/FromStr/Debug` etc and human readable serde impls. I know this is a lot of tedious work. You can look to how rust-bitcoin does it with things like `Txid`. Hopefully they expose their hex decoder too. It would be no bother for me to just push a commit to "impl all the things" on DescriptorId by my [well worn but crazy macros](https://github.com/carol-computer/carol/blob/4041ce605c36c1e8158811272ec8c17394b919ed/crates/carol_core/src/macros.rs#L5) if that's acceptable.
3. Stop `Wallet::load` from taking descriptor arguments. They are stored in the DB now. This also removes some error variants I think in Wallet too I think. Would be good to have a test on this.

File: crates/chain/src/keychain/txout_index.rs (hunk 19 above)
Comment (notmandatory) [reply crates/chain/src/keychain/txout_index.rs:641]: I created #1348 to take a stab at returning a `Result<ChangeSet<K>, AddKeychainError>`.

**Comment by LLFourn** [comment]
BTW I had a go at doing an [emoji review](https://github.com/erikthedeveloper/code-review-emoji-guide) with this one. Let me know if it helps.

File: crates/chain/src/keychain/txout_index.rs (hunk 20 above)
Comment (danielabrozzoni) [reply crates/chain/src/keychain/txout_index.rs]: I don't think it's a good idea to return an empty iterator here. If the user passed in a non-existent keychain they probably want to know about it, and panicking is a really explicit way (probably too explicit!) of doing so, while returning an empty iterator is not explicit at all (in this particular case, not having any unused spks or passing in a wrong keychain yields the same exact result!)

File: crates/chain/src/keychain/txout_index.rs (hunk 22 above)
Comment (danielabrozzoni) [reply crates/chain/src/keychain/txout_index.rs:313]: Opened https://github.com/bitcoindevkit/bdk/issues/1353

File: crates/chain/src/keychain/txout_index.rs (hunk 20 above)
Comment (LLFourn) [reply crates/chain/src/keychain/txout_index.rs]: In my case I actually *don't* want to know about. Here's my current in-progress wallet architecture for frostsnap:

1. When we generate a new key we just insert it into the db (but not the `KeychainTxOutIndex`).
2. In general when the wallet gets queried forwards to the `IndexedTxGraph` / `LocalChain` and transforms it just like bdk's `Wallet`.
3. When the application needs a new address, we check whether we have already got the descriptor in the index, [otherwise we insert it](https://github.com/frostsnap/frostsnap/pull/113/files#diff-57f8639fc9052a85c8cff9c3d5ebe6f20e9a87105d759bb8996fba159acc3e21R218) by seeing if it exists in the database.

I don't think I should be forced to do this check-and-insert before every query to the `KeychainTxOutIndex`. If somehow my app queries `unused_keychain_spks` to the backend before calling an spk deriving method, It'd be much better for me if it just returned that there are no unused spks because that's the correct answer.

The new spk derivation methods do need the descriptor of course and we have to decide whether to panic or to error there. The answer depends on whether in all cases, making a new spk query without having inserted the descriptor represents a programmer error. It's hard to make this judgement for all contexts so it's probably better to indicate in the return type the possibility of the keychain's descriptor not existing. I guess an `Option` would be best for this.

File: crates/chain/src/keychain/txout_index.rs (hunk 22 above)
Comment (evanlinjin) [reply crates/chain/src/keychain/txout_index.rs:313]: Yes, I had CBF in mind for keeping this method. However, yes, maybe something like `all_spks_including_lookahead` (better named) satisfies all usecases.

File: crates/chain/src/keychain/txout_index.rs (hunk 10 above)
Comment (danielabrozzoni) [reply crates/chain/src/keychain/txout_index.rs]: Updated, I don't think we need a non-pub version of methods that takes descriptor_id as the code is kind of clean now already, what do you think?

**Comment by danielabrozzoni** [comment]
This is ready for another round :tada:


> BTW I had a go at doing an [emoji review](https://github.com/erikthedeveloper/code-review-emoji-guide) with this one. Let me know if it helps.

That was actually really helpful!

> Flesh out DescriptorId type. I think it should be DescriptorId([u8;32]). It should encode/decode to hex in Display/FromStr/Debug etc and human readable serde impls. 

@LLFourn I went with using https://docs.rs/bitcoin_hashes/0.13.0/bitcoin_hashes/macro.hash_newtype.html, so `DescriptorId` still contains `Hash` instead of `[u32;8]`, I guess that's also acceptable?

In my last push:
- Rebase
- Fix review comments
- Removed panics (we return `Option` basically everywhere now)
- Add `map_keychain` in `Wallet::unbounded_spk_iter` for consistency with other methods

File: crates/bdk/src/wallet/mod.rs [hunk 26]
```diff
@@ -342,6 +342,8 @@ pub enum LoadError<L> {
     MissingNetwork,
     /// Data loaded from persistence is missing genesis hash.
     MissingGenesis,
+    /// Data loaded from persistence is missing descriptor.
+    MissingDescriptor,
```
Comment (LLFourn) [inline crates/bdk/src/wallet/mod.rs:310]: :wrench: I think the docs for the `Descriptor` variant of the enum is no longer possible. The problem is with the persisted descriptors that were loaded.

Also maybe `LoadError::Load` should be `LoadError::Backend`.

File: crates/bdk/src/wallet/mod.rs [hunk 27]
```diff
@@ -553,27 +570,18 @@ impl<D> Wallet<D> {
     }
 
     /// Load [`Wallet`] from the given persistence backend.
-    pub fn load<E: IntoWalletDescriptor>(
-        descriptor: E,
-        change_descriptor: Option<E>,
-        mut db: D,
-    ) -> Result<Self, LoadError<D::LoadError>>
+    pub fn load(mut db: D) -> Result<Self, LoadError<D::LoadError>>
```
Comment (LLFourn) [inline crates/bdk/src/wallet/mod.rs]: :100: This makes it all worth it!

File: crates/chain/Cargo.toml [hunk 28]
```diff
@@ -28,4 +28,4 @@ rand = "0.8"
 [features]
 default = ["std"]
 std = ["bitcoin/std", "miniscript/std"]
-serde = ["serde_crate", "bitcoin/serde"]
+serde = ["serde_crate", "bitcoin/serde", "miniscript/serde"]
```
Comment (LLFourn) [inline crates/chain/Cargo.toml]: :wrench: I think this should be `miniscript?/serde` so we don't add miniscript as a dependency if we add serde (unless the user has explicitly added miniscript). The same is true for the `std` feature above. If you agree please  fix both of these.

See https://github.com/rust-lang/cargo/issues/8832. I think we have this now because we have a 1.63 as our MSRV.

File: crates/bdk/tests/wallet.rs [hunk 29]
```diff
@@ -161,14 +172,63 @@ fn new_or_load() {
...
             .expect("must recover wallet");
         assert_eq!(wallet.network(), Network::Testnet);
-        assert_eq!(wallet.keychains(), &wallet_keychains);
+        assert_eq!(
+            wallet
+                .keychains()
+                .map(|(k, v)| (*k, v.clone()))
+                .collect::<BTreeMap<_, _>>(),
+            wallet_keychains
+        );
```
Comment (LLFourn) [inline crates/bdk/tests/wallet.rs]: :pick: You could use [`Iterator::eq`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.eq) to do this a bit more erganomically (but you'd have to use `assert`).

File: crates/chain/src/keychain/txout_index.rs [hunk 30]
```diff
@@ -3,16 +3,95 @@ use crate::{
...
     ops::{Bound, RangeBounds},
 };
 
 use crate::Append;
 
+hash_newtype! {
+    /// Represents the ID of a descriptor, defined as the sha256 hash of
+    /// the descriptor string, checksum included.
+    pub struct DescriptorId(pub sha256::Hash);
+}
```
Comment (LLFourn) [inline crates/chain/src/keychain/txout_index.rs]: :100: Nice this is a better solution.

:pick: I'd feel more comfortable with this being defined in `descriptor_ext.rs` (but export it from root). It might get used elsewhere.

:pick: Explaining why this exists would be handy. We want a unique id for a descriptor with a fixed length since descriptors with taproot have no size bound. When we want to persist some application state change associated with the descriptor we don't want to re-write the whole descriptor each time.

:wrench: I think it'd be better if we did not include the checksum in the hash. Is it tricky to get the string representation without the checksum? I wonder if @apoelstra or @sanket1729 has an opinion on this point or the idea of a "descriptor id" in general. Maybe it could be upstreamed.

File: crates/chain/src/keychain/txout_index.rs [hunk 31]
```diff
@@ -292,29 +424,42 @@ impl<K: Clone + Ord + Debug> KeychainTxOutIndex<K> {
...
-            &descriptor, old_descriptor,
-            "keychain already contains a different descriptor"
-        );
+    /// When trying to add a keychain that already existed under a different descriptor, or a descriptor
+    /// that already existed with a different keychain, the old keychain (or descriptor) will be
+    /// overwritten.
+    pub fn insert_descriptor(
+        &mut self,
+        descriptor: Descriptor<DescriptorPublicKey>,
+        keychain: K,
```
Comment (LLFourn) [inline crates/chain/src/keychain/txout_index.rs:480]: :wrench: I think the keychain should be the first argument since it's kind of a key => value type of arrangement.

File: crates/chain/src/keychain/txout_index.rs [hunk 32]
```diff
@@ -292,29 +424,42 @@ impl<K: Clone + Ord + Debug> KeychainTxOutIndex<K> {
...
-        &self.keychains
+    /// Return the map of the keychain to descriptors.
+    pub fn keychains(&self) -> impl Iterator<Item = (&K, &Descriptor<DescriptorPublicKey>)> + '_ {
+        self.keychains_to_descriptors
+            .iter()
+            .map(|(k, (_, d))| (k, d))
     }
 
-    /// Add a keychain to the tracker's `txout_index` with a descriptor to derive addresses.
+    /// Insert a descriptor into the tracker's `txout_index`, with a keychain associated to it.
```
Comment (LLFourn) [inline crates/chain/src/keychain/txout_index.rs]: :camping: These docs still reference a "tracker" which is not something that has existed for a long time!

File: crates/chain/src/keychain/txout_index.rs [hunk 33]
```diff
@@ -330,98 +475,115 @@ impl<K: Clone + Ord + Debug> KeychainTxOutIndex<K> {
...
-        {
-            let _inserted = self
-                .inner
-                .insert_spk((keychain.clone(), new_index), new_spk);
-            debug_assert!(_inserted, "replenish lookahead: must not have existing spk: keychain={:?}, lookahead={}, next_store_index={}, next_reveal_index={}", keychain, lookahead, next_store_index, next_reveal_index);
+        let descriptor_opt = self.keychains_to_descriptors.get(keychain).cloned();
+        if let Some((descriptor_id, descriptor)) = descriptor_opt {
+            let next_store_index = self
+                .next_store_index(keychain)
+                .expect("We know keychain exists");
```
Comment (LLFourn) [inline crates/chain/src/keychain/txout_index.rs]: :wrench: this `expect` is tricky to reason about (involves multiple function jumps to verify the claim). I looked at all the `next_store_index` calls and I think they can just take a `DescriptorId` as an argument which would allow us not to return an `Option`.

File: crates/chain/src/keychain/txout_index.rs [hunk 34]
```diff
@@ -330,98 +475,115 @@ impl<K: Clone + Ord + Debug> KeychainTxOutIndex<K> {
...
     pub fn revealed_keychain_spks(
         &self,
         keychain: &K,
-    ) -> impl DoubleEndedIterator<Item = (u32, &Script)> + Clone {
-        let next_i = self.last_revealed.get(keychain).map_or(0, |&i| i + 1);
-        self.inner
-            .all_spks()
-            .range((keychain.clone(), u32::MIN)..(keychain.clone(), next_i))
-            .map(|((_, i), spk)| (*i, spk.as_script()))
+    ) -> Option<impl DoubleEndedIterator<Item = (u32, &Script)> + Clone> {
```
Comment (LLFourn) [inline crates/chain/src/keychain/txout_index.rs]: :question: What's your opinion on https://github.com/bitcoindevkit/bdk/pull/1203#discussion_r1495082281 ? I still think that this should just be an empty iterator -- it's more ergonomic and technically the right answer.

**Review by LLFourn — DISMISSED** [review]
Thanks this looks almost ready. It's great that `rust-bitcoin` re-exports the macros to easily spin up the hash type!

File: crates/chain/src/keychain/txout_index.rs [hunk 35]
```diff
@@ -505,84 +674,89 @@ impl<K: Clone + Ord + Debug> KeychainTxOutIndex<K> {
...
     ///
     /// Returns the derivation index of the revealed script pubkey, the revealed script pubkey and a
     /// [`super::ChangeSet`] which represents changes in the last revealed index (if any).
+    /// Returns None if the provided keychain doesn't exist.
     ///
     /// When a new script cannot be revealed, we return the last revealed script and an empty
     /// [`super::ChangeSet`]. There are two scenarios when a new script pubkey cannot be derived:
     ///
     ///  1. The descriptor has no wildcard and already has one script revealed.
     ///  2. The descriptor has already revealed scripts up to the numeric bound.
```
Comment (evanlinjin) [inline crates/chain/src/keychain/txout_index.rs:833]: We need to add 1 more scenario. When there is no descriptor under the given keychain.

File: crates/bdk/src/wallet/mod.rs [hunk 36]
```diff
@@ -2551,13 +2605,13 @@ fn create_signers<E: IntoWalletDescriptor>(
 ) -> Result<(Arc<SignersContainer>, Arc<SignersContainer>), crate::descriptor::error::Error> {
     let (descriptor, keymap) = into_wallet_descriptor_checked(descriptor, secp, network)?;
     let signers = Arc::new(SignersContainer::build(keymap, &descriptor, secp));
-    index.add_keychain(KeychainKind::External, descriptor);
+    let _ = index.insert_descriptor(descriptor, KeychainKind::External);
```
Comment (evanlinjin) [inline crates/bdk/src/wallet/mod.rs]: Nit: For consistency, it will be nice to have `create_signers` return the aggregate changeset (instead of calling `initial_changeset` later on).

File: crates/bdk/src/wallet/mod.rs (hunk 26 above)
Comment (evanlinjin) [reply crates/bdk/src/wallet/mod.rs:310]: @LLFourn can you expand on what you mean that this isn't possible? `Wallet` still expects a descriptor under the `KeychainKind::External` keychain right?

File: crates/chain/src/keychain/txout_index.rs (hunk 30 above)
Comment (notmandatory) [reply crates/chain/src/keychain/txout_index.rs]: ❓ @LLFourn I'm curious why you want to exclude the checksum from the descriptor string hashed for `DescriptorId`. It's easy to remove the checksum by splitting the descriptor string on the `#` but I don't see any reason to do it.

**Review by evanlinjin — COMMENTED** [review]
I need to finish this review, but here as some thoughts.

File: crates/chain/src/keychain/txout_index.rs (hunk 30 above)
Comment (evanlinjin) [reply crates/chain/src/keychain/txout_index.rs]: @notmandatory I think it's easier to reason about. It's odd to hash a checksum and the checksum is not mandatory for a miniscript descriptor so we should have some standard as to how to come up with a unique identifier for a descriptor (so might as well remove the checksum for this as opposed to keeping it to generate the unique identifier).

File: crates/chain/src/keychain/txout_index.rs [hunk 37]
```diff
@@ -3,16 +3,95 @@ use crate::{
...
+                *descriptor = other_descriptor;
+            }
+        }
+
+        for (descriptor_id, index) in &mut self.last_revealed {
+            if let Some(other_index) = other.last_revealed.remove(descriptor_id) {
+                *index = other_index.max(*index);
+            }
+        }
+
```
Comment (evanlinjin) [inline crates/chain/src/keychain/txout_index.rs]: I don't think we need this. `::extend` already makes elements of `other` take precedence.

Edit: Okay, I'm wrong. We still don't need this loop for `keychains_added`, but we still need it for `last_revealed`.

File: crates/chain/src/keychain/txout_index.rs [hunk 38]
```diff
@@ -121,7 +202,15 @@ impl<K: Clone + Ord + Debug> Indexer for KeychainTxOutIndex<K> {
...
         match self.inner.scan_txout(outpoint, txout).cloned() {
-            Some((keychain, index)) => self.reveal_to_target(&keychain, index).1,
+            Some((descriptor_id, index)) => {
+                if let Some(keychain) = self.keychain_of_descriptor_id(&descriptor_id) {
+                    self.reveal_to_target(&keychain.clone(), index)
+                        .expect("We know keychain exists")
+                        .1
+                } else {
+                    super::ChangeSet::default()
+                }
```
Comment (evanlinjin) [inline crates/chain/src/keychain/txout_index.rs]: We also want to reveal spks for descriptors without keychains. It's probably handy to create a non-public `reveal_to_target` method that takes in `DescriptorId` instead.

File: crates/chain/src/keychain/txout_index.rs [hunk 39]
```diff
@@ -199,7 +313,10 @@ impl<K: Clone + Ord + Debug> KeychainTxOutIndex<K> {
...
         self.inner
             .txouts_in_tx(txid)
-            .map(|((k, i), op, txo)| (k.clone(), *i, op, txo))
+            .filter_map(|((desc_id, i), op, txo)| {
+                self.keychain_of_descriptor_id(desc_id)
+                    .map(|k| (k.clone(), *i, op, txo))
+            })
     }
 
     /// Return the [`TxOut`] of `outpoint` if it has been indexed.
```
Comment (evanlinjin) [inline crates/chain/src/keychain/txout_index.rs]: We need to update the docs to say that we will only return if the descriptor has corresponding keychain id (somehow).

**Review by evanlinjin — CHANGES_REQUESTED** [review]
Sorry I'm doing reviews in sections.

File: crates/chain/Cargo.toml (hunk 28 above)
Comment (evanlinjin) [reply crates/chain/Cargo.toml]: I didn't know this was a feature. Very cool.

File: crates/chain/src/keychain/txout_index.rs [hunk 40]
```diff
@@ -170,26 +266,44 @@ impl<K> KeychainTxOutIndex<K> {
...
+        &self,
+        keychain: &K,
+    ) -> Option<&(DescriptorId, Descriptor<DescriptorPublicKey>)> {
+        self.keychains_to_descriptors.get(keychain)
+    }
+
+    /// Returns the corresponding keychain given a descriptor id, if exists
+    fn keychain_of_descriptor_id(&self, descriptor_id: &DescriptorId) -> Option<&K> {
+        self.descriptor_ids_to_keychain.get(descriptor_id)
+    }
```
Comment (evanlinjin) [inline crates/chain/src/keychain/txout_index.rs]: Nit: This method does not do much. I think it's better if we use `descriptor_ids_to_keychain.get` directly.

File: crates/chain/src/keychain/txout_index.rs [hunk 41]
```diff
@@ -170,26 +266,44 @@ impl<K> KeychainTxOutIndex<K> {
...
     /// [struct-level docs](KeychainTxOutIndex) for more about `lookahead`.
-    pub fn inner(&self) -> &SpkTxOutIndex<(K, u32)> {
+    pub fn inner(&self) -> &SpkTxOutIndex<(DescriptorId, u32)> {
         &self.inner
     }
 
-    /// Get a reference to the set of indexed outpoints.
-    pub fn outpoints(&self) -> &BTreeSet<((K, u32), OutPoint)> {
-        self.inner.outpoints()
+    /// Get the set of indexed outpoints.
```
Comment (evanlinjin) [inline crates/chain/src/keychain/txout_index.rs]: I think we should take a note that we only return outpoints for descriptors with a corresponding keychain id. Maybe something like:

```
/// Get outpoints indexed against spks of tracked keychains.
```

I think we can also return `impl DoubleEndedIterator< ... >`

File: crates/chain/src/keychain/txout_index.rs [hunk 42]
```diff
@@ -252,7 +376,11 @@ impl<K: Clone + Ord + Debug> KeychainTxOutIndex<K> {
     ///
     /// [`unmark_used`]: Self::unmark_used
     pub fn mark_used(&mut self, keychain: K, index: u32) -> bool {
```
Comment (evanlinjin) [inline crates/chain/src/keychain/txout_index.rs:408]: We should probably update the docs for this:

```rust
/// Returns whether the spk under the given `keychain` and `index` is successfully
/// marked as used. Returns false either when there is no descriptor under the given
/// keychain, or when the spk is already marked as used.

File: crates/chain/src/keychain/txout_index.rs [hunk 43]
```diff
@@ -292,29 +424,42 @@ impl<K: Clone + Ord + Debug> KeychainTxOutIndex<K> {
 }
 
 impl<K: Clone + Ord + Debug> KeychainTxOutIndex<K> {
-    /// Return a reference to the internal map of keychain to descriptors.
-    pub fn keychains(&self) -> &BTreeMap<K, Descriptor<DescriptorPublicKey>> {
-        &self.keychains
+    /// Return the map of the keychain to descriptors.
+    pub fn keychains(&self) -> impl Iterator<Item = (&K, &Descriptor<DescriptorPublicKey>)> + '_ {
```
Comment (evanlinjin) [inline crates/chain/src/keychain/txout_index.rs]: Lets make this a `DoubleEndedIterator + ExactSizeIterator`

File: crates/chain/src/keychain/txout_index.rs [hunk 44]
```diff
@@ -292,29 +424,42 @@ impl<K: Clone + Ord + Debug> KeychainTxOutIndex<K> {
...
+        let descriptor_id = descriptor.descriptor_id();
+        self.keychains_to_descriptors
+            .insert(keychain.clone(), (descriptor_id, descriptor.clone()));
+        self.descriptor_ids_to_keychain
+            .insert(descriptor_id, keychain.clone());
         self.replenish_lookahead(&keychain, self.lookahead);
+        super::ChangeSet {
+            keychains_added: [(keychain, descriptor)].into(),
+            last_revealed: [].into(),
+        }
```
Comment (evanlinjin) [inline crates/chain/src/keychain/txout_index.rs]: This is wrong, we should return an empty changeset if we already have the same descriptor under the keychain.

File: crates/chain/src/keychain/txout_index.rs (hunk 37 above)
Comment (evanlinjin) [reply crates/chain/src/keychain/txout_index.rs]: For updating `last_revealed`, I think it's better to just loop through `other.last_revealed` and get rid of the call to `self.last_revealed.extend`.

**Review by evanlinjin — CHANGES_REQUESTED** [review]

File: crates/chain/tests/test_keychain_txout_index.rs [hunk 45]
```diff
@@ -44,29 +52,133 @@ fn spk_at_index(descriptor: &Descriptor<DescriptorPublicKey>, index: u32) -> Scr
         .script_pubkey()
 }
 
+#[test]
+fn append_keychain_derivation_indices() {
```
Comment (evanlinjin) [inline crates/chain/tests/test_keychain_txout_index.rs]: Nit: I found it hard to figure out what this test did based on the name. What do you think about this?

```suggestion
fn append_changesets_check_last_revealed() {
```

Also, I think it will help if we had a short doc-comment explaining the test as well.

File: crates/chain/tests/test_keychain_txout_index.rs [hunk 46]
```diff
@@ -44,29 +52,133 @@ fn spk_at_index(descriptor: &Descriptor<DescriptorPublicKey>, index: u32) -> Scr
...
+    // Existing index updates if the new index in `other` is higher than `self`.
+    assert_eq!(lhs.last_revealed.get(&descriptor_ids[1]), Some(&5));
+    // Existing index is unchanged if keychain doesn't exist in `other`.
+    assert_eq!(lhs.last_revealed.get(&descriptor_ids[2]), Some(&3));
+    // New keychain gets added if the keychain is in `other` but not in `self`.
+    assert_eq!(lhs.last_revealed.get(&descriptor_ids[3]), Some(&4));
+}
+
+#[test]
+fn test_insert_different_desc_same_keychain() {
```
Comment (evanlinjin) [inline crates/chain/tests/test_keychain_txout_index.rs]: Based on this test's name, I thought this was testing `insert_descriptor` but `apply_changeset` was tested instead.

I'm thinking whether we should set a test-naming policy to start each test name with the method that we are testing. So in this case, the name would be something like: `apply_changeset_with_different_descriptors_to_same_keychain`.

File: crates/chain/tests/test_keychain_txout_index.rs [hunk 47]
```diff
@@ -5,36 +5,44 @@ mod common;
...
-) -> (
-    bdk_chain::keychain::KeychainTxOutIndex<TestKeychain>,
-    Descriptor<DescriptorPublicKey>,
-    Descriptor<DescriptorPublicKey>,
-) {
+struct TestIndex {
+    index: bdk_chain::keychain::KeychainTxOutIndex<TestKeychain>,
+    external_descriptor: Descriptor<DescriptorPublicKey>,
+    internal_descriptor: Descriptor<DescriptorPublicKey>,
+}
```
Comment (evanlinjin) [inline crates/chain/tests/test_keychain_txout_index.rs]: Nit: Personal taste here, but I don't think adding this struct helped the readability of the tests.

File: crates/chain/tests/test_keychain_txout_index.rs [hunk 48]
```diff
@@ -5,36 +5,44 @@ mod common;
...
+
+fn init_txout_index(lookahead: u32) -> TestIndex {
```
Comment (evanlinjin) [inline crates/chain/tests/test_keychain_txout_index.rs]: An idea would be to have this method take in the two descriptors as `&str`s. This will give the method more flexibility (we can use it with `DESCRIPTORS`) and we only need to return the `KeychainTxOutIndex`. What do you think?

File: crates/bdk/src/wallet/mod.rs (hunk 26 above)
Comment (danielabrozzoni) [reply crates/bdk/src/wallet/mod.rs:310]: @evanlinjin I think the problem is that we return `LoadError::Descriptor` if `into_wallet_descriptor_checked` (in `create_signers`) fails, but it can never fail since we're recovering the descriptors from the changeset.

File: crates/chain/src/keychain/txout_index.rs (hunk 30 above)
Comment (notmandatory) [reply crates/chain/src/keychain/txout_index.rs]: Ok that makes sense. But the `descriptor_id()` function should already normalizes optional features (including using ' or h and root keys paths) by hashing the `to_string()` of the Descriptor type. But I don't want to bike shed this too much, it's fine for me either way as long as it's done in the `descriptor_id()` function and we use that everywhere.

File: crates/chain/src/keychain/txout_index.rs [hunk 49]
```diff
@@ -292,29 +424,42 @@ impl<K: Clone + Ord + Debug> KeychainTxOutIndex<K> {
...
+    /// that already existed with a different keychain, the old keychain (or descriptor) will be
+    /// overwritten.
+    pub fn insert_descriptor(
+        &mut self,
+        descriptor: Descriptor<DescriptorPublicKey>,
+        keychain: K,
+    ) -> super::ChangeSet<K> {
+        let descriptor_id = descriptor.descriptor_id();
+        self.keychains_to_descriptors
+            .insert(keychain.clone(), (descriptor_id, descriptor.clone()));
```
Comment (evanlinjin) [inline crates/chain/src/keychain/txout_index.rs]:
```suggestion
        let old_desc = self.keychains_to_descriptors
            .insert(keychain.clone(), (descriptor_id, descriptor.clone()));
        if let Some((old_desc_id, _)) = old_desc {
            self.descriptor_ids_to_keychain.remove(&old_desc_id);
        }

```

This is wrong. I think we should add a test for this. I.e. something to do with swapping descriptors for a given keychain and then attempting to index transactions.

**Review by evanlinjin — CHANGES_REQUESTED** [review]

File: crates/chain/tests/test_keychain_txout_index.rs (hunk 48 above)
Comment (danielabrozzoni) [reply crates/chain/tests/test_keychain_txout_index.rs]: What if you need the `Descriptor`s instead of the `&str` outside of init_txout_index, you'd have to re-parse them yourself? 😅

File: crates/chain/tests/test_keychain_txout_index.rs (hunk 47 above)
Comment (danielabrozzoni) [reply crates/chain/tests/test_keychain_txout_index.rs]: I think having a struct is better than having a tuple. Returning only the index maybe was more readable, but then you'd have to calculate the desc_ids by yourself when needed

File: crates/chain/src/keychain/txout_index.rs (hunk 40 above)
Comment (danielabrozzoni) [reply crates/chain/src/keychain/txout_index.rs]: Ouch, lloyd also pointed  that out, i resolved the conversation and somehow forgot to update the code 🤦🏻‍♀️  I'm sorry, should be good now

File: crates/bdk/src/wallet/mod.rs (hunk 26 above)
Comment (LLFourn) [reply crates/bdk/src/wallet/mod.rs:310]: @evanlinjin I think i was just mentioning that the docs for descriptor were stale. "There was a problem with the passed-in descriptor(s)." You don't pass them in now. Looks fixed now thanks @danielabrozzoni.

File: crates/chain/src/keychain/txout_index.rs (hunk 34 above)
Comment (danielabrozzoni) [reply crates/chain/src/keychain/txout_index.rs]: I am very torn here.
On one hand - of course, returning an Option is not ergonomic at all, and that's mostly the reason why I decided to panic at first. And I agree that returning an empty iterator is technically the right answer, but at the same time I wonder how many users will want to know that they've asked for a keychain we don't have vs how many don't care (and if you don't care but we tell you, it's easy to just discard the option, even though your code becomes not_so_clean, vs if you do care and we don't tell you, that's a problem).

An example comes to my mind: our `Wallet::sign` doesn't return any Error if you don't have a private key, it just returns back the transaction unsigned. I'm not advocating for changing this - but we had many users just telling us "there's a bug! I call `sign` and nothing happens!" because our technically right answer didn't communicate what was going on underneath ("we tried to sign your transaction but we simply don't have a private key").

Now, it doesn't mean that we need to solve this in code - maybe decent docs are enough for this?

I don't like the Options either, and that's mostly why I pushed a separate commit for the panic -> option change, so that I could simply remove it if we decide that's not the right way to go. I can remove the option from the methods that return an iterator, leave it everywhere else, and document clearly that if your keychain isn't inserted the returned iterator is going to be empty. If we realize that this confuses our users, we can always re-introduce the option in a later version.

File: crates/chain/src/keychain/txout_index.rs (hunk 10 above)
Comment (danielabrozzoni) [reply crates/chain/src/keychain/txout_index.rs]: Mhh. Actually, reveal_to_target is called in a couple of places where I had the descriptor_id available, and instead I'm calling it with the keychain and expecting on the result, so `reveal_to_target_with_id` would be clean. At the same time, reveal_to_target needs both the desc_id and the descriptor, and at the moment we don't have a quick way of returning a descriptor given the id.
What do you think it's better:
1. Leave the code as is
2. Create a desc_id -> desc map (we could also have a public method returning this info?)
3. Change the descriptor_ids_to_keychains to be (desc_id -> (desc, keychain)) instead of (desc_id -> keychain). Makes the code way less readable imho, as we need to call `.1` almost everywhere to only retrieve the keychain 

I'm thinking 2 but what do you think?

File: crates/chain/src/keychain/txout_index.rs (hunk 38 above)
Comment (danielabrozzoni) [reply crates/chain/src/keychain/txout_index.rs]: > We also want to reveal spks for descriptors without keychains.

I don't understand why this is needed. 

Regarding the reveal_to_target with desc_id: I agree,  what do you think about this? https://github.com/bitcoindevkit/bdk/pull/1203#discussion_r1516020519

File: crates/chain/src/keychain/txout_index.rs (hunk 30 above)
Comment (danielabrozzoni) [reply crates/chain/src/keychain/txout_index.rs]: I agree that it's odd to use the hash of the descriptor with the checksum included. I addressed everything in 477c4a0a201296d88b5dcc669bef6b69ecb6e3bb

File: crates/chain/tests/test_keychain_txout_index.rs (hunk 48 above)
Comment (evanlinjin) [reply crates/chain/tests/test_keychain_txout_index.rs]: Then we can use `Descriptor` as the input type.

File: crates/chain/src/keychain/txout_index.rs (hunk 38 above)
Comment (evanlinjin) [reply crates/chain/src/keychain/txout_index.rs]: We still want to maintain revealed/lookahead indices for tracked descriptors without keychains. I understand that these will not be returned to the caller (because they do not have keychains assigned). However, revealed/lookahead indices play a key part in discovering relevant txs/txouts. This method here is indexing txs/txouts and we need to replenish our spks afterwards (even for descriptors without keychains). Note that descriptors is added in a monotone manner, but keychains can be assigned/unassigned freely. A descriptor may have a keychain one moment and not have it in another. We should make tx/txout scanning consistent between ALL tracked descriptors.

File: crates/chain/tests/test_keychain_txout_index.rs (hunk 48 above)
Comment (danielabrozzoni) [reply crates/chain/tests/test_keychain_txout_index.rs]: Then every call to `init_txout_index` would look like this:
```rust
let secp = bdk_chain::bitcoin::secp256k1::Secp256k1::signing_only();
let (external_descriptor, _) =
   Descriptor::<DescriptorPublicKey>::parse_descriptor(&secp, DESCRIPTORS[0]).unwrap();
let (internal_descriptor, _) =
   Descriptor::<DescriptorPublicKey>::parse_descriptor(&secp, DESCRIPTORS[1]).unwrap();
let index = init_txout_index(lookahead, external_desc, internal_desc);
```

Is it really worth it? I don't think so.

File: crates/chain/src/descriptor_ext.rs [hunk 50]
```diff
@@ -1,10 +1,28 @@
...
+
+hash_newtype! {
+    /// Represents the ID of a descriptor, defined as the sha256 hash of
+    /// the descriptor string, checksum excluded.
+    ///
+    /// This is useful for having a fixed-length unique representation of a descriptor,
+    /// in particular, we use it to persist application state changes related to the
+    /// descriptor without having to re-write the whole descriptor each time.
+    ///
+    pub struct DescriptorId(pub sha256::Hash);
```
Comment (ValuedMammal) [inline crates/chain/src/descriptor_ext.rs:15]: Brilliant.

**Comment by notmandatory** [comment]
Reviewers please specify for any outstanding suggestions if they are a nit ⛏️ , can be fixed later 📌  or must fix 🔧  concern. This PR is five months  old and we need to wrap it up!

**Comment by evanlinjin** [comment]
Everything that I have not specified as a nit, or asked as a question needs to be fixed now.

File: crates/chain/src/keychain/txout_index.rs [hunk 51]
```diff
@@ -13,6 +13,76 @@ use core::{
...
+        bound(
+            deserialize = "K: Ord + serde::Deserialize<'de>",
+            serialize = "K: Ord + serde::Serialize"
+        )
+    )
+)]
+#[must_use]
+pub struct ChangeSet<K> {
+    /// Contains the keychains that have been added and their respective descriptor
+    pub keychains_added: BTreeMap<K, Descriptor<DescriptorPublicKey>>,
```
Comment (notmandatory) [inline crates/chain/src/keychain/txout_index.rs:39]: I've ran into a problem testing this PR with the `wallet_esplora_async` test. When it reloads this `ChangeSet` since `keychains_added` is a `Descriptor<DescriptorPublicKey>>` I'm not able to sign any transactions. Am I supposed to manually add privkey signers to my `Wallet` or something like that ? Or do we need a way to store the private key descriptors in the db?

Comment (evanlinjin) [reply crates/chain/src/keychain/txout_index.rs:39]: Definitely not store privkey in db imo. Maybe have an option to load privkey when constructing wallet.

Comment (LLFourn) [reply crates/chain/src/keychain/txout_index.rs:39]: This is a good point. I don't think we considered the impact on private descriptors to `Wallet` when designing this change which was an oversight. Yes you're meant to manually add them and I expect this is quite difficult. In the long term we should be looking to remove the signers from `Wallet` but we probably need a design that makes it easy to add the keys from private descriptors to the Wallet for now before merging this.

Comment (notmandatory) [reply crates/chain/src/keychain/txout_index.rs:39]: Ok, it's not too hard to manually add the signers, but will need to update the examples and docs. 

📌 We could make this easier by adding a function to add a whole `SignerContainer` or in `Wallet::new_or_load` add the signers if a `Descriptor<DescriptorSecretKey>` is passed in. 

Here's my quick examples workaround:

```rust
    let secp = Secp256k1::new();

    let (external_descriptor, external_keymap) = Descriptor::parse_descriptor(&secp, "wpkh(tprv8ZgxMBicQKsPdy6LMhUtFHAgpocR8GC6QmwMSFpZs7h6Eziw3SpThFfczTDh5rW2krkqffa11UpX3XkeTTB2FvzZKWXqPY54Y6Rq4AQ5R8L/84'/1'/0'/0/*)").unwrap();
    let (internal_descriptor, internal_keymap) = Descriptor::parse_descriptor(&secp, "wpkh(tprv8ZgxMBicQKsPdy6LMhUtFHAgpocR8GC6QmwMSFpZs7h6Eziw3SpThFfczTDh5rW2krkqffa11UpX3XkeTTB2FvzZKWXqPY54Y6Rq4AQ5R8L/84'/1'/0'/1/*)").unwrap();

    let external_signer_container = SignersContainer::build(external_keymap, &external_descriptor, &secp);
    let internal_signer_container = SignersContainer::build(internal_keymap, &internal_descriptor, &secp);
    
    let mut wallet = Wallet::new_or_load(
        external_descriptor,
        Some(internal_descriptor),
        db,
        Signet,
    )?;
    
    external_signer_container.signers().into_iter()
        .for_each(|s| wallet.add_signer(KeychainKind::External, SignerOrdering::default(), s.clone()));
    internal_signer_container.signers().into_iter()
        .for_each(|s| wallet.add_signer(KeychainKind::Internal, SignerOrdering::default(), s.clone()));
```

Comment (notmandatory) [reply crates/chain/src/keychain/txout_index.rs:39]: I added code in the wallet to add the expected descriptor keys as signers and I think it's a pretty clean way to do it: https://github.com/bitcoindevkit/bdk/pull/1128/commits/c053f1940013987bdf0902c41f074158eaafabad.

**Comment by evanlinjin** [comment]
@danielabrozzoni let me know if you need a hand with this

File: crates/bdk/src/wallet/mod.rs (hunk 36 above)
Comment (danielabrozzoni) [reply crates/bdk/src/wallet/mod.rs]: It would be but then in `Wallet::load_from_changeset` we'd probably discard the changeset. Anyways, I'm opening a good first issue for this!

**Comment by danielabrozzoni** [comment]
@evanlinjin thanks! Right now I'm going through comments and updating/replying, I'll let you know if I need anything :)

File: crates/chain/tests/test_keychain_txout_index.rs (hunk 46 above)
Comment (danielabrozzoni) [reply crates/chain/tests/test_keychain_txout_index.rs]: I agree that the new name is better! I'm not sure if it's worth it to have a strict test-naming policy, but "don't name a test with a method you aren't even using" is certainly a good policy to implement 😂

File: crates/chain/src/keychain/txout_index.rs (hunk 34 above)
Comment (notmandatory) [reply crates/chain/src/keychain/txout_index.rs]: Hey @danielabrozzoni  I think you answered your own questions here, which is to return an empty iterator, the technically right way, but clearly document the behavior. For these internal chain crate APIs I think it's ok to lean in favor of technically right and avoiding panics. Anyone using the chain crate should be more sophisticated than our `wallet` API users who would need more explicit return values.

File: crates/chain/src/keychain/txout_index.rs (hunk 10 above)
Comment (evanlinjin) [reply crates/chain/src/keychain/txout_index.rs]: I'm actually in favor of 3. Instead of `.1`, we can have `let (_, keychain) = self.descriptor_ids_to_keychain.get(something)`. I think having less fields makes it easier to maintain and reason about.

However, I would be fine with 1 or 2 (although I would prefer 1 over 2).

File: crates/chain/src/keychain/txout_index.rs (hunk 34 above)
Comment (evanlinjin) [reply crates/chain/src/keychain/txout_index.rs]: Unlike @notmandatory, I'm leaning technically left (just joking).

In all seriousness, I think returning an empty iterator makes sense as it is the correct answer. Returning `Option` also makes sense and can be somewhat ergonomic (`opt.iter().flatten()`). I'm leaning towards returning the Option as it conveys more information.

File: crates/chain/tests/test_keychain_txout_index.rs (hunk 48 above)
Comment (evanlinjin) [reply crates/chain/tests/test_keychain_txout_index.rs]: Add another helper method to parse descriptor?

File: crates/chain/src/keychain/txout_index.rs (hunk 34 above)
Comment (danielabrozzoni) [reply crates/chain/src/keychain/txout_index.rs]: I really need to decide what to do here before rebasing, since I need to rebase on top of https://github.com/bitcoindevkit/bdk/commit/fac228337c79e1a7c406500c177e049e7f9f5da7 and I don't want to redo the rebase.

Returning an empty iterator is the easiest solution to implement, so I'll go with that for now, and open an issue to track the fact that some of us liked the option better. We can always switch to option in a subsequent pr.

File: crates/chain/src/keychain/txout_index.rs (hunk 37 above)
Comment (danielabrozzoni) [reply crates/chain/src/keychain/txout_index.rs]: Can you explain why?

File: crates/chain/src/keychain/txout_index.rs (hunk 49 above)
Comment (danielabrozzoni) [reply crates/chain/src/keychain/txout_index.rs]: Next time, can you expand a bit on why it's wrong? It took me half an hour to reload the context of the whole conversation, find our DMs and https://github.com/danielabrozzoni/bdk/pull/6/commits/8229a082c9de879abc3ba5b1e3540d34f0641471 😅

**Comment by danielabrozzoni** [comment]
My last push includes a rebase and a fix for almost all the review comments.

Left to do:
- https://github.com/bitcoindevkit/bdk/pull/1203#discussion_r1510281852 I need some input from @evanlinjin, I don't understand why this is needed/better
- https://github.com/bitcoindevkit/bdk/pull/1203#discussion_r1510207238 @evanlinjin I ported your tests from https://github.com/danielabrozzoni/bdk/pull/6/commits/8229a082c9de879abc3ba5b1e3540d34f0641471, but I realized the only way for them to pass is to add a `desc_id -> desc` map, which I know you're not a fan of. The reason for this is that `reveal_to_target_with_id` needs to know the descriptor given the desc_id, which we don't know if the keychain isn't present (we clean `self.descriptor_ids_to_keychain` in `insert_descriptor`). Let me know if you find any other possible solution!
- Address https://github.com/bitcoindevkit/bdk/pull/1203#discussion_r1566263753 - thanks @notmandatory for the fix! I want to cherry pick it + add some docs to the load method

File: crates/chain/tests/test_keychain_txout_index.rs [hunk 52]
```diff
@@ -475,14 +619,83 @@ fn lookahead_to_target() {
...
+        /*
+        assert_eq!(
+            index_changeset,
+            bdk_chain::keychain::ChangeSet {
+                keychains_added: BTreeMap::default(),
+                last_revealed: [(desc_id_a, i as u32)].into(),
+            },
+            "must always increase last active if impl respects lookahead"
+        );
+        */
```
Comment (evanlinjin) [inline crates/chain/tests/test_keychain_txout_index.rs]: Can we fix this? If we can't do this without having `desc_id -> desc` then so be it.

**Comment by danielabrozzoni** [comment]
This is ready for another round of review :)

File: crates/chain/src/descriptor_ext.rs [hunk 53]
```diff
@@ -1,10 +1,28 @@
...
+}
 
 /// A trait to extend the functionality of a miniscript descriptor.
 pub trait DescriptorExt {
     /// Returns the minimum value (in satoshis) at which an output is broadcastable.
     /// Panics if the descriptor wildcard is hardened.
     fn dust_value(&self) -> u64;
+
+    /// Returns the descriptor id, calculated as the sha256 of the descriptor, checksum included.
+    fn descriptor_id(&self) -> DescriptorId;
```
Comment (ValuedMammal) [inline crates/chain/src/descriptor_ext.rs]: "checksum *not included"

**Review by ValuedMammal — APPROVED** [review]

File: crates/chain/src/keychain/txout_index.rs (hunk 37 above)
Comment (evanlinjin) [reply crates/chain/src/keychain/txout_index.rs]: Because `other` is changing `self`. Looping through changes and applying it to `self` is the more straightforward logic.

I made a PR to show how much simpler it can be: https://github.com/danielabrozzoni/bdk/pull/7

File: crates/chain/src/keychain/txout_index.rs [hunk 54]
```diff
@@ -99,13 +169,24 @@ const DEFAULT_LOOKAHEAD: u32 = 25;
...
 #[derive(Clone, Debug)]
 pub struct KeychainTxOutIndex<K> {
-    inner: SpkTxOutIndex<(K, u32)>,
-    // descriptors of each keychain
-    keychains: BTreeMap<K, Descriptor<DescriptorPublicKey>>,
+    inner: SpkTxOutIndex<(DescriptorId, u32)>,
+    // keychain -> (descriptor, descriptor id) map
+    keychains_to_descriptors: BTreeMap<K, (DescriptorId, Descriptor<DescriptorPublicKey>)>,
+    // descriptor id -> keychain map
+    descriptor_ids_to_keychain: BTreeMap<DescriptorId, (K, Descriptor<DescriptorPublicKey>)>,
```
Comment (evanlinjin) [inline crates/chain/src/keychain/txout_index.rs]: I think this was my suggestion. However, I just found out that this is unsound since multiple keychains can point to the same descriptor. Hence, a given `DescriptorId` can point to multiple keychains...

Comment (evanlinjin) [reply crates/chain/src/keychain/txout_index.rs]: This also means an outpoint can be associated with multiple keychains... Which is a bad API... The other option is to return duplicates if the caller associates the same descriptor to different keychains (which is not great either)...

Comment (evanlinjin) [reply crates/chain/src/keychain/txout_index.rs]: I demonstrated this problem with this test here: https://github.com/evanlinjin/bdk/commit/16366b47ef1e38fafe220433e8ad78c7ab5f4f6c

Comment (notmandatory) [reply crates/chain/src/keychain/txout_index.rs]: I agree with @ValuedMammal's suggestion on discord that we should simplify this mapping for now and support more complicated scenarios later if needed.

Can we go back to a requirement that a keychain -> descriptor mapping can't change? I think this is what @danielabrozzoni originally had.  As long as we document that it's invalid/unsupported it's OK to panics if someone tries to insert a mapping for a keychain or descriptor that already exists in a mapping.

Comment (evanlinjin) [reply crates/chain/src/keychain/txout_index.rs]: @notmandatory I would like to try something before we resort to that. Give me end of today.

Comment (evanlinjin) [reply crates/chain/src/keychain/txout_index.rs]: I have a solution, just need to clean it up and add documentation

Comment (evanlinjin) [reply crates/chain/src/keychain/txout_index.rs]: Fix implemented in #1428

Comment (danielabrozzoni) [reply crates/chain/src/keychain/txout_index.rs]: I agree that we should fix the changeset not being monotonic, but I don't like the approach taken in #1428, as it's complex and feels quite hacky honestly. You're letting the user add multiple keychains for a single descriptor, but then, since the whole API is based on the assumption that there is a single keychain associated with a descriptor, you're arbitrarily deciding that the "right" descriptor is the one with the highest `Ord`. 

I would simply disallow inserting a keychain for a descriptor id that already has a keychain associated. It's the easiest solution and makes way more sense imho.

Comment (notmandatory) [reply crates/chain/src/keychain/txout_index.rs]: Rather than doing something the user wouldn't expect I'd also rather disallow assigning already used descriptor_ids to new keychains. That doesn't mean we can't keep working on a more flexible solution, and by having the `descriptor_id` mapping already in this PR it sets the ground work. Further it shouldn't change the API if we can later allow changing the keychain of a descriptor, we just remove the panic and update the docs. 

🎉 In other news, I've tested this PR with my sqlite_store  (#1128)  and it's working fine for my simple unit tests and with one of the wallet examples. 

🔧 A few small PRs have gone in since this PR was rebased so it probably needs to be rebased again.

Comment (evanlinjin) [reply crates/chain/src/keychain/txout_index.rs]: > I would simply disallow inserting a keychain for a descriptor id that already has a keychain associated. It's the easiest solution and makes way more sense imho.

If you look at `ChangeSet::keychains_added`, it allows for changing the descriptor for a keychain. If we want to implement what you suggested, the `Append::append` implementation needs to iterate through all descriptors and panic if there is a match (which would be horrible). If we only panic in `KeychainTxOutIndex`, then changesets cannot be monotonic (as shown in ffba1b56ba59ab95aa69d9f38bb790c20125d81c).

> as it's complex

I don't think it is. We are just storing multiple keychains per descriptor id. If you look at a1d55f2662b40e61c03234681be6f4c718b6b6e4, the logic barely changes and I would argue that `insert_descriptor` is now made simpler.

> arbitrarily... "right" descriptor is the one with the highest `Ord`.

Not true. It's based on `Ord` so it's not arbitrary.

> Rather than doing something the user wouldn't expect

If we document it, the caller will expect it. Same with our alternative solution (which is panicing). I would argue that the panicing approach would make our API highly unpredictable since there will be scenarios where applying an aggregated changeset will not panic, but applying the individual changesets one by one will (as mentioned above).

> Further it shouldn't change the API

It doesn't change the API at all? The behavior only defers if the caller associates the same descriptor to multiple keychains. One is to panic (which I already demonstrated is bad), the other is to use `Ord` to return the highest-ranked keychain.

---

I might need a clear argument to be convinced that the ranked-keychain solution is a bad idea. Give an example?

Comment (LLFourn) [reply crates/chain/src/keychain/txout_index.rs]: > > I would simply disallow inserting a keychain for a descriptor id that already has a keychain associated. It's the easiest solution and makes way more sense imho.
> 
> If you look at `ChangeSet::keychains_added`, it allows for changing the descriptor for a keychain. If we want to implement what you suggested, the `Append::append` implementation needs to iterate through all descriptors and panic if there is a match (which would be horrible). If we only panic in `KeychainTxOutIndex`, then changesets cannot be monotonic (as shown in [ffba1b5](https://github.com/bitcoindevkit/bdk/commit/ffba1b56ba59ab95aa69d9f38bb790c20125d81c)).

Why can't the ChangeSet::append implementation be different from the insert method. The changeset can be montone while the insert method errors when you try and reassign a keychain.

> 
> > as it's complex
> 
> I don't think it is. We are just storing multiple keychains per descriptor id. If you look at [a1d55f2](https://github.com/bitcoindevkit/bdk/commit/a1d55f2662b40e61c03234681be6f4c718b6b6e4), the logic barely changes and I would argue that `insert_descriptor` is now made simpler.
> 
> > arbitrarily... "right" descriptor is the one with the highest `Ord`.
> 
> Not true. It's based on `Ord` so it's not arbitrary.
> 
> > Rather than doing something the user wouldn't expect

`Ord` of descriptors is very very arbitrary. The `cmp` output has no bearing on the semantics of the descriptor.

> 
> If we document it, the caller will expect it. Same with our alternative solution (which is panicing). I would argue that the panicing approach would make our API highly unpredictable since there will be scenarios where applying an aggregated changeset will not panic, but applying the individual changesets one by one will (as mentioned above).
> 

The documentation would be very tl;dr. It think it should just say you can't reassign keychains and we don't guarantee what happens if you do. We can then of course make whatever does happen relatively sane by maintaining montonicity in the `ChangeSet::append` method.

> > Further it shouldn't change the API
> 
> It doesn't change the API at all? The behavior only defers if the caller associates the same descriptor to multiple keychains. One is to panic (which I already demonstrated is bad), the other is to use `Ord` to return the highest-ranked keychain.
> 
> I might need a clear argument to be convinced that the ranked-keychain solution is a bad idea. Give an example?

The code is just complicated and the documentation is long winded and it doesn't get us anything. Sure making the ChangeSet monotone is a good idea but functions called on the actual txout index can just panic or error when you try to reassign keychains.

Comment (evanlinjin) [reply crates/chain/src/keychain/txout_index.rs]: Just had a call with @LLFourn. He pointed out that my changes in #1428 does not actually make changesets monotone as we still need to rely on the order of the changesets. He also noted that there may be a misunderstanding that the ranking is based on `Ord` of descriptors when this is not the case. We are basing it on the `Ord` of keychains. He also noted that the main value of these changes is to allow multiple keychains to point to the same descriptor (since we can avoid doing #1390). He also noted that when he proposed the `DescriptorId` concept, he didn't take into consideration that we can just disallow changing the descriptor associated with a keychain once it is set in `Append::append` (basically ignoring reassignment). If we disallow reassigning descriptors, we can do away with the `DescriptorId` completely.

Comment (evanlinjin) [reply crates/chain/src/keychain/txout_index.rs]: In either of these solutions, @LLFourn pointed out that we should error when we call `insert_descriptor` when trying to reassign a keychain's descriptor. However, we should either ignore/allow it (no error/panic) when calling `apply_changeset` or `Append::append`.

Comment (danielabrozzoni) [reply crates/chain/src/keychain/txout_index.rs]: > He pointed out that my changes in https://github.com/bitcoindevkit/bdk/pull/1428 does not actually make changesets monotone as we still need to rely on the order of the changesets.

Why is it a problem if applying changesets is not commutative?

The way I see it, we have a KeychainTxOutIndex with monotone descriptors, and these descriptors can be labeled with certain keychains, and labels can be removed. One operation we can do on the index is "add this certain label for this descriptor", reflected in the `keychains_added` map. If we want this "relabeling" operation to still exist, then I don't see a way for having commutative changesets. Labeling a descriptor with `K` and then relabeling it with `K'` is always going to yield a different result than labeling it with `K'` and then with `K`.

Comment (evanlinjin) [reply crates/chain/src/keychain/txout_index.rs]: It's not a problem. I was just using the wrong terminology.

File: crates/chain/src/keychain/txout_index.rs (hunk 37 above)
Comment (notmandatory) [reply crates/chain/src/keychain/txout_index.rs]: I agree that @evanlinjin 's approach is easier to read and looks to be more efficient with only one loop through `other.last_revealed`. The way I read it is: 
1. extend my keychains_added with other's keychains_added
2. update my last_revealed with just the changes in other's last_revealed

Comment (notmandatory) [reply crates/chain/src/keychain/txout_index.rs]: BTW, based on recent [discussion](https://github.com/bitcoindevkit/bdk/pull/1203/files#r1592046771) step 1. above will be more complicated if we want to skip adding the keychain if `K` is pointing to a different descriptor or `Descriptor` is assigned to a different `K`. Or don't check for it since this situation should be prevented by  `insert_descriptor`.

**Comment by danielabrozzoni** [comment]
After a call with @evanlinjin we decided to go with his solution of using `Ord` by Keychain for methods that *return* a K (one thing I didn't understand, is that methods that take in a K will continue to work normally).

Then, either of us will open an issue in order to discuss further improvements (I don't like this solution that much and proposed one where we'd return only the latest keychain added, using a Vec instead of a set, but it still needs some discussion). 

At the moment, replacing descriptors is still allowed, and having multiple keychains for the same descriptor is still allowed, even when using `insert_descriptor`.

**Review by evanlinjin — APPROVED** [review]
ACK 86711d4f46f467c651238ad3804fdbe1d22a8600

File: crates/chain/src/keychain/txout_index.rs [hunk 55]
```diff
@@ -79,14 +152,43 @@ const DEFAULT_LOOKAHEAD: u32 = 25;
...
+/// even though multiple keychain variants identify the same descriptor.
+///
+/// ## Reassigning the descriptor of a single keychain
+///
+/// Descriptors added to [`KeychainTxOutIndex`] are never removed. However, a keychain that
+/// identifies a descriptor can be reassigned to identify a different descriptor. This may result in
+/// a situation where a descriptor has no associated keychain(s), and relevant [`TxOut`]s,
+/// [`OutPoint`]s and [`Script`]s (of that descriptor) will not be return by [`KeychainTxOutIndex`].
+/// Therefore, reassigning the descriptor of a single keychain is not recommended.
+///
```
Comment (notmandatory) [inline crates/chain/src/keychain/txout_index.rs:191]: 👍 good explanation!

**Review by notmandatory — APPROVED** [review]
ACK b9902936a0d17498eec8866233d89b2882d0af8f

Great job everyone sticking with this one! it was a real journey.

File: crates/chain/src/keychain/txout_index.rs [hunk 56]
```diff
@@ -99,13 +201,27 @@ const DEFAULT_LOOKAHEAD: u32 = 25;
...
+/// [`txouts`]: KeychainTxOutIndex::txouts
+/// [`unused_spks`]: KeychainTxOutIndex::unused_spks
 #[derive(Clone, Debug)]
 pub struct KeychainTxOutIndex<K> {
-    inner: SpkTxOutIndex<(K, u32)>,
-    // descriptors of each keychain
-    keychains: BTreeMap<K, Descriptor<DescriptorPublicKey>>,
+    inner: SpkTxOutIndex<(DescriptorId, u32)>,
+    // keychain -> (descriptor, descriptor id) map
+    keychains_to_descriptors: BTreeMap<K, (DescriptorId, Descriptor<DescriptorPublicKey>)>,
```
Comment (LLFourn) [inline crates/chain/src/keychain/txout_index.rs:211]: The `Descriptor` does not need to be here. You can just look it up in `descriptor_ids_to_descriptors`.

**Comment by LLFourn** [comment]
POST merge ACK. Thanks for just one of the non-perfect options and pushing this one through. Let's see how we feel about it after using it.

I left one comment that I think should be addressed.
