### PR TITLE
Store the last sync time and block height

### LINKED ISSUE #413: BDK will select coinbase inputs that are not matured yet
I just did `generatetoaddress` to a wallet address and tried to create a transaction. BDK wallet did it but RPC returned: `"sendrawtransaction RPC error: {\"code\":-26,\"message\":\"bad-txns-premature-spend-of-coinbase, tried to spend coinbase at depth 38\"}"`

### LINKED ISSUE #455: Save the latest block height in the database
I'm working on a fix for #413 and #238: it would be useful for both of them to know the "current height" (to know if the coinbase outputs are mature or in the case of #238 to check if we have reached a given minimum number of confirmations).

Since we might not have a `Blockchain` when running calls like `get_balance`, we should save the block height in the db every time we sync (and maybe the timestamp as well).

This could also be used to, for instance, only sync automatically if the data are `x` minutes old or something like that.

### PR DESCRIPTION
**Pull request by afilini**
### Description

Update the `Database` trait to allow storing the block height and timestamp of the last `sync` of a `Wallet`. This will allow having a rough estimation of the "current" height, even in parts of the code that don't have network access (tx creation, computing the balance, etc), at least in non-airgapped wallets that are periodically synced.

After this is ready I'm planning to work on a PR to close #413, essentially making BDK aware of what can be spent and what is still not "mature" (initially only for coinbase UTXOs which are trivial, later on ideally also for any UTXO that has a timelock, which is a lot trickier).

Closes #455.

### Notes to the reviewers

Opening this in draft mode, since it includes some commits from #454.

Random open points:

1. I was thinking about renaming `ConfirmationTime` because that name doesn't really make sense in this context, but I couldn't come up with a decent alternative. I'm open to suggestions if you have any. 
2. I'm not sure what I've done with the sqlite database is ideal, let me know if you think I could use a better structure. Initially I used to add an entry in the table for every `sync`, and then I would only return the latest one. That seemed pretty inefficient, considering that I was storing stuff that were by definition never read, so I changed it to the current structure.. but this feels more NoSQL-like so I still don't know which one I like best.

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### New Features:

* [x] I've added tests for the new feature
* [x] I've added docs for the new feature
* [x] I've updated `CHANGELOG.md`

#### Bugfixes:

* [x] This pull request breaks the existing API
* [x] I'm linking the issue being fixed by this PR

### CODE REVIEW

**Comment by notmandatory** [comment]
My rename suggestion for `ConfirmationTime` is simply `Confirmation`and then the field would be `TransactionDetails.confirmation`.

**Comment by notmandatory** [comment]
It looks like this PR has come commits that are already in `master`, can it be rebased to simplify the history?
Don't need:
a348dbdcfe2fa9abc92eab7286dde1177fef65bd
548e43d928d1492784dc465a28fa99b9ca263b9f
548e43d928d1492784dc465a28fa99b9ca263b9f
548e43d928d1492784dc465a28fa99b9ca263b9f

**Comment by LLFourn** [comment]
Can we think about getting rid of the block height request in `Wallet::new` after this and just using the one from the database.

**Comment by afilini** [comment]
> Can we think about getting rid of the block height request in Wallet::new after this and just using the one from the database.

Yup, that would be great. With that you would only need the network to sync, everything else would work offline as well, which is reasonable

File: src/database/keyvalue.rs [hunk 1]
```diff
@@ -82,6 +82,13 @@ macro_rules! impl_batch_operations {
             Ok(())
         }
 
+        fn set_last_sync_time(&mut self, ct: ConfirmationTime) -> Result<(), Error> {
```
Comment (LLFourn) [inline src/database/keyvalue.rs]: So I'm working towards adding different types of syncs. e.g. only sync addresses given out (no stop-gap). Maybe only sync addresses given out recently or only sync external keychain etc.

Could we leave the door open to that by making a `SyncTime` struct which has the blocktime (whose type is unfortunately called `ConfirmationTime`) as a field? It wouldn't hurt to add the local time to it. It's possible we'd want more metadata about a sync in the future and it'd make it easier from a DB updating point of view to serialize it in this way.

**Review by LLFourn — CHANGES_REQUESTED** [review]
LGTM -- one thing I'd like you to consider changing.

**Comment by artfuldev** [comment]
Regarding `ConfirmationTime`, I think we can just use something like `BlockInfo` which has a few details from:
image

Currently, we use the height and timestamp as an indication of confirmation and last sync "time". Maybe we add hash next. And we can refer to it in a confirmed transaction as `block: BlockInfo` / while syncing as `last_synced: BlockInfo`.

File: src/database/keyvalue.rs (hunk 1 above)
Comment (afilini) [reply src/database/keyvalue.rs]: I tried implementing this but I got stuck because we don't have a way to get the tip hash with the current `Blockchain` trait.

Since I would have to make a breaking change to the trait I'm thinking I might as well split it up like you described during our last call.

I'm not sure if we should hold this PR until that's ready or just go ahead and merge it without block_hash and add that later on.

Comment (LLFourn) [reply src/database/keyvalue.rs]: I think merge without that now and follow up with a PR that adds `Option<BlockHash>` to the struct. I still think that we don't want to add this to `BlockTime` but rather a struct like `SyncTime` that contains a `BlockTime`. Also `SyncTime` should probably contain the UTC time that the sync was finished (in this PR).

Comment (afilini) [reply src/database/keyvalue.rs]: Yeah in my local branch I had a separate structure that contained the `BlockTime` and the block hash.

I will add just the UTC time for now, we'll add the block hash in a following PR

Comment (LLFourn) [reply src/database/keyvalue.rs]: You might consider adding a field for it in the sqlite table otherwise we have to do a table update and I'm not sure we have a db upgrade plan yet :S?

**Comment by notmandatory** [comment]
Looks like it needs a rebase to fix the CHANGELOG then is ready to go.

**Comment by afilini** [comment]
Done!

**Review by notmandatory — APPROVED** [review]
ACK 5830226216218f2b3ce89206c58fb24c88ef8c9a
