### PR TITLE
ci: check-docs for all workspace packages

### LINKED ISSUE #2152: Check `cargo rustdoc` for all workspace members
Currently `cargo doc --workspace --no-deps` throws warnings for some of our workspace packages, for example due to redundant_explicit_links and broken_intra_doc_links. To prevent documentation errors from persisting consider adding a CI job to check building the docs for each package.

### Tasks

- [ ] Add `ci/check-docs.sh` script that runs `cargo rustdoc` for each package in the workspace. The script should fail if any cargo rustdoc invocations produce warnings
- [ ] Add a `check-docs` job to `cont_integration.yml` that calls the check-docs.sh script
- [ ] Add a justfile recipe `just doc` that similarly executes check-docs.sh

Alternatively, use a 1-liner somewhere in `cont_integration.yml` (e.g. in build-test) such as

    RUSTDOCFLAGS='-D warnings' cargo doc --workspace --no-deps

however that's not as explicit as it could be with respect to the crate names.

**Build environment**  
- BDK tag/commit: fb05873a
- OS+version:   
- Rust/Cargo version: 1.93.1
- Rust/Cargo target:   

**Which backend(s) are relevant (if any)?**
- [ ] Electrum
- [ ] Esplora
- [ ] Bitcoin Core RPC
- [x] None / not backend-related (e.g. `bdk_chain`, `bdk_core`)
- [ ] Other (please specify): `____`

**Is this blocking production use?**
- [ ] Yes
- [x] No

### PR DESCRIPTION
**Pull request by shinigami-777**
fixes #2152 

### Description

This PR adds new CI job `check-docs` to validate that documentation builds for all workspace packages, also adds a new justfile recipe `just doc`.

It also fixes the existing errors in `bdk_chain` and `bdk_core`.

### Changelog notice

```
### Added

- ci: add new `check-docs` job.

### Changed

- fix(docs): in `keychain_txout.rs` and `spk_client.rs`
```

#### All Submissions:

* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)

#### New Features:

* [ ] I've added tests for the new feature
* [x] I've added docs for the new feature

#### Bugfixes:

* [ ] This pull request breaks the existing API
* [ ] I've added tests to reproduce the issue which are now passing
* [x] I'm linking the issue being fixed by this PR

### CODE REVIEW

**Comment by evanlinjin** [comment]
Thanks for this work.

I think it also makes sense to also include the documentation fixes in this PR (as a separate commit).

**Comment by ValuedMammal** [comment]
@shinigami-777 Can you add a commit addressing the check-docs failures? I recommend removing the redundant explicit link targets in `keychain_txout.rs` for types that are already in scope (i.e. `bitcoin::Script`). Then in `spk_client.rs` update the docs with a valid link to the [`KeychainTxOutIndex`](https://docs.rs/bdk_chain/0.23.2/bdk_chain/indexer/keychain_txout/struct.KeychainTxOutIndex.html) type.

**Comment by shinigami-777** [comment]
> Thanks for this work.
> 
> I think it also makes sense to also include the documentation fixes in this PR (as a separate commit).

I have added some doc changes to the `CONTRIBUTING.md` in [this](https://github.com/bitcoindevkit/bdk/pull/2158/changes/5738ddcd1bc62d076d4868f8990a3b277aa514cc) commit.

**Comment by shinigami-777** [comment]
Updated `keychain_txout.rs` and `spk_client.rs`. Now all doc checks are successful.

File: justfile [hunk 1]
```diff
@@ -57,3 +58,7 @@ _test-testenv:
 
 # Run pre-push suite: format, check, and test
 pre-push: fmt check test
```
Comment (oleonardolima) [inline justfile:60]: nit: it's also a good idea to add the doc to pre-push too.

File: ci/check-docs.sh [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+    echo ""
+done
+
+if [ $FAILED -eq 1 ]; then
+    echo -e "${RED}Documentation check failed for one or more packages${NC}"
+    exit 1
+else
+    echo -e "${GREEN}All documentation checks passed!${NC}"
+    exit 0
+fi
```
Comment (oleonardolima) [inline ci/check-docs.sh]: @shinigami-777 What's the benefit for having this instead of just calling `RUSTDOCFLAGS='-D warnings' cargo doc --workspace --no-deps` ?

File: crates/core/src/spk_client.rs [hunk 3]
```diff
@@ -137,8 +137,7 @@ impl<I, D> SyncRequestBuilder<I, D> {
     /// # Example
     ///
     /// Sync revealed script pubkeys obtained from a
-    /// [`KeychainTxOutIndex`](../../bdk_chain/indexer/keychain_txout/struct.KeychainTxOutIndex.
-    /// html).
+    /// [`KeychainTxOutIndex`](https://docs.rs/bdk_chain/0.23.2/bdk_chain/indexer/keychain_txout/struct.KeychainTxOutIndex.html).
```
Comment (oleonardolima) [inline crates/core/src/spk_client.rs]: nit: it's best to use latest
```suggestion
    /// [`KeychainTxOutIndex`](https://docs.rs/bdk_chain/latest/bdk_chain/indexer/keychain_txout/struct.KeychainTxOutIndex.html).
```

File: .github/workflows/cont_integration.yml [hunk 4]
```diff
@@ -166,3 +166,21 @@ jobs:
...
+        with:
+          persist-credentials: false
+      - name: Install Rust toolchain
+        uses: actions-rust-lang/setup-rust-toolchain@v1
+        with:
+          toolchain: ${{ needs.prepare.outputs.rust_version }}
+          override: true
+          cache: true
+      - name: Check docs
+        run: ./ci/check-docs.sh
```
Comment (oleonardolima) [inline .github/workflows/cont_integration.yml]: As I mentioned below I don't think we need another file, calling `RUSTDOCFLAGS='-D warnings' cargo doc --workspace --no-deps` here and in justfile is much better.

**Review by oleonardolima — COMMENTED** [review]
Thanks for working on this one!

I left some comments as I don't see use for a new `check-docs.sh` file we should probably just call the cargo commands directly. Let's see what other thinks about it.

Also, you could probably squash it into two commits, something like this:

- ci: add new `check-docs` job and recipe in justfile
- fix(docs): in `keychain_txout.rs` and `spk_client.rs`

File: ci/check-docs.sh (hunk 2 above)
Comment (shinigami-777) [reply ci/check-docs.sh]: Removed `ci/check-docs.sh`. I did the same using `RUSTDOCFLAGS='-D warnings' cargo doc --workspace --no-deps`.

File: .github/workflows/cont_integration.yml (hunk 4 above)
Comment (shinigami-777) [reply .github/workflows/cont_integration.yml]: Changed to just calling `RUSTDOCFLAGS='-D warnings' cargo doc --workspace --no-deps`.

File: justfile (hunk 1 above)
Comment (shinigami-777) [reply justfile:60]: I added the doc for pre-push in [this commit](https://github.com/bitcoindevkit/bdk/pull/2158/changes/c4b8e93d5dceab959131d6eeec164654d1aa870c).

**Comment by shinigami-777** [comment]
@oleonardolima Thanks for reviewing. I have made the changes and squashed them in 2 commits: [c4b8e93](https://github.com/bitcoindevkit/bdk/pull/2158/commits/c4b8e93d5dceab959131d6eeec164654d1aa870c) and [1d1e985](https://github.com/bitcoindevkit/bdk/pull/2158/commits/1d1e985eff0073e78df0a511d810ca71ae525932)

File: justfile (hunk 1 above)
Comment (oleonardolima) [reply justfile:60]: I mean, add the `doc` to the list of commands called (e.g `pre-push: fmt check test doc`); not a blocker though.

**Review by oleonardolima — APPROVED** [review]
utACK 1d1e985eff0073e78df0a511d810ca71ae525932

**Comment by oleonardolima** [comment]
I fixed a trailing whitespace in 19d1269f814f445b0337d6c66cd694358afede18.

**Review by oleonardolima — APPROVED** [review]
ACK 9c8b564fb4d9fc0ecf6a03f1cd6668de73555eb3
