### PR TITLE
Fix: Wallet sync may decrement address index

### LINKED ISSUE #649: Syncing causes get_address index to decrement
This only happens with certain xpubs. Code:
```
    #[test]
    fn test_address_looping() {
        let wallet =
            Wallet::new("wpkh([5d14cd2a/84h/1h/0h]tpubDCWhawC5a8Rgx6y7rk5qHtueax2MVWfdfobzEcmcSvQUDYq94dnqyx6KAFbxCocxQnnLuFcRYFWmvXS9DtWRYqJeU33pcvsam9AaozJXS1P/0/*)",
                        None,
                        Network::Testnet,
                        MemoryDatabase::new()).unwrap();

        for _ in 0..15 {
            let address = wallet.get_address(AddressIndex::New).unwrap();
            println!("{}:  {}", address.index, address.address.to_string());
        }

        println!("wallet.sync()");
        let client = get_electrum_client(-1, "ssl://electrum.blockstream.info:60002").unwrap();
        let blockchain = ElectrumBlockchain::from(client);

        wallet.sync(&blockchain, SyncOptions { progress: None }).unwrap();

        for _ in 0..15 {
            let address = wallet.get_address(AddressIndex::New).unwrap();
            println!("{}:  {}", address.index, address.address.to_string());
        }
    }
```
Output:
```
0:  tb1qghhpvphu6rd6ygwuurw3p9cg7se84taj2vssdu
1:  tb1q79crajpg7y838vmqngerx6eqv5tuytzlk7cx3n
2:  tb1qcae3r5r6pv7p59s9vy3depphz3vffuqhrxm0e3
3:  tb1qemh2gefeeydc8k649tqlhz4egr3pktnt72h9xz
4:  tb1qckls5f7xrz29k3jtuw67ul6dp6mlz39m6r0xmj
5:  tb1qvycmqxyffvllmt7u8732nr7l576s9al6qlfleq
6:  tb1qrxm4qpdjevpzjmh7x7048kng6ys0audzz50jwn
7:  tb1q285u2994gsyuplqajm0ttadh238pp2clsutxc3
8:  tb1q5cfe3nrwtl4qfxyavnagxe7lqchskdjvkeqw50
9:  tb1qpa8375ve0um755svsm7u8r73ltk5xc0hwmp240
10:  tb1qc3nd440fqzx3zzwvm2n47g5dn2ahpcs74e58rw
11:  tb1qur22cvhcwtez5d7f0jeajg6ul22chqvcqwv3pg
12:  tb1qyud6sa4dseyx5k8vzp9yhq2nef9p5zrcv7pjny
13:  tb1qq50glc8hh20k8fh39u9xedshy6plra69cx4xxt
14:  tb1q92llgymvnl90y2a6ku2fztfw4heg400psph740
wallet.sync()
3:  tb1qemh2gefeeydc8k649tqlhz4egr3pktnt72h9xz
4:  tb1qckls5f7xrz29k3jtuw67ul6dp6mlz39m6r0xmj
5:  tb1qvycmqxyffvllmt7u8732nr7l576s9al6qlfleq
6:  tb1qrxm4qpdjevpzjmh7x7048kng6ys0audzz50jwn
7:  tb1q285u2994gsyuplqajm0ttadh238pp2clsutxc3
8:  tb1q5cfe3nrwtl4qfxyavnagxe7lqchskdjvkeqw50
9:  tb1qpa8375ve0um755svsm7u8r73ltk5xc0hwmp240
10:  tb1qc3nd440fqzx3zzwvm2n47g5dn2ahpcs74e58rw
11:  tb1qur22cvhcwtez5d7f0jeajg6ul22chqvcqwv3pg
12:  tb1qyud6sa4dseyx5k8vzp9yhq2nef9p5zrcv7pjny
13:  tb1qq50glc8hh20k8fh39u9xedshy6plra69cx4xxt
14:  tb1q92llgymvnl90y2a6ku2fztfw4heg400psph740
15:  tb1qzyzavz6qc9qn52hxrfhpddztas84r69ytqzgyh
16:  tb1qgfwvg3tpvkedzl5exmmwjlpzx74rtmkw0dtemg
17:  tb1qh6vsnhff77tr9g0yg5jum0n3h5ccesnhldfsjw
```
One would expect `get_address` subsequent to `sync` to return an address at index 15.

**Build environment**  
 - BDK tag/commit: a328607d27feb5d556df99ec6beabc41cc655160
 - OS+version: Ubuntu 22.04
 - Rust/Cargo version: 1.54.0
 - Rust/Cargo target: x86_64

### PR DESCRIPTION
**Pull request by evanlinjin**
### Description

Fixes #649 

It is critical to ensure `Wallet::get_address` with `AddressIndex::new` always returns a new and unused address.

This bug seems to be Electrum-specific. The fix is to check address index updates to  ensure that newly suggested indexes are not smaller than indexes already in database.

### Notes to the reviewers

I have written new tests in `/testutils/blockchain_tests.rs` that tests all `Blockchain` implementations.

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### Bugfixes:

~* [ ] This pull request breaks the existing API~
* [x] I've added tests to reproduce the issue which are now passing
* [x] I'm linking the issue being fixed by this PR

### CODE REVIEW

**Comment by evanlinjin** [comment]
### TODO
- [ ] I should add a test for possible regressions. Ensure that wallet index increments when expected after sync.
- [ ] Fix CI errors

**Comment by evanlinjin** [comment]
These tests should be made universal so we can test all `Blockchain` implementations. I'm on it now.

**Comment by evanlinjin** [comment]
Update: this bug affects `RpcBlockchain` as well. Probably in a different manner though.

File: src/blockchain/script_sync.rs [hunk 1]
```diff
@@ -314,6 +314,26 @@ impl<'a, D: BatchDatabase> State<'a, D> {
...
+
+        // Ensure `last_active_index` does not decrement database's current state.
+        let index_updates = self
+            .last_active_index
+            .iter()
+            .filter_map(|(keychain, index)| {
+                let db_index = self
+                    .db
+                    .get_last_index(*keychain)
+                    .unwrap_or(None)
```
Comment (afilini) [inline src/blockchain/script_sync.rs]: I think here ideally we should propagate the error instead of "downgrading" it to a `None` (otherwise again we may overwrite the last derivation index accidentally).

On the other end, I'm not sure what would be the best way to do it: the only thing I could think of would be to replace this `filter_map` with just a map, and return a `Result` in the closure so that you can collect a `Result<Vec<_>>` and propagate the error with `?`. Then you'll have to filter out the `None`s before iterating the list.

Comment (evanlinjin) [reply src/blockchain/script_sync.rs]: This is my current solution, would this be satisfactory?

https://github.com/bitcoindevkit/bdk/blob/edf5ab7ea72189fc978271fee362159c02415c48/src/blockchain/script_sync.rs#L318-L344

File: src/testutils/blockchain_tests.rs [hunk 2]
```diff
@@ -651,6 +652,61 @@ macro_rules! bdk_blockchain_tests {
...
+                let (wallet, blockchain, _descriptors, mut test_client) = init_single_sig();
+
+                const ADDRS_TO_FUND: u32 = 7;
+                const ADDRS_TO_IGNORE: u32 = 11;
+
+                let mut first_addr_index: u32 = 0;
+
+                (0..ADDRS_TO_FUND + ADDRS_TO_IGNORE).for_each(|i| {
+                    let new_addr = wallet.get_address(AddressIndex::New).unwrap();
+                    println!("new_addr.index: {}", new_addr.index);
```
Comment (notmandatory) [inline src/testutils/blockchain_tests.rs]: I think you forgot to remove this `println!`.

Comment (evanlinjin) [reply src/testutils/blockchain_tests.rs]: Removed!

File: src/blockchain/script_sync.rs [hunk 3]
```diff
@@ -314,6 +314,35 @@ impl<'a, D: BatchDatabase> State<'a, D> {
...
+                match db_result {
+                    // Only update on OK db_result with db index < proposed index
+                    Ok(db_index) if db_index < index => Some((*keychain, index)),
+                    _ => None,
+                }
+            })
+            .collect::<Vec<_>>();
+
+        // report error on db fail
+        db_result?;
```
Comment (rajarshimaitra) [inline src/blockchain/script_sync.rs]: We can just match the whole thing in one iterator and we don't have to initialize and pass around the errors..
This comparison logic can be written something like this.. 
```
        let index_updates = self
            .last_active_index
            .iter()
            .map(|(keychain, sync_index)| {
                let db_index = match self.db.get_last_index(*keychain).transpose() {
                    Some(Ok(db_index)) => Ok(std::cmp::max(db_index as usize, *sync_index)),
                    Some(e) => e.map(|i| i as usize),
                    None => Ok(*sync_index),
                };
                db_index.and_then(|index| Ok((*keychain, index as usize)))
            })
            .collect::<Result<Vec<(KeychainKind, usize)>, _>>()?;
```
To me this looks much simple to read..

**Review by rajarshimaitra — CHANGES_REQUESTED** [review]
Concept ACK..

I verified that the test is only failing for Electrum, but not for RPC or Esplora.. Maybe worth exploring further.. 

I have a code suggestion for the same checking logic.. It seems we can get the check done in much sorter codes.

File: src/blockchain/script_sync.rs (hunk 3 above)
Comment (evanlinjin) [reply src/blockchain/script_sync.rs]: @rajarshimaitra Thank you for providing an elegant solution. I'll add a shoutout in the commit (almost feel bad for just copying it).

Comment (evanlinjin) [reply src/blockchain/script_sync.rs]: I did not know you could collect into a `Result<>`, that is pretty useful.

Comment (evanlinjin) [reply src/blockchain/script_sync.rs]: I don't think we need to `transpose` with your solution:
```rust
        let index_updates = self
            .last_active_index
            .iter()
            .map(|(keychain, sync_index)| {
                let sync_index = *sync_index as u32;
                let index_res = match self.db.get_last_index(*keychain) {
                    Ok(Some(db_index)) => Ok(std::cmp::max(db_index, sync_index)),
                    Ok(None) => Ok(sync_index),
                    Err(err) => Err(err),
                };
                index_res.map(|index| (*keychain, index))
            })
            .collect::<Result<Vec<(KeychainKind, u32)>, _>>()?;
```

File: src/blockchain/script_sync.rs (hunk 1 above)
Comment (evanlinjin) [reply src/blockchain/script_sync.rs]: Continued here: https://github.com/bitcoindevkit/bdk/pull/653#discussion_r916074702

File: src/blockchain/script_sync.rs (hunk 3 above)
Comment (rajarshimaitra) [reply src/blockchain/script_sync.rs]: Yeah converting `Vec<Result<>>` into `Result<Vec<>>` is very useful and allows us to do a lot just with iterators.. 

Yes agree, this looks much better than the original..

**Review by rajarshimaitra — APPROVED** [review]
tACK ac5f0af2f7465910c2e1fdd41f83a31126a91de7

Thanks for the quick update..

**Comment by afilini** [comment]
ACK af6bde3997ac2fe4cfdbb691f2af2e802f0ab7c6

I'll wait for the CI to finish and then I'll merge this.
